#!/usr/bin/env python3
"""Render the report-only localization snapshot from existing app translations.

Prints source (or an apply_patch patch); never edits files or reads live data.
The extension cannot import the app's actor-bound localization/state helpers.
"""
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
STRING = r'"((?:[^"\\]|\\.)*)"'
ENTRY = re.compile(r'^\s*' + STRING + r'\s*:\s*' + STRING + r',?\s*$', re.M)
LANGUAGES = {'es': '', 'de': '+German', 'fr': '+French', 'pt': '+Portuguese',
             'pl': '+Polish', 'tr': '+Turkish', 'hi': '+Hindi'}


def report_keys():
    view = (ROOT / 'LatchReport/UsageInsightsView.swift').read_text()
    # Includes literal helper arguments, period titles, and conditional labels.
    keys = {json.loads('"' + key + '"') for key in re.findall(
        r'\b(?:insightsText|heading|format|rangeButton|pageButton)\(\s*' + STRING, view)}
    keys.update(json.loads('"' + key + '"') for key in re.findall(r'title:\s*' + STRING, view))
    keys.update({'Today so far', 'Full reported coverage', 'Partial reported coverage',
                 'Daily usage', 'Weekly totals', 'Tap a bar to see that day.', 'Tap a bar to see that week.',
                 'Expanded', 'Compact'})
    keys.update({'Week', 'Last seven completed days', 'Previous seven completed days'})
    return keys


def render():
    keys = report_keys()
    lines = [
        '// Generated by Tests/GenerateUsageLocalization.py; app translations are the source.',
        '// Read-only preferences; no measured usage leaves this report extension.',
        'import Foundation', '',
        'nonisolated private func insightsLanguageCode() -> String {',
        '    let supported = ["en", "es", "de", "fr", "pt", "pl", "tr", "hi"]',
        '    if let saved = UserDefaults(suiteName: AppGroup.id)?.string(forKey: "latch.language"),',
        '       supported.contains(saved) { return saved }',
        '    let preferred = Locale.preferredLanguages.first ?? "en"',
        '    let code = Locale(identifier: preferred).language.languageCode?.identifier',
        '        ?? String(preferred.prefix(2))',
        '    return supported.contains(code) ? code : "en"',
        '}', '',
        'nonisolated func insightsText(_ key: String) -> String {',
        '    switch insightsLanguageCode() {',
    ]
    for code, suffix in LANGUAGES.items():
        pairs = ENTRY.findall((ROOT / f'Shared/Localization{suffix}.swift').read_text())
        table = {json.loads('"' + key + '"'): json.loads('"' + value + '"')
                 for key, value in pairs}
        # Numeric/date placeholders need no language-specific text.
        table.setdefault('%@ – %@', '%@ – %@')
        missing = keys - table.keys()
        if missing:
            raise ValueError(f'{code}: missing report keys {sorted(missing)}')
        lines += [f'    case "{code}":', f'        // LANGUAGE {code}',
                  '        let table: [String: String] = [']
        for key in sorted(keys):
            lines.append('            ' + json.dumps(key, ensure_ascii=False) + ': '
                         + json.dumps(table[key], ensure_ascii=False) + ',')
        lines += ['        ]', '        // END LANGUAGE', '        return table[key] ?? key']
    lines += ['    default: return key', '    }', '}', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    source = render()
    target = ROOT / 'LatchReport/UsageInsightsLocalization.swift'
    if '--check' in sys.argv:
        assert target.read_text() == source, 'Regenerate the extension-local translation snapshot'
        print(f'Usage report localization snapshot matches {len(report_keys())} keys × 7 languages')
    elif '--patch' in sys.argv:
        if target.exists():
            print('*** Begin Patch\n*** Update File: ' + str(target) + '\n@@')
            print('\n'.join('-' + line for line in target.read_text().splitlines()))
        else:
            print('*** Begin Patch\n*** Add File: ' + str(target))
        print('\n'.join('+' + line for line in source.splitlines()))
        print('*** End Patch')
    else:
        print(source, end='')
