//
//  Localization+Turkish.swift
//  Full in-app localization table. Missing keys fall back to English.
//

import Foundation

let turkishStrings: [String: String] = [
    "Demora now speaks more languages": "Demora artık daha fazla dil konuşuyor",
    "We've added support for German, French, Portuguese, Polish, Turkish, and Hindi.": "Almanca, Fransızca, Portekizce, Lehçe, Türkçe ve Hintçe desteği ekledik.",
    "Choose your language here. You can change it anytime under Settings → Appearance → Language.": "Dilinizi buradan seçin. Daha sonra Ayarlar → Görünüm → Dil bölümünden istediğiniz zaman değiştirebilirsiniz.",
    "Apply language": "Dili uygula",
    "Translation in beta": "Beta çeviri",
    "This language is in beta. Please report any mistranslations or unclear phrasing to hello@getdemora.app.": "Bu çeviri beta aşamasındadır. Lütfen hatalı çevirileri veya anlaşılmayan ifadeleri hello@getdemora.app adresine bildirin.",
    "Dismiss": "Kapat",
    "Recheck blocked limits": "Engellenen sınırları yeniden kontrol et",
    "Takes around 30 seconds": "Yaklaşık 30 saniye sürer",
    "Recheck keeps current blocks in place while iOS verifies today's usage. Limits iOS confirms stay blocked.": "Yeniden kontrol sırasında iOS bugünkü kullanımı doğrularken mevcut engeller korunur. iOS’un doğruladığı sınırlar engelli kalır.",
    "Limit recheck": "Sınırları yeniden kontrol etme",
    "Released %d stale limit blocks. %d limits were freshly confirmed by iOS.": "%d eski sınır engeli kaldırıldı. iOS %d sınırı yeniden doğruladı.",
    "iOS freshly confirmed all current limit blocks.": "iOS mevcut tüm sınır engellerini yeniden doğruladı.",
    "No blocked limits need to be rechecked.": "Yeniden kontrol edilmesi gereken engellenmiş bir sınır yok.",
    "Wait until the active free period ends, then recheck again.": "Etkin serbest dönem bitince yeniden kontrol edin.",
    "You can recheck again in %@.": "%@ sonra yeniden kontrol edebilirsiniz.",
    "The recheck was interrupted. No blocks were changed.": "Yeniden kontrol kesintiye uğradı. Hiçbir engel değiştirilmedi.",
    "iOS couldn't complete the verification safely. No blocks were changed. Try again later.": "iOS doğrulamayı güvenli şekilde tamamlayamadı. Hiçbir engel değiştirilmedi. Daha sonra tekrar deneyin.",
    "Safe limit rechecking requires iOS 17.4 or later. No blocks were changed.": "Güvenli sınır kontrolü iOS 17.4 veya daha yeni bir sürüm gerektirir. Hiçbir engel değiştirilmedi.",
    "This is a demo — nothing you do here is saved or actually blocked.": "Bu bir demo — burada yaptığınız hiçbir şey kaydedilmez veya gerçekten engellenmez.",
    "Limitations": "Sınırlamalar",
    "iOS reporting notes": "iOS raporlama notları",
    "Today's usage reporting": "Bugünkü kullanım raporlaması",
    "Daily counting on older iOS": "Daha eski iOS'ta günlük sayma",
    "%@ #%d of every month": "Her ayın %@ #%d'si",
    "%d / %d min": "%d / %d dk",
    "blocked until midnight": "gece yarısına kadar engellendi",
    "now & next": "şimdi ve sonraki",
    "Today's usage": "Bugünkü kullanım",
    "Manage": "yönetmek",
    "Week starts": "Hafta başlar",
    "Monday": "pazartesi",
    "Sunday": "pazar",
    "Calendar": "takvim",
    "week / month": "hafta / ay",
    "month": "ay",
    "Solve math problems to skip a countdown.": "Bir sayım geriye doğru yapısını atlamak için matematik problemleri çözün.",
    "Enter a password to skip a countdown.": "Bir sayım geriye bakışını atlamak için bir şifre girin.",
    "How schedules work": "Programlar nasıl çalışır",
    "Help": "Yardım",
    "guide, contact, more": "rehber, iletişim, daha fazlası",
    "thank you": "teşekkür ederim",
    "Guide": "Rehber",
    "Contact": "İletişim",
    "About": "Hakkında",
    "how each part works": "her parça nasıl çalışır",
    "bug, feature, help": "hata, özellik, yardım",
    "links": "bağlantılar",
    "Report a bug": "Bir hata bildirin",
    "Request a feature": "Bir özellik isteyin",
    "General help": "Genel yardım",
    "Website": "örün sitesi",
    "Instagram": "Instagram",
    "What Demora is": "Demora nedir",
    "Demora protects your screen-time rules with a delay instead of a password. Every change you make waits out a countdown before it takes effect, so you can always change your mind — just not instantly, in a moment of weakness. Blocking itself is enforced by iOS through Screen Time.": "Demora, ekran kullanım süresi kurallarınızı bir şifre yerine gecikmeyle korur. Yaptığınız her değişiklik, etkili olmadan önce bir sayım geriye doğru işlemi bekler, böylece her zaman fikrinizi değiştirebilirsiniz — ancak anında, bir zayıflık anında değil. Engelleme işlemi kendisi, iOS tarafından Ekran Kullanımı üzerinden uygulanır.",
    "There are two delays. The more-strict delay gates changes that tighten your rules (adding a limit, lowering minutes, adding a schedule). The less-strict delay gates changes that loosen them (raising a limit, removing a block, adding a free period) — usually set longer. Pending changes show on the Home tab with a live countdown and can be cancelled before they apply.": "İki gecikme vardır. Kurallarınızı sıkılaştıran (sınırlama ekleyen, dakikaları düşüren, program ekleyen) daha katı gecikme kapısı değişiklikleri vardır. Onları gevşetiren (sınırlama artıran, bir engeli kaldıran, ücretsiz bir dönem ekleyen) daha gevşek gecikme kapısı değişiklikleri ise genellikle daha uzun sürelerle ayarlanır. Bekleyen değişiklikler, Canlı sayım ile birlikte Ana sayfa sekmesinde görüntülenir ve uygulanmadan önce iptal edilebilir.",
    "A limit is a daily time budget for the apps or categories you choose. When the minutes run out, those apps are blocked until midnight. The Limits tab shows today's usage per limit, and tapping a limit shows exactly which apps it covers.": "Bir sınır, seçtiğiniz uygulamalar veya kategoriler için günlük bir zaman bütçesidir. Dakikalar bittiğinde, bu uygulamalar gece yarısına kadar engellenir. Sınırlar sekmesi, her sınır için bugünkü kullanımını gösterir ve bir sınırı dokunmak, tam olarak hangi uygulamaları kapsadığını gösterir.",
    "Schedules block apps on a repeating or one-off basis. Recurring schedules repeat daily, on chosen weekdays, or monthly. Planned windows are one-offs for specific dates. Sessions are immediate timed blocks or unblocks. Free periods are windows where limits don't block and usage doesn't count.": "Programlar uygulamaları tekrarlayan veya tek seferlik olarak engeller. Tekrarlayan programlar, seçilen hafta içi günlerinde veya aylık olarak günlük olarak tekrarlanır. Planlanmış pencereler belirli tarihler için tek seferliktir. Oturumlar anında zamanlanmış bloklar veya engellenmeyen zaman dilimleridir. Ücretsiz dönemler, sınırlamaların engellemediği ve kullanımın sayılmadığı zaman dilimleridir.",
    "A trusted contact can approve skipping a countdown — by email code or from their own Demora app. People you add must accept before they can approve, and you can revoke them at any time.": "Güvenilir bir iletişim kişisi, sayım gerisini atlamayı — e-posta koduyla veya kendi Demora uygulamasından — onaylayabilir. Onaylayabilmeden önce eklediğiniz kişiler kabul etmeli ve bunları istediğiniz zaman iptal edebilirsiniz.",
    "App deletion lock": "Uygulama silme kilidi",
    "the core idea": "temel fikir",
    "the two countdowns": "iki sayım geriye doğru",
    "daily app budgets": "günlük uygulama bütçeleri",
    "recurring, planned, sessions": "tekrarlayan, planlı, oturumlar",
    "escape hatches": "kaçış kapıları",
    "approval by a person": "bir kişinin onayı",
    "can't uninstall to bypass": "atlatmak için kaldırılamıyor",
    "Most screen-time apps lock your rules behind a password. Because you know the password, you can undo your own rules the moment you feel the urge — so they rarely stick.\n\nDemora protects your rules with time instead. Every change waits out a countdown you set in advance before it takes effect. You stay in full control of your rules, but you can't change them in a single impulsive moment. The blocking itself is enforced by iOS through Screen Time — the same system parental controls use — so it can't be quietly bypassed.": "Çoğu ekran zamanı uygulaması kurallarınızı bir şifre arkasına kilitlemektedir. Şifreyi bildiğiniz için, dürtüyü hissettiğiniz anda kendi kurallarınızı geri alabilirsiniz — bu yüzden nadiren kalıcı hale gelirler.\n\nDemora ise kurallarınızı zamanla korur. Her değişiklik, etkili olmadan önce önceden ayarladığınız bir sayım geriye doğru işlemi bekler. Kurallarınızın tam kontrolünde kalırsınız, ancak bunları tek bir dürtüsel anda değiştiremezsiniz. Engelleme işlemi kendisi, iOS'un ebeveyn kontrollerinin kullandığı aynı sistem olan Ekran Süresi aracılığıyla uygulanır; bu nedenle sessizce atlatılamaz.",
    "Demora has two delays. The more-strict delay covers any change that tightens your rules: adding a limit, lowering its minutes, adding a schedule, or turning on the deletion lock. The less-strict delay covers changes that loosen them: raising a limit, removing a block, adding a free period, or disabling an override. The less-strict delay is usually set longer, since loosening is where temptation lives.\n\nA change doesn't apply right away — it becomes a pending change with a live countdown on the Home tab. You can cancel it any time before it lands, and when the countdown reaches zero it applies on its own, even if the app is closed.": "Demora'nın iki gecikmesi vardır. Daha katı gecikme, kurallarınızı sıkılaştıran herhangi bir değişikliği kapsar: bir sınır eklemek, dakikalarını düşürmek, bir program eklemek veya silme kilidini etkinleştirmek. Daha gevşek gecikme, bunları gevşetmekteki değişiklikleri kapsar: bir sınırı yükseltmek, bir engeli kaldırmak, ücretsiz bir dönem eklemek veya bir geçersiz kılma özelliğini devre dışı bırakmak. Daha gevşek gecikme genellikle daha uzun ayarlanır, çünkü cazibe tam da gevşeme noktalarında yaşar.\n\nBir değişiklik hemen uygulanmaz — Ana sayfa sekmesinde canlı bir sayım geriye doğru gösteren bekleyen bir değişiklik haline gelir. Uygulama yüklenmeden önce istediğiniz zaman iptal edebilirsiniz ve sayım geriye doğru sıfıra ulaştığında, uygulama kapalı olsa bile otomatik olarak uygulanır.",
    "A limit is a daily time budget for a set of apps or whole categories. When the minutes run out, those apps are blocked for the rest of the day and unlock again at midnight.\n\nThe Limits tab shows today's real usage for each limit, read straight from Screen Time, and tapping a limit reveals exactly which apps and categories it covers. Because usage is measured by iOS, time spent before you created the limit still counts toward it that day. Raising or removing a limit is a less-strict change; adding one or lowering its minutes is stricter.": "Bir sınır, belirli bir uygulama seti veya tüm kategoriler için günlük bir zaman bütçesidir. Dakikalar bittiğinde, bu uygulamalar günün geri kalanında engellenir ve gece yarısı tekrar kilidini açılır.\n\nSınırlar sekmesi, her sınır için bugünkü gerçek kullanımını Ekran Süresi'nden doğrudan gösterir ve bir sınırı dokunmak, tam olarak hangi uygulamaları ve kategorileri kapsadığını ortaya çıkarır. Kullanım iOS tarafından ölçüldüğü için, sınırı oluşturmadan önce harcadığınız zaman yine o gün için sayılır. Bir sınırı yükseltmek veya kaldırmak daha az katı bir değişikliktir; bir tane eklemek veya dakikalarını düşürmek daha katıdır.",
    "Schedules block apps by time rather than by budget, in a few shapes. Recurring schedules repeat — every day, on chosen weekdays, or on a monthly pattern. Planned windows are one-offs for a specific date, like a trip or an exam. Sessions are immediate, timed blocks or unblocks you start right now. Free periods are windows where limits don't block and usage doesn't count toward them.\n\nEach blocking schedule either blocks the apps you pick, or blocks everything except the apps you pick. When rules overlap, the most specific one wins: a session beats a planned window, which beats a recurring schedule, and within the same kind the one added most recently takes priority.": "Programlar, bütçe yerine zaman bazında uygulamaları birkaç farklı şekilde engeller. Tekrarlayan programlar tekrarlanır — her gün, seçilen hafta içi günlerinde veya aylık bir desenle. Planlanmış pencereler, bir gezi veya sınav gibi belirli bir tarih için tek seferliklerdir. Oturumlar, hemen başlattığınız anlık, zamanlandırılmış bloklar veya engellenmeyen zaman dilimleridir. Ücretsiz dönemler, sınırlamaların engellemediği ve kullanımın bunlara dahil edilmediği zaman dilimleridir.\n\nHer engelleme programı ya seçtiğiniz uygulamaları engeller ya da seçtiğiniz uygulamalar hariç her şeyi engeller. Kurallar örtüşürse, en spesifik olan kazanır: bir oturum planlanan bir pencereyi, bir tekrarlayan programı yenir ve aynı tür içinde en son eklenen en üst önceliği alır.",
    "Overrides are optional escape hatches that let you skip a pending change's countdown. There are three: solve a set of math problems, enter a password, or ask a trusted contact to approve. They're all off by default, so out of the box your delays are absolute.\n\nTurning an override on, or making it easier, counts as a less-strict change and waits out that delay. Turning one off, or making it harder, is stricter — so you can't instantly weaken your own safety net.": "Yenileme atlamaları, bekleyen bir değişikliğin sayımını atlamanı sağlayan isteğe bağlı kaçış kapılarındır. Üç tanesi vardır: bir dizi matematik sorusunu çözmek, bir şifre girmek veya güvenilir bir kişiden onay istemek. Hepsi varsayılan olarak kapalıdır, bu nedenle kutudan çıkışta gecikmeleriniz mutlakdır.\n\nBir geçici ayarlamayı etkinleştirmek veya onu kolaylaştırmak, daha az katı bir değişiklik olarak sayılır ve bu gecikmeyi bekler. Birini devre dışı bırakmak veya onu zorlaştırmak daha katıdır — bu nedenle kendi güvenlik ağınızı anında zayıflatamazsınız.",
    "A trusted contact is a person who can approve skipping a countdown for you. They can approve by entering a short code sent to their email, or directly from their own copy of Demora.\n\nAnyone you add has to accept the request before they can approve anything, so no one is involved without their knowledge. You can revoke a contact at any time, and they can step down on their side too. Adding the override is a less-strict change; removing it is stricter.": "Güvenilir bir iletişim kişisi, sizin için sayım geriye çekilmesini atlamayı onaylayabilen bir kişidir. E-postalarına gönderilen kısa bir kod girerek veya Demora'nın kendi kopyalarından doğrudan onaylayabilirler.\n\nEklediğiniz herkes, herhangi bir şeyi onaylayabilmeden önce talebi kabul etmelidir, bu nedenle kimse onların bilgisi olmadan dahil edilmez. Bir kişiyi istediğiniz zaman iptal edebilir ve onlar da kendi tarafından geri çekilebilirler. Devre dışı bırakmayı eklemek daha az katı bir değişikliktir; çıkarmak daha katıdır.",
    "When the deletion lock is on, deleting any app from this iPhone is blocked — including Demora itself. That closes the most obvious loophole: uninstalling the app to wipe your rules.\n\nBecause turning the lock off makes things easier to bypass, it counts as a less-strict change and waits out that delay before it takes effect.": "Silme kilidi açık olduğunda, bu iPhone'dan herhangi bir uygulamayı silmek engellenir — Demora'yı da dahil olmak üzere. Bu, kurallarınızı silebilirken uygulamayı kaldırmanın en bariz boşluğu kapatır.\n\nKiliti kapatmak şeyleri atlatmayı kolaylaştırdığı için, bu daha az katı bir değişiklik olarak sayılır ve etkili olmadan önce bu gecikmeyi bekler.",
    "When on, deleting any app from this iPhone is blocked — including Demora itself — so your rules can't be bypassed by uninstalling. Turning it off goes through the less-strict delay.": "Açıldığında, bu iPhone'dan herhangi bir uygulamayı silmek engellenir — Demora'yı da dahil olmak üzere — böylece kurallarınızı yüklemeyi kaldırmanızla aşamıyorsunuz. Kapattığınızda daha az katı gecikme süreci geçerlidir.",
    "Blocks": "Bloklar",
    "New recurring": "Yeni tekrarlayan",
    "Week": "hafta",
    "Month": "ay",
    "Nothing on this day.": "Bu gün hiçbir şey yok.",
    "When things overlap": "Şeyler örtüştüğünde",
    "One-off, right now: block or unblock chosen apps for a set number of minutes. Still delay-gated to start; ending early flips the rule.": "Tek seferlik, şu anda: seçilen uygulamaları belirli bir süre boyunca engelle veya engelleyin. Başlamak için hâlâ gecikmeli bir kısıtlama var; erken bitirmek kuralı değiştirir.",
    "One-off windows for specific dates — a trip, an exam. Block, allow-all-except, or a free period. Doesn't repeat.": "Belirli tarihler için tek seferlik pencereler — bir gezi, bir sınav. Bloğu, tümü hariç izin verme veya ücretsiz bir dönem. Tekrarlanmaz.",
    "Windows that repeat — daily, by weekday, or monthly. Each is either a block or a free period.": "Tekrarlayan pencereler — günlük, hafta içi veya aylık olarak. Her biri ya bir blok ya da serbest bir dönemdir.",
    "Limits don't block during the window, and time used inside it doesn't count against your daily budgets.": "Sınırlamalar pencere içinde engellenmez ve içinde kullanılan süre günlük bütçelerinize sayılmaz.",
    "Priority: a session beats a planned window, which beats a recurring schedule. Within the same kind, the one you added most recently wins.": "Öncelik: bir oturum planlanan bir pencereyi, bu da tekrarlayan bir programı yenir. Aynı tür içinde, en son eklediğiniz olan kazanır.",
    "today %@–%@": "bugün %@–%@",
    "Current passcode": "Mevcut şifre",
    "New passcode": "Yeni şifre",
    "Confirm new passcode": "Yeni şifreyi onayla",
    "Change passcode": "Şifreyi değiştirin",
    "Change passcode now": "Şimdi şifreyi değiştirin",
    "Enter your current passcode to change it instantly. Forgot it? Reset below — that one waits out your delay.": "Şifrenizi anında değiştirmek için mevcut şifrenizi girin. Unuttunuz mu? Aşağıdan sıfırlayın — bu, gecikmenizi bekler.",
    "Forgot it?": "Unuttun mu?",
    "Reset passcode (forgot)": "Şifreyi sıfırla (unuttum)",
    "Turn off password override": "Şifre üst yazma özelliğini kapatın",
    "Wrong passcode.": "Yanlış şifre.",
    "Select": "seçmek",
    "Cancel %d": "İptal %d",
    "Apply %d now": "Şimdi %d uygulayın",
    "%d changes": "%d değişiklik",
    "Denied": "Reddedildi",
    "My info": "Bilgilerim",
    "view": "görüş",
    "Nobody yet": "Henüz kimse yok",
    "language, theme, case": "dil, tema, durum",
    "%@ · %@": "%@ · %@",
    "none on": "hiçbiri yok",
    "%d on": "%d üzerinde",
    "Nothing scheduled right now.": "Şu anda planlanmış hiçbir şey yok.",
    "Active now": "Şimdi aktif",
    "Coming up": "Yaklaşıyor",
    "until %@": "%@'ye kadar",
    "today at %@": "bugün %@'da",
    "Planned": "Planlanmış",
    "Recurring": "Tekrarlanan",
    "none": "hiçbiri",
    "No active sessions": "Etkin oturum yok",
    "%d · %d active": "%d · %d aktif",
    "%d total": "%d toplam",
    "Your name": "Adın",
    "Your name (optional)": "Adınız (isteğe bağlı)",
    "Shown to people you ask to approve, so they know it's you.": "Onaylamanızı istediğiniz insanlara gösterilir, böylece bunun siz olduğunuzu bilirler.",
    "People you approve for": "Onayladığınız insanlar",
    "These people have you as a trusted contact. Removing yourself tells them and stops their requests.": "Bu insanlar seni güvenilir bir iletişim noktası olarak görüyor. Kendini kaldırmak onlara haber verir ve isteklerini durdurur.",
    "Remove": "kaldırmak",
    "code %@": "kod %@",
    "Demora user %@": "Demora kullanıcısı %@",
    "%@ removed their permission to be your trusted contact.": "%@, güvenilir iletişim kaynağınız olma iznini kaldırdı.",
    "Trusted contact removed": "Güvenilir iletişim kişi kaldırıldı",
    "A trusted contact": "Güvenilir bir iletişim",
    "That's your own code — add someone else.": "Bu senin kendi kodun — başka birini ekle.",
    "You already have this person as a contact.": "Bu kişiyi zaten bir iletişim kişiniz olarak bulunduruyorsunuz.",
    "Request history": "Talep geçmişi",
    "Blocked users": "Bloklanan kullanıcılar",
    "No requests yet.": "Henüz istek yok.",
    "No blocked users.": "Bloklanmış kullanıcı yok.",
    "Blocked": "Bloklandı",
    "Accepted": "Kabul edildi",
    "Declined": "Reddedildi",
    "Requested": "Talep edildi",
    "Accept": "kabul etmek",
    "Decline": "düşüş",
    "Active": "aktif",
    "Pending": "Bekleniyor",
    "Contact requests": "İletişim istekleri",
    "Pending — hasn't accepted yet": "Bekleniyor — henüz kabul etmedi",
    "Waiting for them to accept in their Demora app.": "Onların Demora uygulamasında kabul etmesini bekliyoruz.",
    "A trusted contact can let you skip a pending change's countdown — by emailing you a one-time code, or, if they use Demora, by approving from their own app.": "Güvenilir bir iletişim kurucu, bekleyen bir değişikliğin sayımını atlaymanıza olanak tanıyabilir - size tek kullanımlık bir kod göndererek veya Demora kullanıyorsa kendi uygulamalarından onay vererek.",
    "Share this code so another Demora user can add you. You get a request to accept before it's active.": "Bu kodu paylaşın, böylece başka bir Demora kullanıcısı sizi ekleyebilir. Aktif olmadan önce kabul etme isteği alırsınız.",
    "A Demora user (code %@) wants to add you as their trusted contact.": "Bir Demora kullanıcısı (%@) kodunu kullanarak sizi güvenilir iletişim kurma noktası olarak eklemek istiyor.",
    "%@ (code %@) wants to add you as their trusted contact.": "%@ (kod %@) sizi güvenilir iletişim kişileri olarak eklemek istiyor.",
    "If you accept, they can ask you to approve skipping their delays.": "Eğer kabul ederseniz, gecikmelerini atlamanıza onaylamanızı isteyebilirler.",
    "Email contacts work as soon as you add them. Demora-user contacts must accept first. Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "E-posta iletişimleri eklediğiniz anda çalışır. Demora kullanıcıları iletişimlerini önce kabul etmelidir. Bir iletişim eklemek daha az katı bir değişikliktir; birini kaldırmak daha katıdır — ikisi de gecikmeler yaşar.",
    "Ask them for the code in their Demora settings. They'll get a request to accept before they can approve for you.": "Onlardan Demora ayarlarındaki kodu isteyin. Sizin için onaylayabilmeden önce kabul etme talebi alacaklar.",
    "change": "değiştirmek",
    "Text case": "Büyük/küçük harf",
    "lowercase": "küçük harf",
    "Regular": "düzenli",
    "6-digit code": "6 haneli kod",
    "Add contact": "İletişim ekle",
    "Add contact…": "İletişim ekle…",
    "Add trusted contact: %@": "Güvenilir bir iletişim kurucu ekle: %@",
    "Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Bir iletişim kurucu eklemek daha az katı bir değişikliktir; birini kaldırmak daha katıdır — ikisi de gecikmeler yaşar.",
    "Any one approval unlocks the change.": "Herhangi bir onay değişikliği açar.",
    "Approval requests": "Onay talepleri",
    "Approve": "onaylamak",
    "Ask a contact": "Bir kişiye sorun",
    "Ask a trusted contact": "Güvenilir bir kişiden sorun",
    "Ask them for the code shown in their Demora settings.": "Demora ayarlarlarında gösterilen kodu onlardan isteyin.",
    "Checking…": "Kontrol Ediliyor…",
    "Checks automatically every few seconds. The request expires after 1 hour.": "Her birkaç saniyede bir otomatik olarak kontrol eder. Talep 1 saat sonra sona erer.",
    "Contacts": "Kişiler",
    "approvers, blocked": "onaylayıcılar, engellendi",
    "Couldn't send the request — check your connection and try again.": "İsteği gönderemedim — bağlantınızı kontrol edin ve tekrar deneyin.",
    "Too many requests to this contact right now. Try again later.": "Şu anda bu kişiye çok fazla istek var. Daha sonra tekrar deneyin.",
    "You've used all of today's approval emails. Try again tomorrow.": "Bugünün tüm onay e-postalarını kullandınız. Yarın tekrar deneyin.",
    "General blocking": "Genel engelleme",
    "deletion, websites": "silme, web siteleri",
    "Block adult websites": "Yetişkin web sitelerini engelle",
    "Allow adult websites": "Yetişkin web sitelerini izin verin",
    "Uses Apple's built-in filter to limit adult websites in Safari and other apps.": "Safari ve diğer uygulamalarda yetişkin web sitelerini sınırlamak için Apple'ın yerleşik filtresini kullanır.",
    "Website blocker": "Web sitesi engelleci",
    "Block website: %@": "Web sitesini engelle: %@",
    "Unblock website: %@": "Web sitesini engelleme: %@",
    "e.g. reddit.com": "örneğin reddit.com",
    "Queue: remove": "Sıra: kaldır",
    "Block specific websites by typing their domain — no need for Apple's site picker, which often comes up empty. Note: blocking sites also turns on Apple's adult-content filter. Adding a site is gated by your delays; removing one waits the longer delay.": "Belirli web sitelerini alan adlarını yazarak engelleyin — genellikle boş çıkan Apple'ın site seçicisine gerek yok. Not: siteleri engellemek aynı zamanda Apple'ın yetişkin içerik filtresini de etkinleştirir. Bir site eklemek gecikmelerinizle sınırlıdır; birini kaldırmak daha uzun gecikmeyi bekler.",
    "Blocked all day": "Gün boyu engellendi",
    "Adult websites": "Yetişkin web siteleri",
    "%d sites": "%d site",
    "Blocked sites": "Bloklanan siteler",
    "Stop apps from being deleted, limit adult websites, or block specific sites by domain. Every change here goes through your delays.": "Uygulamaların silinmesini önleyin, yetişkin web sitelerini sınırlayın veya alan adı bazında belirli siteleri engelleyin. Buradaki her değişiklik gecikmelerinizden geçer.",
    "0 minutes — this app stays blocked all day, every day.": "0 dakika — bu uygulama bütün gün, her gün engellenir.",
    "Approval emails are at capacity right now. Try again later, or use a Demora contact.": "Onay e-postaları şu anda kapasitesinin üzerinde. Daha sonra tekrar deneyin veya bir Demora temsilcisini kullanın.",
    "You've sent today": "Bugün gönderdin",
    "All users · today": "Tüm kullanıcılar · bugün",
    "All users · this month": "Tüm kullanıcılar · bu ay",
    "Email approvals": "E-posta onayılar",
    "Email contacts have a daily send limit; Demora-user contacts don't.": "E-posta iletişimlerinin günlük gönderim limiti vardır; Demora kullanıcılarının iletişimlerinin yoktur.",
    "one-time, forever": "tek seferlik, sonsuza dek",
    "active": "aktif",
    "Deny": "yadsımak",
    "Disable trusted-contact override": "Güvenilir iletişimci üst yazılımı devre dışı bırak",
    "Email": "E-posta",
    "Email address": "E-posta adresi",
    "Email code": "E-posta kodu",
    "Email contacts aren't available yet in this build.": "Bu sürümde e-posta iletişimleri henüz mevcut değil.",
    "Enable trusted-contact override": "Güvenilir iletişimci üst yazılımı etkinleştirin",
    "Friends who use Demora can add you as their trusted contact with this code.": "Demora kullanan arkadaşlar bu kodla sizi güvenilir iletişim kuracakları kişi olarak ekleyebilirler.",
    "Demora user": "Demora kullanıcısı",
    "My code": "Kodum",
    "No Demora user found with that code.": "O kodla No Demora kullanıcısı bulunamadı.",
    "No contacts yet": "Henüz iletişim bilgisi yok",
    "Remove trusted contact: %@": "Güvenilir iletişimi kaldırın: %@",
    "Send request": "Talep gönder",
    "Sending…": "Gönderiliyor…",
    "Someone set you as their trusted contact and wants to skip a waiting period.": "Birisi sizi güvenilir iletişim noktası olarak belirledi ve bekleme süresini atlamak istiyor.",
    "Their Demora code": "Onların Demora kodu",
    "Trusted contacts": "Güvenilir kişiler",
    "Trusted-contact override": "Güvenilir iletişim üst yazılımı",
    "Verify code": "Kod doğrulama",
    "Waiting for approval from their Demora app…": "Demora uygulamasından onay bekliyoruz…",
    "When enabled, a trusted contact can let you skip a pending change's countdown — by emailing you a code, or by approving from their own Demora app.": "Etkinleştirildiğinde, güvenilir bir iletişim kişisi, size bir kod göndererek veya kendi Demora uygulamalarından onay vererek bekleyen bir değişikliğin sayımını atlaymanıza izin verebilir.",
    "Who should approve?": "Kim onaylamalı?",
    "Wrong or expired code.": "Yanlış veya süresi dolmuş kod.",
    "Your contact received a code by email. Enter it here. It expires in 15 minutes.": "İletişim bilgilerinize e-posta ile bir kod gönderildi. Buraya girin. 15 dakika içinde geçerliliğini yitirecektir.",
    "contact": "temas",
    "e.g. Mom, Alex": "örneğin Anne, Alex",
    "%@ (%d problems)": "%@ (%d sorun)",
    "%@ session: %@ (%d min)": "%@ oturumu: %@ (%d dk)",
    "%@ — session starts in %@, then runs %d min": "%@ — oturum %@'da başlar, ardından %d dk çalışır",
    "%@ — takes effect in %@": "%@ — %@'da geçerli olur",
    "%d apps, %d categories": "%d uygulama, %d kategori",
    "%d hr": "%d saat",
    "%d min": "%d dk",
    "%d min/day": "%d dk/gün",
    "%d minutes": "%d dakika",
    "%d minutes/day": "%d dakika/gün",
    "%d of %d solved": "%d'si %d'den çözüldü",
    "%d selected": "%d seçildi",
    "ACTIVE": "aktif",
    "Add a daily time limit. It activates after your 'more strict' delay (%@).": "Günlük bir zaman sınırı ekleyin. 'daha katı' gecikmenizin (%@)' ardından etkinleşir.",
    "Add free period: %@ (%@)": "Ücretsiz dönem ekle: %@ (%@)",
    "Add free period…": "Ücretsiz dönem ekle…",
    "Add limit: %@ — %d min/day": "Sınırlama ekle: %@ — %d dk/gün",
    "Add me": "Beni ekle",
    "Add my name…": "Adımı ekle…",
    "Add schedule: %@ (%@ %@)": "Program ekle: %@ (%@ %@)",
    "Add schedule…": "Program ekle…",
    "Adding…": "Ekleniyor…",
    "Allow app deletion": "Uygulamanın silinmesine izin ver",
    "Answer": "cevap",
    "App deletion": "Uygulama silme",
    "Applies in": "Uygulanır",
    "Apply now": "Şimdi başvurun",
    "Apply now…": "Şimdi başvurun...",
    "Permissions": "İzniler",
    "Demora needs Screen Time access to set limits and block apps, and notifications to tell you when a pending change is ready. iOS will ask for each.": "Demora, sınırlamalar belirlemek ve uygulamaları engellemek için Ekran Süresi erişimine ve bekleyen bir değişiklik hazır olduğunda size bildirmek için bildirimlere ihtiyaç duyar. iOS her birini isteyecektir.",
    "Grant access": "Erişim sağlayın",
    "Welcome to Demora": "Demora'ya hoş geldiniz",
    "Demora can be a lot at first, so let's set up your first limit together — a quick, hands-on walkthrough of how delays and overrides actually feel. It takes about a minute.": "Demora — Önceden, ilk limitinizi bir araya koyalım.",
    "Add my first limit": "İlk sınırlamamı ekle",
    "Add your first limit": "İlk limitinizi ekleyin",
    "Add a recurring schedule": "Tekrarlayan bir program ekleyin",
    "Add a sample contact": "Örnek bir iletişim ekle",
    "Add a contact": "Bir iletişim ekle",
    "Adding a trusted contact normally waits out a delay. In this tutorial it's instant.": "Güvenilir bir iletişim kurucuyu eklemek genellikle bir gecikmeyi bekler. Bu eğitimde ise anında gerçekleşir.",
    "Alex (sample)": "Alex (örnek)",
    "Now a schedule. Tap ‘Add a recurring schedule’, pick a time window and some apps, then queue it.": "Şimdi bir program. 'Tekrarlayan bir program ekle'ye dokunun, bir zaman dilimi ve bazı uygulamalar seçin, ardından sıraya alın.",
    "Two changes are waiting, and you can't wait them out. Tap Select, choose both, Apply — then use the password override. The password is: test": "İki değişiklik bekliyor ve bunları bekleyemezsiniz. Seç seçeneğine dokunun, ikisini seçin, Uygula — ardından şifre üst yazımını kullanın. Şifre şudur: test",
    "Open Calendar to see everything laid out by day.": "Her şeyi gün bazında düzenlenmiş halde görmek için Takvimi açın.",
    "Now tidy up: remove the recurring schedule here, and the limit over in Limits.": "Şimdi düzenleyin: burada tekrarlayan programı kaldırın ve Limitler bölümündeki sınırı kaldırın.",
    "Now tidy up: open Recurring and remove the schedule you made.": "Şimdi düzenleyin: Tekrarlayanları açın ve yaptığınız programı kaldırın.",
    "And the limit: tap it, then Remove this limit.": "Ve sınır: ona dokunun, ardından Bu sınırı kaldırın.",
    "Let's add a backup approver. Open Rules → Overrides → Trusted contacts and add a sample contact.": "Bir yedek onaylayıcı ekleyelim. Kuralları Aç → Geçersizleştirme → Güvenilir iletişim kişilerini açın ve örnek bir iletişim kişisi ekleyin.",
    "all off": "hepsi kapalı",
    "Home delays": "Ev gecikmeleri",
    "Home overrides": "Ana sayfa üst yazıları",
    "shown": "gösterildi",
    "hidden": "gizli",
    "Rules": "Kurallar",
    "delays, overrides, blocking": "geri planlamalar, üst yazmalar, engelleme",
    "Current overrides": "Mevcut üst yazmalar",
    "No overrides on": "Devre dışı bırakma yok",
    "People who approve for you": "Seni onaylayan insanlar",
    "Demora code": "Demora kodu",
    "Code": "kod",
    "Name (optional)": "Ad (isteğe bağlı)",
    "Unnamed": "Adı olmayan",
    "Waiting for them to enter their code.": "Kodlarını girmelerini bekliyoruz.",
    "Added as a trusted contact": "Güvenilir bir iletişim olarak eklendi",
    "Add as trusted contact": "Güvenilir bir iletişim olarak ekle",
    "They'll get a request to accept before they can approve for you. Adding a contact goes through a delay.": "Sizin için onaylayabilmeden önce kabul etme talebi alacaklar. Bir iletişim eklemek bir gecikme yaşar.",
    "Removing yourself tells them and stops their requests.": "Kendinizi çıkarmak onlara söyler ve isteklerini durdurur.",
    "That's your own code.": "Bu senin kendi kodun.",
    "These people have you as a trusted contact. Tap one to see their details or add them back. Removing yourself tells them and stops their requests.": "Bu kişiler sizi güvenilir bir iletişim noktası olarak kullanıyor. Detaylarını görmek veya onları tekrar eklemek için birine dokunun. Kendinizi kaldırmak onlara haber verir ve isteklerini durdurur.",
    "Confirmed": "Onaylandı",
    "Send confirmation code": "Onay kodunu gönder",
    "Resend code": "Kodu yeniden gönder",
    "Confirm contact": "İletişimi onayla",
    "Confirm by email": "E-posta ile onaylayın",
    "We email a code to this address. Your contact gives you the code, you enter it here, and then they can approve for you. Until then they can't.": "Bu adrese bir kod e-posta ile gönderiyoruz. İletişim kişiniz size kodu verir, bunu buraya girersiniz ve ardından sizin için onaylayabilirler. O zamana kadar onaylayamazlar.",
    "Code sent. Ask your contact for it.": "Kod gönderildi. Bunun için iletişim kişinize sorun.",
    "Daily email limit reached. Try again later.": "Günlük e-posta limiti ulaşıldı. Daha sonra tekrar deneyin.",
    "You've sent too many codes today. Try again tomorrow.": "Bugün çok fazla kod gönderdiniz. Yarın tekrar deneyin.",
    "Couldn't send the code. Check your connection and try again.": "Kodu gönderemedim. Bağlantınızı kontrol edin ve tekrar deneyin.",
    "That code didn't match. Double-check and try again.": "Bu kod eşleşmedi. Tekrar kontrol edin ve tekrar deneyin.",
    "Both email and Demora-user contacts must confirm before they can approve: email contacts enter a code you email them, Demora users accept in their app. Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "E-posta ve Demora kullanıcıları arasındaki iletişimlerin onaylanabilmesi için her ikisi de onaylamalıdır: e-posta iletişimleri, e-posta ile gönderdiğiniz bir kod girer, Demora kullanıcıları ise uygulamalarında kabul eder. Bir iletişim eklemek daha az katı bir değişikliktir; birini kaldırmak ise daha katıdır; her ikisi de gecikmelerle karşılaşır.",
    "Elementary": "temel",
    "Middle school": "Ortaokul",
    "High school": "Lise",
    "Very easy": "Çok kolay",
    "Your change is ready": "Değişikliğiniz hazır",
    "Your limits have reset": "Sınırlarınız sıfırlandı",
    "If any apps still look blocked, open Demora to refresh them.": "Herhangi bir uygulama hala engellenmiş görünüyor ise, onları yenilemek için Demora'yı açın.",
    "If you denied access, turn on Screen Time for Demora in Settings, then come back.": "Eğer erişimi reddettiyorsanız, Ayarlar'da Demora için Ekran Süresi'ni açın, ardından geri dönün.",
    "Open Settings": "Ayarları Aç",
    "Couldn't check the code — check your connection and try again.": "Kodu kontrol edemedim — bağlantınızı kontrol edin ve tekrar deneyin.",
    "Couldn't send your response — check your connection and try again.": "Yanıtınızı gönderemedim — bağlantınızı kontrol edin ve tekrar deneyin.",
    "Those changes are still counting down. Wait them out, or turn on an override in Settings → Rules → Overrides to skip the wait.": "Bu değişiklikler hâlâ sayım geri yapıyor. Bekleyin ya da beklemeyi atlamak için Ayarlar → Kurallar → Devre Dışı Tutmalar'da bir devir dışı tutma özelliğini etkinleştirin.",
    "Heads up": "Dikkat",
    "Feature roadmap": "Özellik yol haritası",
    "Software roadmap": "Yazılım yol haritası",
    "features & bugs": "özellikler ve hatalar",
    "links to Trello": "Trello bağlantıları",
    "Safety code": "Güvenlik kodu",
    "Mark as verified": "Doğrulanmış olarak işaretle",
    "Verified": "Doğrulanmış",
    "Security": "güvenlik",
    "Available once you've both added each other.": "İkiniz de birbirinizi eklediğinizde kullanılabilir.",
    "Compare this code with your contact in person or on a call. If it matches on both phones, no one has tampered with the connection.": "Bu kodu kişisel olarak veya bir görüşmede iletişim kurduğunuz kişiyle karşılaştırın. Her iki telefonda da eşleşiyorsa, bağlantıya kimse müdahale etmemiş demektir.",
    "Background blocking may be incomplete": "Arka plan engelleme eksik olabilir",
    "iOS limits how many limits and schedules can run in the background at once. Removing a few restores full enforcement.": "iOS, arka planda aynı anda kaç limitin ve programın çalışabileceğini sınırlar. Birkaç tanesini kaldırmak tam uygulama sağlamasını sağlar.",
    "College": "kolej",
    "Nothing — just a new problem": "Hiçbir şey — sadece yeni bir sorun",
    "Lose one correct answer": "Bir doğru cevabı kaybedin",
    "Restart from zero": "Sıfırdan yeniden başlat",
    "Problems to solve": "Çözülmesi gereken sorunlar",
    "If an answer is wrong": "Bir cevap yanlışsa",
    "Enable math override (%@, %d problems)": "Matematik üst yazışmasını etkinleştir (%@, %d sorun)",
    "Solve for x:  %dx + %d = %d": "x için çözün: %dx + %d = %d",
    "Solve for x:  (x − %d) × %d = %d": "x için çözün: (x − %d) × %d = %d",
    "Solve for x:  %dx + %d = %dx + %d": "x için çözün: %dx + %d = %dx + %d",
    "Solve for x:  %d(x + %d) = %d": "x için çözün: %d(x + %d) = %d",
    "Wrong — here's a new problem.": "Yanlış — işte yeni bir sorun.",
    "Wrong — you lost one correct answer.": "Yanlış — bir doğru cevabı kaçırdınız.",
    "Wrong — starting over.": "Yanlış — yeniden başlıyorum.",
    "Avatar": "Avatar",
    "Icon": "ikon",
    "Photo": "fotoğraf",
    "Type one emoji": "Bir emoji girin",
    "Choose a photo": "Bir fotoğraf seçin",
    "Change photo": "Fotoğrafı değiştir",
    "Remove photo": "Fotoğrafı kaldır",
    "Demora %@": "Demora %@",
    "Blocked user": "Bloklanan kullanıcı",
    "Two removals are pending. Tap Select, choose both, Apply — then approve with your trusted contact instead of the password.": "İki kaldırma bekliyor. Seç seçeneğine dokunun, ikisini seçin, Uygula — ardından şifre yerine güvenilir iletişim kişinizle onaylayın.",
    "This time, use your trusted contact — it'll be approved for you.": "Bu sefer, güvenebileceğiniz kişiyi kullanın - sizin için onaylanacaktır.",
    "Send a request to Alex (sample). A real contact approves from their own Demora app or with an emailed code.": "Alex'e bir istek gönderin (örnek). Gerçek bir iletişim, kendi Demora uygulamasından veya e-posta ile gönderilen bir kodla onaylar.",
    "Waiting for approval…": "Onay bekliyorum…",
    "%d changes: %@": "%d değişiklik: %@",
    "Requested change": "Talep edilen değişiklik",
    "Requested changes": "Talep edilen değişiklikler",
    "Awaiting approval": "Onay bekliyor",
    "Tap to enter the email code": "E-posta kodunu girmek için dokunun",
    "Encrypted request — re-add this contact to read it.": "Şifreli istek — bunu okumak için bu kişiyi tekrar ekleyin.",
    "Privacy Policy": "Gizlilik Politikası",
    "Terms of Use": "Kullanım Koşulları",
    "Approved!": "Onaylandı!",
    "Almost done": "Neredeyse bitti",
    "Nice work — that's the whole loop. Now set the delays and overrides that will actually protect you.": "İyi iş çıkardın — işte tüm döngü bu. Şimdi seni gerçekten koruyacak gecikmeleri ve geçersiz kılma ayarlarını ayarla.",
    "Finish setup": "Kurulumu tamamla",
    "Tap ‘Add your first limit’, choose an app or two and a daily budget, then queue the change.": "'İlk limitinizi ekleyin'e dokunun, bir veya iki uygulama ve günlük bir bütçe seçin, ardından değişikliği sıraya alın.",
    "Your change is waiting out its delay — and you can't wait this one out. Tap ‘Apply now…’ and use the password override. The password is: test": "Değişikliğiniz gecikmesini bekliyor — ve bunu bekleyemezsiniz. ‘Şimdi Uygula…’ tuşuna dokunun ve şifre geçişini kullanın. Şifre şudur: test",
    "Now remove it: tap the limit, then ‘Remove this limit’.": "Şimdi kaldırın: sınırı dokunun, ardından 'Bu sınırı kaldır' seçeneğine dokunun.",
    "Same again — tap ‘Apply now…’ and enter the password (test).": "Tekrar aynı şey — 'Şimdi Uygula...'a dokunun ve şifreyi girin (test).",
    "For this tutorial, only the password works. The password is: test": "Bu eğitim için sadece şifre çalışır. Şifre şudur: test",
    "For the tutorial, the password is: test": "Eğitim için şifre: test",
    "Everything here is just a sample — nothing is saved and nothing is actually blocked. It's only to show how the app works.": "Buradaki her şey sadece bir örnek — hiçbir şey kaydedilmiyor ve hiçbir şey gerçekten engellenmiyor. Bu, uygulamanın nasıl çalıştığını göstermek içindir.",
    "Applying…": "Başvuruluyor…",
    "Apps": "Uygulamalar",
    "Apps that stay usable": "Kullanılabilir kalan uygulamalar",
    "Apps to block": "Bloklamak için uygulamalar",
    "Nothing selected": "Hiçbir şey seçilmedi",
    "Apps blocked": "Uygulamalar engellendi",
    "Apps unblocked": "Uygulamalar engellenmedi",
    "Blocking the selected apps": "Seçilen uygulamaları engelleme",
    "Unblocking the selected apps": "Seçilen uygulamaları engellemeyi kaldırmak",
    "Apps to unblock": "Blokajı kaldırmak için uygulamalar",
    "Authorize": "yetki vermek",
    "Authorized ✓": "Yetkilendirilmiş ✓",
    "Back": "geri",
    "Beta testers": "Beta testçileri",
    "Block": "Engelle",
    "Block all except…": "Aşağıdakileri hariç tümünü engelle…",
    "Block app deletion": "Uygulama silme engelleme",
    "Block apps": "Uygulamaları engelle",
    "Block only…": "Sadece engelle…",
    "Blocked by Demora": "Demora tarafından engellendi",
    "Blocking is enforced by iOS itself through Screen Time, the same system parental controls use.": "Blokaj, iOS tarafından, aynı sistem ebeveyn kontrollerinin kullandığı Ekran Süresi aracılığıyla uygulanır.",
    "Cancel": "iptal etmek",
    "Change %@ to %d min/day": "%@'yı %d dk/gün olarak değiştirin",
    "Changes that make things LESS STRICT (raise a limit, remove a block, add a free period) wait out your second delay — usually set longer.": "Şeyleri DAHA AZ SIKITLEYEN değişiklikler (bir sınırı yükseltmek, bir engeli kaldırmak, ücretsiz bir dönem eklemek) ikinci gecikmenizi bekler — genellikle daha uzun ayarlanır.",
    "Changes that make things STRICTER (add a limit, lower minutes, add a schedule) wait out your first delay.": "Her şeyi DAHA SIKI hale getiren değişiklikler (sınırlama ekleyin, dakikaları azaltın, bir program ekleyin) ilk gecikmenizi bekleyin.",
    "Changes you make will appear here with a countdown.": "Yaptığınız değişiklikler burada sayım geri çevirmesi ile görünecektir.",
    "Choose apps": "Uygulamaları seçin",
    "Close": "yakın",
    "Confirm password": "Şifreyi onayla",
    "Continue": "Devam et",
    "Couldn't load names (check iCloud/network).": "Adları yükleyemedim (iCloud/ağ kontrol edin).",
    "Couldn't submit — make sure you're signed into iCloud and try again.": "Göndereyemedim — iCloud'a giriş yaptığınızdan emin olun ve tekrar deneyin.",
    "Current delays": "Mevcut gecikmeler",
    "Current: %@": "Mevcut: %@",
    "Daily limit": "Günlük sınır",
    "Day %d of every month": "Her ayın %d. günü",
    "Day of month": "Ayın günü",
    "Delay": "Gecikme",
    "Delay for LOOSER changes": "LOOSER değişiklikleri için gecikme",
    "Delay for STRICTER changes": "DAHA SIKI değişiklikler için gecikme",
    "Delays": "Gecikmeler",
    "Difficulty": "zorluk",
    "Disable math override": "Matematik üst yazısını devre dışı bırak",
    "Disable password override": "Şifre üst yazma özelliğini devre dış",
    "Done": "Tamamlandı",
    "Duration": "süre",
    "During a free period, limits don't block and usage inside the window doesn't count toward them — time used before the window still does.": "Ücretsiz bir dönemde sınırlamalar engellemez ve pencerenin içinde yapılan kullanım bunlara sayılmaz — pencerenin öncesinde kullanılan zaman yine de sayılır.",
    "Easy": "kolay",
    "Enable math override": "Matematik üst yazışmasını etkinleştir",
    "Enable math override (%@)": "Matematik üst yazışmasını etkinleştir (%@)",
    "Enable password override": "Şifre geçişini etkinleştir",
    "Enable/update password override": "Şifre geçersiz kılma özelliğini etkinleştir/güncelle",
    "End": "son",
    "End early…": "Erken bitir…",
    "End session early: %@": "Oturumu erken bitirin: %@",
    "Ends": "Sonlar",
    "Enter password": "Şifreyi girin",
    "Every change you make waits out a delay you chose, counting down in the background. You can always change your rules — just not in a moment of weakness.": "Yaptığınız her değişiklik, seçtiğiniz bir gecikmeyi bekler ve arka planda sayım yapar. Kurallarınızı her zaman değiştirebilirsiniz — sadece bir zayıflık anında değil.",
    "Every day": "Her gün",
    "Everything on the iPhone is blocked during the window except the apps picked here.": "iPhone'daki her şey, burada seçilen uygulamalar hariç pencere sırasında engellenir.",
    "Free period": "Serbest dönem",
    "Today's usage is reported by iOS Screen Time, which can be slow to load or briefly show nothing. If it looks empty, tap the refresh arrow a couple of times.": "Bugünkü kullanım, iOS Ekran Süresi tarafından raporlanmaktadır; bu uygulama yüklenirken yavaşlayabilir veya kısa bir süre hiçbir şey göstermeyebilir. Boş görünüyorsa, yenileme okusuna birkaç kez dokunun.",
    "Free": "Serbest",
    "Free period: %@ (%d min)": "Ücretsiz dönem: %@ (%d dk)",
    "Free period — nothing is blocked": "Ücretsiz dönem — hiçbir şey engellenmiyor",
    "Temporarily lifts everything — no app blocks apply, and usage during the free period doesn't count toward your limits.": "Her şeyi geçici olarak kaldırır — herhangi bir uygulama engeli uygulanmaz ve ücretsiz dönemde kullanım sınırlamanızın sayılmasına dahil değildir.",
    "Free periods": "Ücretsiz dönemler",
    "Friction, not passwords": "Frekans, şifreler değil",
    "Get started": "Başlayın",
    "Hard": "zor",
    "Home": "Ana Sayfa",
    "Hours": "Saatler",
    "How does it work?": "Nasıl çalışır?",
    "Incorrect password": "Yanlış şifre",
    "Keep it appropriate — names are reviewed, and inappropriate ones won't be added.": "Uygun tutun — isimler incelenir ve uygunsuz olanlar eklenmeyecektir.",
    "Language": "Dil",
    "Demora needs Screen Time authorization to set app limits and block apps. iOS will ask for your confirmation.": "Demora, uygulama sınırlamaları belirlemek ve uygulamaları engellemek için Ekran Süresi yetkilendirmesine ihtiyaç duyar. iOS onayınızı isteyecektir.",
    "Demora wouldn't exist without the people who tested it, broke it, and told me about it. Thank you. ❤️": "Demora, onu test eden, kıran ve bana anlatan insanlar olmadan var olmazdı. Teşekkür ederim. ❤️",
    "Less strict": "Daha az katı",
    "Less-strict delay": "Daha az katı gecikme",
    "Limit": "sınır",
    "Limits": "Süre sınırları",
    "Limits won't block and usage won't count during this window.": "Bu pencere boyunca sınırlamalar engellenmeyecek ve kullanım sayılmayacak.",
    "Limits: daily time budgets per app. When the minutes run out, the app is blocked until midnight.": "Sınırlamalar: uygulama başına günlük zaman bütçeleri. Dakikalar bittiğinde, uygulama gece yarısına kadar engellenir.",
    "Looser changes": "Düşük değişiklikler",
    "Looser changes wait %@": "Kaybeden değişiklikler bekliyor %@",
    "Math override": "Matematik üst yazılımı",
    "Math problems": "Matematik problemleri",
    "Medium": "orta",
    "Minutes": "tutanaklar",
    "Mode": "moda",
    "Monthly schedules can't cross midnight — set the end time after the start time.": "Aylık programlar gece yarısına geçemez — bitiş zamanını başlangıç zamanından sonra ayarlayın.",
    "More strict": "Daha katı",
    "More-strict delay": "Daha katı gecikme",
    "Most screen-time apps protect your rules with a password — which you know, so you cave. Demora protects them with time instead.": "Çoğu ekran süresi uygulaması kurallarınızı bir şifreyle korur — ki bunu biliyorsunuz, bu yüzden teslim oluyorsunuz. Demora ise onları zamanla korur.",
    "Name": "isim",
    "Names will appear here soon.": "İsimler yakında burada görünecek.",
    "New free period": "Yeni ücretsiz dönem",
    "New limit": "Yeni sınır",
    "New password": "Yeni şifre",
    "New schedule": "Yeni program",
    "New session": "Yeni oturum",
    "New session…": "Yeni oturum…",
    "No free periods": "Ücretsiz dönem yok",
    "No limits yet": "Henüz sınırlama yok",
    "No overrides — delays are absolute": "Devre dışı bırakma yok — gecikmeler mutlakdır",
    "No pending changes": "Bekleyen değişiklik yok",
    "No schedules": "Program yok",
    "No thanks": "Hayır teşekkürler",
    "Nothing planned": "Hiçbir şey planlanmadı",
    "Nth weekday": "N. iş günü",
    "OK": "iyi",
    "Off": "kapalı",
    "On": "açık",
    "One-off and unplanned, but still delay-gated. A block session waits %@; an unblock session waits %@. Ending early flips the rule (or use an override).": "Tek seferlik ve planlanmamış, ancak yine de gecikme kontrolüne tabi. Bir blok oturumu %@ bekliyor; kilidini açılmamış bir oturum %@ bekliyor. Erken bitirmek kuralı değiştirir (veya bir geçersiz kılma kullanın).",
    "Only the apps picked here are blocked during the window.": "Sadece burada seçilen uygulamalar pencere boyunca engellenir.",
    "Overrides": "İstisnalar",
    "Overrides enabled": "Yenileme etkinleştirildi",
    "Overrides let you skip a pending change's countdown. They're off by default. Adding one later counts as a less-strict change; removing one counts as stricter — both go through delays.": "Yenileme ayarları, bekleyen bir değişikliğin sayımını atlamanıza olanak tanır. Varsayılan olarak devre dışıdırlar. Daha sonra bir tanesini eklemek daha az katı bir değişiklik olarak sayılır; bir tanesini kaldırmak daha katı bir değişiklik olarak sayılır — ikisi de gecikmelerle karşılaşır.",
    "Overrides skip a pending change's countdown. Enabling or weakening one is a less-strict change; disabling or strengthening one is stricter. All edits here go through the matching delay.": "Bekleyen bir değişikliğin sayımını atlamayı değiştirir. Birini etkinleştirmek veya zayıflatmak daha az katı bir değişikliktir; birini devre dışı bırakmak veya güçlendirmek daha katıdır. Burada yapılan tüm düzenlemeler eşleşme gecikmesini geçirir.",
    "A change for this setting is already pending. Cancel it on the Home tab first if you want something different.": "Bu ayar için bir değişiklik zaten bekliyor. Farklı bir şey istiyorsanız önce Ana sayfa sekmesinden iptal edin.",
    "Already pending": "Zaten bekliyor",
    "A person you choose approves skipping a countdown — by email code or from their own Demora app. You can also add more later in Settings → Trusted contacts.": "Seçtiğiniz bir kişi, sayım geriye doğru yapmayı atlamayı onaylar — e-posta koduyla veya kendi Demora uygulamasından. Daha sonra Ayarlar → Güvenilir iletişimler bölümünde daha fazlasını da ekleyebilirsiniz.",
    "Add": "Ekle",
    "Message (optional)": "Mesaj (isteğe bağlı)",
    "Sent along with the request so they know why you're asking.": "Neden sorduğunuzu bilmeleri için talebinizle birlikte gönderildi.",
    "e.g. why you need this": "örneğin bunun neden ihtiyacınız var",
    "%@ — Note: %@": "%@ — Not: %@",
    "Your request was denied.": "Talebiniz reddedildi.",
    "Send a new request…": "Yeni bir istek gönderin…",
    "Cancels this request and lets you pick contacts again.": "Bu talebi iptal eder ve tekrar iletişim kurucuları seçmenize izin verir.",
    "Coming soon": "Yakında geliyor",
    "Appearance": "Görünüm",
    "Theme": "Tema",
    "System": "sistem",
    "Light": "ışık",
    "Dark": "karanlık",
    "/ de·mo·ra /  noun, Spanish": "/ de·mo·ra / isim, İspanyolca",
    "a delay; the time that passes before something takes effect.": "bir gecikme; bir şeyin etkili olmasından önce geçen zaman.",
    "an iPhone app that protects your screen-time rules with definition 1 instead of a password.": "şifre yerine 1 tanesiyle ekran kullanım kurallarınızı koruyan bir iPhone uygulaması.",
    "Coming soon — payments aren't available yet.": "Yakında geliyor — ödemeler henüz mevcut değil.",
    "Password": "parola",
    "Password override": "Şifre üst yazımı",
    "Passwords don't match": "Şifreler eşleşmiyor",
    "Pay %@": "Pay %@",
    "Pay %@ to apply this change now": "Bu değişikliği şimdi uygulamak için %@ ödeyin",
    "Pending change": "Bekleyen değişiklik",
    "Pending changes": "Bekleyen değişiklikler",
    "Pending changes show on the Home tab with a live countdown. You can cancel them anytime before they apply.": "Bekleyen değişiklikler, Canlı bir sayım geriye doğru gösteren Ana sayfa sekmesinde gösterilir. Uygulanmadan önce istediğiniz zaman iptal edebilirsiniz.",
    "Plan %@: %@ (%@)": "Plan %@: %@ (%@)",
    "Plan a window": "Bir pencere planlayın",
    "Plan a window…": "Bir pencere planlayın…",
    "Plan ahead for specific dates — a trip, a weekend, an exam. Doesn't repeat. Planning a block is stricter; planning a free period is less strict.": "Belirli tarihler için önceden plan yapın — bir gezi, bir hafta sonu, bir sınav. Tekrarlanmaz. Bir blok planlamak daha katıdır; boş bir dönem planlamak daha az katıdır.",
    "Planned (one-off)": "Planlanmış (tek seferlik)",
    "Planned window": "Planlanan pencere",
    "Purchasing…": "Satın Alma…",
    "Queue change": "Sıra değişikliği",
    "Queue: turn off": "Sıra: kapat",
    "Queue: turn on": "Sıra: aç",
    "Recurring schedules": "Tekrarlayan programlar",
    "Remove free period: %@": "Ücretsiz dönemi kaldırın: %@",
    "Remove limit: %@": "Sınırlamayı kaldır: %@",
    "Remove planned window: %@": "Planlanan pencereyi kaldırın: %@",
    "Remove schedule: %@": "Programı kaldır: %@",
    "Remove this limit": "Bu sınırı kaldırın",
    "Remove…": "Silin…",
    "Repeating windows: every day, chosen weekdays, or monthly patterns. Adding waits %@; removing waits %@.": "Tekrarlayan pencereler: her gün, seçilen hafta içi günler veya aylık kalıplar. Bekleme süreleri ekleme %@; bekleme süreleri kaldırma %@.",
    "Repeats": "Tekrarlar",
    "Schedule": "program",
    "Schedules": "Programlar",
    "Schedules: recurring or one-off windows that block chosen apps — or everything except a chosen few. Plus free periods where time doesn't count.": "Programlar: seçilen uygulamaları — ya da seçilen birkaçını hariç her şeyi engelleyen tekrarlayan veya tek seferlik zaman dilimleri. Ayrıca zamanın önemli olmadığı ücretsiz dönemler.",
    "Screen Time access": "Ekran Süresi erişimi",
    "Sessions": "Oturumlar",
    "Set 'less strict' delay to %@": "'Daha az katı' gecikmeyi %@ olarak ayarlayın",
    "Set 'more strict' delay to %@": "'daha katı' gecikmeyi %@ olarak ayarlayın",
    "Settings": "Ayarlar",
    "Setup": "Kurulum",
    "Simulate payment (beta)": "Ödemeyi simüle et (beta)",
    "Skip the wait": "Beklemeyi atla",
    "Solve %d math problems (%@)": "%d matematik sorusunu çözün (%@)",
    "Solve math problems": "Matematik problemlerini çözün",
    "Start": "başlamak",
    "Start using Demora": "Demora'yı kullanmaya başlayın",
    "Starts": "Başlar",
    "Stricter changes": "Daha katı değişiklikler",
    "Stricter changes wait %@": "Daha katı değişiklikler %@ bekliyor",
    "Submit": "teslim olmak",
    "Temporarily lifts limits, schedules, and block sessions for the chosen apps.": "Seçilen uygulamalar için sınırlamaları, programları ve engellenen oturumları geçici olarak kaldırır.",
    "Thanks for testing Demora!": "Demora'yı denediğiniz için teşekkürler!",
    "This app is blocked right now — by a limit, a schedule, or a session. Changing your rules takes a delay; open Demora to queue a change.": "Bu uygulama şu anda engellendi — bir sınırlama, bir program veya bir oturum tarafından. Kurallarınızı değiştirmek zaman alır; bir değişikliği sıraya koymak için Demora'yı açın.",
    "If it should already be unblocked, iOS is sometimes slow to apply a background change — open Demora for an immediate unblock.": "Eğer zaten engellenmemiş olmalıysa, iOS bazen arka plan değişikliğini uygulamada yavaş olabilir - anında engelleme kaldırmak için Demora'yı açın.",
    "Two delays rule everything": "İki gecikme her şeyi yönetiyor",
    "Type": "tip",
    "Unblock": "Engeli kaldır",
    "Unblock apps": "Uygulamaları engelleme",
    "Unlock": "açmak",
    "Wait this long before any change that loosens your rules takes effect. Usually set longer than the first.": "Kurallarınızı gevşetici herhangi bir değişiklik yürürlüğe girmeden bu kadar uzun bekleyin. Genellikle ilkinden daha uzun ayarlanır.",
    "Wait this long before any change that tightens your rules takes effect.": "Kurallarınızı sıkılaştıran herhangi bir değişiklik yürürlüğe girmeden bu kadar uzun bekleyin.",
    "Want your name in the app's beta-tester thanks page? Pick whatever you'd like to be called.": "Uygulamanın beta testçi teşekkür sayfasında adınızı görmek ister misiniz? Nasıl adlandırılmak istediğinizi seçin.",
    "Weekday": "hafta içi",
    "Weekdays": "Hafta içi günler",
    "What can it do?": "Ne yapabilir?",
    "What's in the box": "Kutuda ne var",
    "When": "ne zaman",
    "When on, deleting ANY app from this iPhone is blocked — including Demora itself, so blocks can't be bypassed by uninstalling.": "Açıldığında, bu iPhone'dan HERHANGİBİR uygulamayı silmek engellenir - Demora'yı da dahil olmak üzere, bu nedenle engeller, yüklemeyi kaldırmaktan atlanamaz.",
    "Which one": "Hangi",
    "Window": "pencere",
    "Wrong — new problem": "Yanlış — yeni sorun",
    "You're in! Your name will appear in the beta testers page once it's approved.": "Katıldınız! Adınız onaylandığında beta testçiler sayfasında görünecektir.",
    "You're set": "Hazırsın",
    "Your name is in — it'll show up once approved.": "Adınız dahil — onaylandığında görünecek.",
    "Your name or nickname": "Adınız veya takma adınız",
    "e.g. Airport, weekend trip": "örneğin Havalimanı, hafta sonu gezisi",
    "e.g. Bedtime": "örneğin. Yatma zamanı",
    "e.g. Deep work": "örneğin Derin çalışma",
    "e.g. Instagram": "örneğin Instagram",
    "e.g. Lunch break": "örneğin. Öğle molası",
    "free period": "ücretsiz dönem",
    "limit": "sınır",
    "now": "şimdi",
    "planned window": "planlanan pencere",
    "schedule": "program",
    "session": "oturum",
    "A passcode is saved. Open the guide below to view it.": "Bir şifre kodu kaydedildi. Görüntülemek için aşağıdaki kılavuzu açın.",
    "Access requested. It unlocks after your less-strict delay — track it on the Home tab, where you can also use an override to skip the wait.": "Erişim talep edildi. Daha az katı gecikmenizin ardından kilidi açılır — Beklemeyi atlamak için ayrıca bir geçersiz kılma kullanabileceğiniz Ana sayfa sekmesinde takip edebilirsiniz.",
    "Can't reach this contact right now — they may have removed Demora or signed out. They won't be able to approve until they're back.": "Şu anda bu kişiye ulaşamıyorum — Demora'yı kaldırmış olabilirler veya oturumdan çıkmış olabilirler. Geri dönene kadar onaylayamayacaklar.",
    "Couldn't start the walkthrough": "Turlar başlamadı",
    "Bug tracker": "Hata takipçisi",
    "Demora can't stop you from turning off its Screen Time access in iOS Settings — but a friend can. If Screen Time itself is locked with someone else's passcode, iOS blocks any change to Demora's access, while Demora keeps doing all the blocking.": "Demora, iOS Ayarlarındaki Ekran Süresi erişimini kapatmanızı engelleyemez — ancak bir arkadaş engelleyebilir. Ekran Süresi kendisi başka birinin şifresiyle kilitleilmişse, iOS Demora'nın erişimindeki herhangi bir değişikliği engellerken, Demora tüm engellemeleri yapmaya devam eder.",
    "Demora couldn't safely back up your current setup, so the replay was cancelled to protect your limits. Nothing was changed. Please try again in a moment.": "Demora, mevcut kurulumunuzu güvenli bir şekilde yedekleyemedi, bu nedenle sınırlamanızı korumak için tekrar oynatma iptal edildi. Hiçbir şey değiştirilmedi. Lütfen bir dakikanızda tekrar deneyin.",
    "Done. Now you can't disable Demora's access — or change the passcode — without your friend. To undo it later, your friend enters the passcode and turns it off.": "Tamamlandı. Artık arkadaşınız olmadan Demora'nın erişimini devre dışı bırakamazsınız — ya da şifreyi değiştiremezsiniz —. Daha sonra bunu geri almak için arkadaşınız şifreyi girer ve devre dışı bırakır.",
    "Email limit": "E-posta limiti",
    "Emoji": "Emoji",
    "Friend: save the passcode here so it isn't lost. It's only shown from this page, which is behind your delay.": "Arkadaş: şifreyi kaybetmemesi için buraya kaydedin. Sadece bu sayfadan gösterilir, bu da gecikmenizin arkasındadır.",
    "Hand your phone to your friend. Have THEM enter a 4-digit passcode you don't see — don't watch.": "Telefonunuzu arkadaşınıza verin. ONLAR'dan görmediğiniz 4 haneli bir şifreyi girmelerini isteyin — izlemeyin.",
    "Heads up: on your iOS version, a limit only counts screen time from the moment you add it — time you already spent earlier today isn't included. Update to iOS 17.4 or later for exact daily counting.": "Dikkat: iOS sürümünüzde, bir sınır yalnızca eklediğiniz andan itibaren ekran süresini sayar — bugün daha önce harcadığınız süre dahil değildir. Kesin günlük sayım için iOS 17.4 veya üzeri sürümüne güncelleyin.",
    "Make Demora impossible to disable": "Demora'yı devre dışı bırakmayı imkansız hale getir",
    "Onboarding demo — you can skip below. It's always available again in Settings → Help.": "Başlangıç demo'su — aşağıya atlayabilirsiniz. Bu, Ayarlar → Yardım'da her zaman tekrar mevcuttur.",
    "One more safeguard": "Bir daha bir koruma",
    "Open Settings → Screen Time on this iPhone. If it's off, turn it on.": "Bu iPhone'da Ayarlar → Ekran Süresi'ni açın. Eğer kapalıysa, açın.",
    "Open the guide": "Kılavuzu açın",
    "Opening this is delayed on purpose — so you can't impulsively look up how to undo your own lock.": "Bunu açmak kasıtlı olarak geciktirilmiştir — böylece kendi kilidinizi nasıl iptal edeceğinizi dürtüsel olarak arayamazsınız.",
    "Passcode": "Şifre",
    "Pick someone you trust and can reach. If the passcode and its recovery Apple ID are both lost, removing it may require erasing the device.": "Güvenebileceğiniz ve ulaşabileceğiniz birini seçin. Şifre ve kurtarma Apple Kimliği her ikisi de kaybolursa, onu kaldırmak cihazı silebilir hale getirmeyi gerektirebilir.",
    "Prevent disabling": "Devre dışı bırakılmasını önleyin",
    "Protection": "koruma",
    "Replay walkthrough": "Tekrar oynatma rehberi",
    "Request access": "Erişim iste",
    "Save": "korumak",
    "Saved passcode: %@": "Kaydedilen şifre: %@",
    "Unlock viewing the stored passcode": "Kaydedilen şifreyi görüntüleme kilidini açın",
    "how to lock it with a friend": "bir arkadaşla nasıl kilitleyeceksin",
    "Screen Time passcode": "Ekran Süresi şifresi",
    "none saved": "hiçbir şey kaydedilmedi",
    "saved": "kaydedildi",
    "Enter passcode": "Şifreyi girin",
    "save it here so it isn't lost": "kaybolmasın diye buraya kaydedin",
    "replaces the saved one": "Kaydedilenini değiştirir",
    "behind your delay": "geçmişinizin arkasındaki",
    "View passcode": "Şifre kodunu görüntüle",
    "Change the passcode?": "Şifreyi mi değiştirmek istiyorsunuz?",
    "Are you sure? There is no way to undo this — the saved passcode is replaced only when you save a new one.": "Emin misiniz? Bunu geri almak için bir yol yok — kaydedilen şifre yalnızca yeni bir şifre kaydettiğinizde değiştirilir.",
    "The friend who set the Screen Time passcode can store it here so it isn't lost. Going back without saving keeps the current one.": "Ekran Süresi şifresini ayarlayan arkadaş, kaybolmaması için bunu burada saklayabilir. Kaydetmeden geri dönmek mevcut olanı korur.",
    "Viewing the stored passcode is behind your less-strict delay: request it, wait out the delay, and you get one look. After that it locks again.": "Kaydedilen şifreyi görüntülemek, daha az katı gecikmenizin arkasındadır: isteyin, gecikmeyi bekleyin ve bir kez bakabilirsiniz. Bundan sonra tekrar kilitlelenir.",
    "Access is spent — viewing it again needs a new request.": "Erişim tükendi - tekrar görüntülemek için yeni bir istek gerekiyor.",
    "Screen Time usually only allows a 4-digit passcode — are you sure this is correct?": "Ekran Süresi genellikle yalnızca 4 haneli bir şifreye izin verir — bunun doğru olduğundan emin misiniz?",
    "Saved ✓": "Kaydedildi ✓",
    "Show me how": "Bana nasıl göstere",
    "Skip and set up manually": "Atla ve manuel olarak ayarla",
    "Skip walkthrough": "İncelemeyi atla",
    "Skip — set up manually": "Atla — manuel olarak ayarla",
    "Store the Screen Time passcode": "Ekran Süresi şifresini kaydedin",
    "Take photo": "Fotoğraf çek",
    "Takes about 2 minutes, and you need a second person physically with you.": "Yaklaşık 2 dakika sürer ve yanınızda fiziksel olarak ikinci bir kişiye ihtiyacınız vardır.",
    "Tap “Lock Screen Time Settings” (or “Use Screen Time Passcode”).": "\"Ekran Süresi Ayarları'nı Kilitle\" (veya \"Ekran Süresi Şifresini Kullan\"ı) dokunun.",
    "Thank you. ❤️": "Teşekkür ederim. ❤️",
    "That's okay. Without Screen Time access Demora can't block apps, but you can continue and turn it on later.": "Sorun değil. Ekran Süresi erişimi olmadan Demora uygulamaları engellemez, ancak devam edebilir ve daha sonra etkinleştirebilirsiniz.",
    "That's the whole loop. Your real limits, schedules, and settings are still here — nothing changed.": "Tam da bu döngü. Gerçek sınırlamalarınız, programlarınız ve ayarlarınız hâlâ burada — hiçbir şey değişmedi.",
    "There's a way to make Demora impossible to turn off — with a friend's help. It takes about 2 minutes and needs a second person physically with you.": "Demora'yı kapatmayı imkansız hale getirmek için bir yol var — bir arkadaşın yardımıyla. Yaklaşık 2 dakika sürer ve yanınızda fiziksel olarak ikinci bir kişinin bulunması gerekir.",
    "They call themselves “%@”.": "Kendilerini \"%@\" diyorlar.",
    "This guide is behind your less-strict delay: request it, wait out the delay, and you get one open. After you view it, it locks again.": "Bu kılavuz, daha az katı gecikmenizin arkasındadır: isteyin, gecikmeyi bekleyin ve bir tane açık alırsınız. Görüntüledikten sonra tekrar kilitleşir.",
    "Unavailable": "Mevcut değil",
    "Unlock the “Prevent disabling” guide": "“Engelleme devre dışı bırakılmasını önle” kılavuzunu açın",
    "Use photo": "Fotoğrafı kullan",
    "When asked for Screen Time Passcode Recovery, your friend signs in with THEIR OWN Apple ID — not yours. That's what stops you from resetting the passcode on your own.": "Ekran Süresi Şifre Kurtarma isteği yapıldığında, arkadaşınız KENDİ Apple KimliĞİ ile giriş yapar — sizinkiyle değil. Bu, şifreyi kendi başınıza sıfırlamanızı engelleyen şeydir.",
    "You can always find this later under Help — but there it's behind a delay.": "Bunu her zaman daha sonra Yardım altında bulabilirsiniz - ancak orada bir gecikmenin arkasındadır.",
    "You can change these any time under General blocking. Each change then goes through your delays.": "Bunları Genel engelleme altında istediğiniz zaman değiştirebilirsiniz. Her değişiklik ardından gecikmelerinizden geçer.",
    "Your one-time access is ready.": "Tek seferlik erişiminiz hazır.",
    "lock it with a friend": "bir arkadaşla kilitle",
    "your setup stays safe": "kurulumunuz güvende kalır",
    "—": "—",
]
