//
//  Localization+Portuguese.swift
//  Full in-app localization table. Missing keys fall back to English.
//

import Foundation

let portugueseStrings: [String: String] = [
    "Dismiss": "Fechar",
    "Recheck blocked limits": "Verificar limites bloqueados novamente",
    "Takes around 30 seconds": "Leva cerca de 30 segundos",
    "Recheck keeps current blocks in place while iOS verifies today's usage. Limits iOS confirms stay blocked.": "A verificação mantém os bloqueios atuais enquanto o iOS confere o uso de hoje. Os limites confirmados pelo iOS continuam bloqueados.",
    "Limit recheck": "Verificação de limites",
    "Released %d stale limit blocks. %d limits were freshly confirmed by iOS.": "%d bloqueios de limite desatualizados foram removidos. O iOS confirmou novamente %d limites.",
    "iOS freshly confirmed all current limit blocks.": "O iOS confirmou novamente todos os bloqueios de limite atuais.",
    "No blocked limits need to be rechecked.": "Não há limites bloqueados que precisem ser verificados novamente.",
    "Wait until the active free period ends, then recheck again.": "Espere o período livre ativo terminar e tente novamente.",
    "You can recheck again in %@.": "Você poderá verificar novamente em %@.",
    "The recheck was interrupted. No blocks were changed.": "A verificação foi interrompida. Nenhum bloqueio foi alterado.",
    "iOS couldn't complete the verification safely. No blocks were changed. Try again later.": "O iOS não conseguiu concluir a verificação com segurança. Nenhum bloqueio foi alterado. Tente novamente mais tarde.",
    "Safe limit rechecking requires iOS 17.4 or later. No blocks were changed.": "A verificação segura de limites requer iOS 17.4 ou posterior. Nenhum bloqueio foi alterado.",
    "This is a demo — nothing you do here is saved or actually blocked.": "Esta é uma demonstração – nada que você faz aqui é salvo ou realmente bloqueado.",
    "Limitations": "Limitações",
    "iOS reporting notes": "Notas de relatórios do iOS",
    "Today's usage reporting": "Relatórios de uso de hoje",
    "Daily counting on older iOS": "Contando diariamente com iOS mais antigo",
    "%@ #%d of every month": "%@ #%d de cada mês",
    "%d / %d min": "%d / %d min",
    "blocked until midnight": "Bloqueado até meia-noite",
    "now & next": "& agora & seguinte",
    "Today's usage": "O uso de hoje",
    "Manage": "Gerenciar",
    "Week starts": "Semana começa",
    "Monday": "segunda-feira",
    "Sunday": "Domingo",
    "Calendar": "Calendário",
    "week / month": "semana / mês",
    "month": "mês",
    "Solve math problems to skip a countdown.": "Resolva problemas de matemática para pular uma contagem regressiva.",
    "Enter a password to skip a countdown.": "Insira uma senha para pular uma contagem regressiva.",
    "How schedules work": "Como funcionam os horários",
    "Help": "Ajuda",
    "guide, contact, more": "contato, mais",
    "thank you": "Obrigado",
    "Guide": "Guia",
    "Contact": "Contato",
    "About": "Sobre",
    "how each part works": "Como cada parte funciona",
    "bug, feature, help": "bug, recurso, ajuda",
    "links": "campo de golfe",
    "Report a bug": "Reportar um bug",
    "Request a feature": "Solicitar uma funcionalidade",
    "General help": "Ajuda geral",
    "Website": "E-mail",
    "Instagram": "Instagram",
    "What Demora is": "O que é Demora",
    "Demora protects your screen-time rules with a delay instead of a password. Every change you make waits out a countdown before it takes effect, so you can always change your mind — just not instantly, in a moment of weakness. Blocking itself is enforced by iOS through Screen Time.": "Demora protege as regras de tempo de tela com um atraso em vez de uma senha. Cada mudança que você faz aguarda uma contagem regressiva antes que ela entre em vigor, para que você possa sempre mudar de ideia apenas não instantaneamente, em um momento de fraqueza. O bloqueio em si é imposto pelo iOS através do Tempo de Tela.",
    "There are two delays. The more-strict delay gates changes that tighten your rules (adding a limit, lowering minutes, adding a schedule). The less-strict delay gates changes that loosen them (raising a limit, removing a block, adding a free period) — usually set longer. Pending changes show on the Home tab with a live countdown and can be cancelled before they apply.": "Há dois atrasos. As mudanças de portões de atraso mais restritas que apertam suas regras (adicionando um limite, diminuindo minutos, adicionando um cronograma). As mudanças de portões de atraso menos restritas que os soltam (aumentando um limite, removendo um bloco, adicionando um período livre) - geralmente são mais longas. As mudanças pendentes são exibidas na guia Início com uma contagem regressiva ao vivo e podem ser canceladas antes de se aplicarem.",
    "A limit is a daily time budget for the apps or categories you choose. When the minutes run out, those apps are blocked until midnight. The Limits tab shows today's usage per limit, and tapping a limit shows exactly which apps it covers.": "Um limite é um orçamento de tempo diário para os aplicativos ou categorias que você escolher. Quando os minutos se esgotam, esses aplicativos são bloqueados até a meia-noite. A guia Limites mostra o uso de hoje por limite e tocar em um limite mostra exatamente quais aplicativos ele cobre.",
    "Schedules block apps on a repeating or one-off basis. Recurring schedules repeat daily, on chosen weekdays, or monthly. Planned windows are one-offs for specific dates. Sessions are immediate timed blocks or unblocks. Free periods are windows where limits don't block and usage doesn't count.": "Os horários agendas bloqueiam aplicativos em uma base repetida ou única. Os horários recorrentes repetem diariamente, nos dias da semana escolhidos ou mensalmente. As janelas planejadas são pontuais para datas específicas. As sessões são blocos cronometrados ou desbloqueiam imediatamente. Os períodos livres são janelas onde os limites não bloqueiam e o uso não conta.",
    "A trusted contact can approve skipping a countdown — by email code or from their own Demora app. People you add must accept before they can approve, and you can revoke them at any time.": "Um contato confiável pode aprovar pular uma contagem regressiva por código de e-mail ou pelo aplicativo Demora. As pessoas que você adicionar devem aceitar antes que possam aprovar e você pode revogá-las a qualquer momento.",
    "App deletion lock": "Bloqueio de eliminação de App",
    "the core idea": "a ideia central",
    "the two countdowns": "As duas contagens regress",
    "daily app budgets": "Orçamentos diários de aplicativos",
    "recurring, planned, sessions": "Recorrentes, planejadas, sessões",
    "escape hatches": "escotilhas de escape",
    "approval by a person": "aprovação de uma pessoa",
    "can't uninstall to bypass": "não pode desinstalar para ignorar",
    "Most screen-time apps lock your rules behind a password. Because you know the password, you can undo your own rules the moment you feel the urge — so they rarely stick.\n\nDemora protects your rules with time instead. Every change waits out a countdown you set in advance before it takes effect. You stay in full control of your rules, but you can't change them in a single impulsive moment. The blocking itself is enforced by iOS through Screen Time — the same system parental controls use — so it can't be quietly bypassed.": "A maioria dos aplicativos de tempo de tela bloqueia suas regras por trás de uma senha. Como você conhece a senha, você pode desfazer suas próprias regras no momento em que sentir o impulso então eles raramente ficam. Demora protege suas regras com o tempo. Cada mudança aguarda uma contagem regressiva que você definiu antes de entrar em vigor. Você permanece no controle total de suas regras, mas não pode mudá-las em um único momento impulsivo. O bloqueio em si pode ser imposto pelo sistema de tela do iOS",
    "Demora has two delays. The more-strict delay covers any change that tightens your rules: adding a limit, lowering its minutes, adding a schedule, or turning on the deletion lock. The less-strict delay covers changes that loosen them: raising a limit, removing a block, adding a free period, or disabling an override. The less-strict delay is usually set longer, since loosening is where temptation lives.\n\nA change doesn't apply right away — it becomes a pending change with a live countdown on the Home tab. You can cancel it any time before it lands, and when the countdown reaches zero it applies on its own, even if the app is closed.": "Demora tem dois atrasos. O atraso mais restrito abrange qualquer alteração que aperta suas regras: adicionar um limite, reduzir seus minutos, adicionar um cronograma ou ligar o bloqueio de exclusão. O atraso menos rigoroso cobre as mudanças que os afrouxam: aumentar um limite, remover um bloco, adicionar um período livre ou desativar um cancelamento. O atraso menos estrito geralmente é definido por mais tempo, já que qualquer afrouxamento é onde a tentação vive. Uma mudança não se aplica antes.",
    "A limit is a daily time budget for a set of apps or whole categories. When the minutes run out, those apps are blocked for the rest of the day and unlock again at midnight.\n\nThe Limits tab shows today's real usage for each limit, read straight from Screen Time, and tapping a limit reveals exactly which apps and categories it covers. Because usage is measured by iOS, time spent before you created the limit still counts toward it that day. Raising or removing a limit is a less-strict change; adding one or lowering its minutes is stricter.": "Um limite é um orçamento de tempo diário para um conjunto de aplicativos ou categorias inteiras. Quando os minutos se esgotam, esses aplicativos são bloqueados pelo resto do dia e desbloqueiam novamente à meia-noite. A guia Limites mostra o uso real de hoje para cada limite, leia diretamente do Tempo de Tela e tocar em um limite revela exatamente quais aplicativos e categorias ele cobre. Porque o uso é medido pelo iOS, o tempo gasto antes de você criar o limite ainda conta para ele naquele dia. Aumentar ou remover um limite é adicionar menos;",
    "Schedules block apps by time rather than by budget, in a few shapes. Recurring schedules repeat — every day, on chosen weekdays, or on a monthly pattern. Planned windows are one-offs for a specific date, like a trip or an exam. Sessions are immediate, timed blocks or unblocks you start right now. Free periods are windows where limits don't block and usage doesn't count toward them.\n\nEach blocking schedule either blocks the apps you pick, or blocks everything except the apps you pick. When rules overlap, the most specific one wins: a session beats a planned window, which beats a recurring schedule, and within the same kind the one added most recently takes priority.": "Os horários de bloqueio de aplicativos por tempo e não por orçamento, em algumas formas. Os horários recorrentes se repetem todos os dias, nos dias da semana escolhidos ou em um padrão mensal. As janelas planejadas são pontuais para uma data específica, como uma viagem ou um exame. As sessões são blocos imediatos e cronometrados ou desbloqueia você começa agora. Períodos livres são janelas onde os limites não bloqueiam e o uso não conta para eles. Cada cronograma de bloqueio bloqueia os aplicativos, exceto",
    "Overrides are optional escape hatches that let you skip a pending change's countdown. There are three: solve a set of math problems, enter a password, or ask a trusted contact to approve. They're all off by default, so out of the box your delays are absolute.\n\nTurning an override on, or making it easier, counts as a less-strict change and waits out that delay. Turning one off, or making it harder, is stricter — so you can't instantly weaken your own safety net.": "As ultrapassagens são escotilhas de escape opcionais que permitem que você pule a contagem regressiva de uma mudança pendente. Existem três: resolver um conjunto de problemas matemáticos, inserir uma senha ou pedir um contato confiável para aprovar. Eles estão todos fora por padrão, então fora da caixa seus atrasos são absolutos. Ligar uma substituição ou torná-la mais fácil, conta como uma mudança menos restrita e aguarda esse atraso. Desligar um ou torná-lo mais difícil, pode enfraquecer instantaneamente mais rigoroso.",
    "A trusted contact is a person who can approve skipping a countdown for you. They can approve by entering a short code sent to their email, or directly from their own copy of Demora.\n\nAnyone you add has to accept the request before they can approve anything, so no one is involved without their knowledge. You can revoke a contact at any time, and they can step down on their side too. Adding the override is a less-strict change; removing it is stricter.": "Um contato confiável é uma pessoa que pode aprovar pular uma contagem regressiva para você. Eles podem aprovar inserindo um código curto enviado para seu e-mail ou diretamente de sua própria cópia do Demora. Qualquer pessoa que você adicionar tem que aceitar o pedido antes que eles possam aprovar qualquer coisa, para que ninguém esteja envolvido sem o conhecimento deles. Você pode revogar um contato a qualquer momento e eles podem renunciar ao seu lado também. Adicionar a substituição é uma mudança menos rigorosa; removê-lo é rigoroso.",
    "When the deletion lock is on, deleting any app from this iPhone is blocked — including Demora itself. That closes the most obvious loophole: uninstalling the app to wipe your rules.\n\nBecause turning the lock off makes things easier to bypass, it counts as a less-strict change and waits out that delay before it takes effect.": "Quando o bloqueio de exclusão está ligado, a exclusão de qualquer aplicativo deste iPhone é bloqueada incluindo o próprio Demora. Isso fecha a brecha mais óbvia: desinstalar o aplicativo para limpar suas regras. Porque desativar o bloqueio facilita o desvio, conta como uma mudança menos restrita e aguarda esse atraso antes que ele entre em vigor.",
    "When on, deleting any app from this iPhone is blocked — including Demora itself — so your rules can't be bypassed by uninstalling. Turning it off goes through the less-strict delay.": "Quando estiver ligado, a exclusão de qualquer aplicativo deste iPhone está bloqueada incluindo o próprio Demora para que suas regras não possam ser contornadas desinstalando. Desativar passa pelo atraso menos rigoroso.",
    "Blocks": "Blocos",
    "New recurring": "Novo recorrente",
    "Week": "Semana",
    "Month": "Mês",
    "Nothing on this day.": "Nada neste dia.",
    "When things overlap": "Quando as coisas se sobrepõem",
    "One-off, right now: block or unblock chosen apps for a set number of minutes. Still delay-gated to start; ending early flips the rule.": "Agora mesmo: bloquear ou desbloquear aplicativos escolhidos por um número definido de minutos. Ainda atrasado para começar; terminando cedo vira a regra.",
    "One-off windows for specific dates — a trip, an exam. Block, allow-all-except, or a free period. Doesn't repeat.": "Janelas únicas para datas específicas uma viagem, um exame. Bloquear, permitir-tudo-exceto, ou um período livre. Não se repete.",
    "Windows that repeat — daily, by weekday, or monthly. Each is either a block or a free period.": "Windows que repetem diariamente, por dia da semana, ou mensalmente. Cada um é um bloco ou um período livre.",
    "Limits don't block during the window, and time used inside it doesn't count against your daily budgets.": "Os limites não bloqueiam durante a janela, e o tempo usado dentro dela não conta contra seus orçamentos diários.",
    "Priority: a session beats a planned window, which beats a recurring schedule. Within the same kind, the one you added most recently wins.": "Prioridade: uma sessão bate uma janela planejada, que bate um cronograma recorrente. Dentro do mesmo tipo, o que você adicionou mais recentemente ganha.",
    "today %@–%@": "hoje %@–%@",
    "Current passcode": "Código de acesso atual",
    "New passcode": "Nova senha",
    "Confirm new passcode": "Confirme nova senha",
    "Change passcode": "Mudar código",
    "Change passcode now": "Mudar código agora",
    "Enter your current passcode to change it instantly. Forgot it? Reset below — that one waits out your delay.": "Digite seu código de acesso atual para alterá-lo instantaneamente. Esqueceu? Reset abaixo que espera o seu atraso.",
    "Forgot it?": "Esqueceu-se?",
    "Reset passcode (forgot)": "Reset passcode (esquecimento)",
    "Turn off password override": "Desativar a substituição da palavra-passe",
    "Wrong passcode.": "Código errado.",
    "Select": "Selecionar",
    "Cancel %d": "%d",
    "Apply %d now": "Aplicar %d agora",
    "%d changes": "%d alterações",
    "Denied": "Negado",
    "My info": "Minhas informações",
    "view": "ver",
    "Nobody yet": "Ninguém ainda",
    "language, theme, case": "linguagem, tema, caso",
    "%@ · %@": "%@  %@",
    "none on": "nenhum",
    "%d on": "%d em",
    "Nothing scheduled right now.": "Nada programado agora.",
    "Active now": "Ativo agora",
    "Coming up": "A chegar",
    "until %@": "até %@",
    "today at %@": "Hoje em %@",
    "Planned": "Planejado",
    "Recurring": "Recorrente",
    "none": "nenhum",
    "No active sessions": "Sem sessões ativas",
    "%d · %d active": "%d  %d ativo",
    "%d total": "total %d",
    "Your name": "Seu nome",
    "Your name (optional)": "Seu nome (opcional)",
    "Shown to people you ask to approve, so they know it's you.": "Mostrado para as pessoas que você pede para aprovar, para que eles saibam que é você.",
    "People you approve for": "Pessoas que você aprova para",
    "These people have you as a trusted contact. Removing yourself tells them and stops their requests.": "Essas pessoas têm você como um contato confiável. Remover-se diz a eles e pára seus pedidos.",
    "Remove": "Remover",
    "code %@": "código %@",
    "Demora user %@": "Demora utilizador %@",
    "%@ removed their permission to be your trusted contact.": "%@ removeu a permissão deles para ser seu contato confiável.",
    "Trusted contact removed": "Contato confiável removido",
    "A trusted contact": "Um contato confiável",
    "That's your own code — add someone else.": "Esse é o seu próprio código – adicione outra pessoa.",
    "You already have this person as a contact.": "Você já tem essa pessoa como contato.",
    "Request history": "Pedido de histórico",
    "Blocked users": "Usuários bloqueados",
    "No requests yet.": "Ainda não há pedidos.",
    "No blocked users.": "Não bloqueou usuários.",
    "Blocked": "Bloqueado",
    "Accepted": "Aceito",
    "Declined": "Reclinado",
    "Requested": "Solicitado",
    "Accept": "Aceitar",
    "Decline": "Declínio",
    "Active": "Ativo",
    "Pending": "Pendente",
    "Contact requests": "Pedidos de contacto",
    "Pending — hasn't accepted yet": "Pendente ainda não aceitou",
    "Waiting for them to accept in their Demora app.": "Esperando que eles aceitem em seu aplicativo \"Demora\".",
    "A trusted contact can let you skip a pending change's countdown — by emailing you a one-time code, or, if they use Demora, by approving from their own app.": "Um contato confiável pode permitir que você pule a contagem regressiva de uma mudança pendente enviando um código único por e-mail ou, se eles usarem o “Demora”, aprovando a partir de seu próprio aplicativo.",
    "Share this code so another Demora user can add you. You get a request to accept before it's active.": "Compartilhe este código para que outro usuário Demora possa adicioná-lo. Você recebe um pedido para aceitar antes que ele esteja ativo.",
    "A Demora user (code %@) wants to add you as their trusted contact.": "Um usuário \"Demora\" (código %@) quer adicioná-lo como seu contato confiável.",
    "%@ (code %@) wants to add you as their trusted contact.": "%@ (código %@) quer adicioná-lo como seu contato confiável.",
    "If you accept, they can ask you to approve skipping their delays.": "Se aceitar, eles podem pedir que você aprove pular os atrasos.",
    "Email contacts work as soon as you add them. Demora-user contacts must accept first. Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Os contatos de e-mail funcionam assim que você os adiciona. Os contatos do usuário do Demora devem aceitar primeiro. Adicionar um contato é uma mudança menos restrita; remover um é mais rigoroso - ambos passam por atrasos.",
    "Ask them for the code in their Demora settings. They'll get a request to accept before they can approve for you.": "Peça-lhes o código nas configurações de \"Demora\". Eles receberão um pedido para aceitar antes que possam aprovar para você.",
    "change": "mudar",
    "Text case": "Capitalização",
    "lowercase": "minúscula",
    "Regular": "regular",
    "6-digit code": "código de 6 dígitos",
    "Add contact": "Adicionar contato",
    "Add contact…": "Adicionar contato...",
    "Add trusted contact: %@": "Adicionar contato confiável: %@",
    "Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Adicionar um contato é uma mudança menos restrita; remover um é mais rigoroso – ambos passam por atrasos.",
    "Any one approval unlocks the change.": "Qualquer aprovação desbloqueia a mudança.",
    "Approval requests": "Pedidos de aprovação",
    "Approve": "Aprovar",
    "Ask a contact": "Pergunte a um contato",
    "Ask a trusted contact": "Pergunte a um contato confiável",
    "Ask them for the code shown in their Demora settings.": "Peça-lhes o código mostrado nas configurações de \"Demora\".",
    "Checking…": "Verificando...",
    "Checks automatically every few seconds. The request expires after 1 hour.": "Verifica automaticamente a cada poucos segundos. O pedido expira após 1 hora.",
    "Contacts": "Contatos",
    "approvers, blocked": "aprovadores, bloqueados",
    "Couldn't send the request — check your connection and try again.": "Não foi possível enviar o pedido – verifique sua conexão e tente novamente.",
    "Too many requests to this contact right now. Try again later.": "Muitos pedidos para este contato agora mesmo. Tente novamente mais tarde.",
    "You've used all of today's approval emails. Try again tomorrow.": "Você usou todos os e-mails de aprovação de hoje. Tente novamente amanhã.",
    "General blocking": "Bloqueio geral",
    "deletion, websites": "Apagamento, websites",
    "Block adult websites": "Bloquear sites adultos",
    "Allow adult websites": "Permitir websites adultos",
    "Uses Apple's built-in filter to limit adult websites in Safari and other apps.": "Usa o filtro integrado da Apple para limitar sites adultos no Safari e em outros aplicativos.",
    "Website blocker": "Bloqueador de Website",
    "Block website: %@": "Website: %@",
    "Unblock website: %@": "Desbloquear website: %@",
    "e.g. reddit.com": "por exemplo reddit.com",
    "Queue: remove": "Fila: remover",
    "Block specific websites by typing their domain — no need for Apple's site picker, which often comes up empty. Note: blocking sites also turns on Apple's adult-content filter. Adding a site is gated by your delays; removing one waits the longer delay.": "Bloqueie sites específicos digitando seu domínio não há necessidade do seletor de sites da Apple, que muitas vezes aparece vazio. Nota: sites de bloqueio também ativam o filtro de conteúdo adulto da Apple. Adicionar um site é bloqueado por seus atrasos; remover um espera o atraso mais longo.",
    "Blocked all day": "Bloqueado o dia todo",
    "Adult websites": "sites adultos",
    "%d sites": "Sites %d",
    "Blocked sites": "Sites bloqueados",
    "Stop apps from being deleted, limit adult websites, or block specific sites by domain. Every change here goes through your delays.": "Impedir que os aplicativos sejam excluídos, limitar sites adultos ou bloquear sites específicos por domínio. Cada mudança aqui passa por seus atrasos.",
    "0 minutes — this app stays blocked all day, every day.": "0 minutos – este aplicativo fica bloqueado o dia todo, todos os dias.",
    "Approval emails are at capacity right now. Try again later, or use a Demora contact.": "Os e-mails de aprovação estão disponíveis agora. Tente novamente mais tarde ou use um contato Demora.",
    "You've sent today": "Você enviou hoje",
    "All users · today": "Todos os usuários  hoje",
    "All users · this month": "Todos os usuários  este mês",
    "Email approvals": "aprovações por e-mail",
    "Email contacts have a daily send limit; Demora-user contacts don't.": "Os contatos de e-mail têm um limite de envio diário; os contatos de usuário do Demora não.",
    "one-time, forever": "Uma vez, para sempre",
    "active": "ativo",
    "Deny": "Negar",
    "Disable trusted-contact override": "Desabilitar a substituição de contacto fidedigável",
    "Email": "E-mail",
    "Email address": "Endereço de e-mail",
    "Email code": "Código de e-mail",
    "Email contacts aren't available yet in this build.": "Os contatos de e-mail ainda não estão disponíveis nesta compilação.",
    "Enable trusted-contact override": "Habilitar a substituição de contato confiável",
    "Friends who use Demora can add you as their trusted contact with this code.": "Os amigos que usam Demora podem adicioná-lo como seu contato confiável com este código.",
    "Demora user": "Demora utilizador",
    "My code": "Meu código",
    "No Demora user found with that code.": "Nenhum usuário \"Demora\" encontrado com esse código.",
    "No contacts yet": "Ainda não há contactos",
    "Remove trusted contact: %@": "Remover contacto de confiança: %@",
    "Send request": "Enviar pedido",
    "Sending…": "Enviando...",
    "Someone set you as their trusted contact and wants to skip a waiting period.": "Alguém o define como seu contato confiável e quer pular um período de espera.",
    "Their Demora code": "O código Demora",
    "Trusted contacts": "Contatos de confiança",
    "Trusted-contact override": "Sobreposição de contacto fidedigável",
    "Verify code": "Verificar código",
    "Waiting for approval from their Demora app…": "Aguardando a aprovação de seu aplicativo Demora...",
    "When enabled, a trusted contact can let you skip a pending change's countdown — by emailing you a code, or by approving from their own Demora app.": "Quando ativado, um contato confiável pode permitir que você pule a contagem regressiva de uma mudança pendente enviando um código por e-mail ou aprovando o aplicativo \"Demora\".",
    "Who should approve?": "Quem deve aprovar?",
    "Wrong or expired code.": "Código errado ou expirado.",
    "Your contact received a code by email. Enter it here. It expires in 15 minutes.": "O seu contacto recebeu um código por e-mail. Introduza-o aqui. Ele expira em 15 minutos.",
    "contact": "contato",
    "e.g. Mom, Alex": "Por exemplo, mãe, Alex",
    "%@ (%d problems)": "%@ (problemas do %d)",
    "%@ session: %@ (%d min)": "Sessão %@: %@ (%d min)",
    "%@ — session starts in %@, then runs %d min": "%@ sessão começa em %@, em seguida, executa %d min",
    "%@ — takes effect in %@": "%@ entra em vigor em %@",
    "%d apps, %d categories": "%d apps, %d categorias",
    "%d hr": "%d h",
    "%d min": "%d min",
    "%d min/day": "%d min/dia",
    "%d minutes": "Minutos %d",
    "%d minutes/day": "%d minutos/dia",
    "%d of %d solved": "%d de %d resolvido",
    "%d selected": "%d selecionado",
    "ACTIVE": "ACTIVO",
    "Add a daily time limit. It activates after your 'more strict' delay (%@).": "Adicione um limite de tempo diário. Ele é ativado após o seu atraso \"mais rigoroso\" (%@).",
    "Add free period: %@ (%@)": "Adicionar período livre: %@ (%@)",
    "Add free period…": "Adicionar período livre...",
    "Add limit: %@ — %d min/day": "Adicionar limite: %@ %d min/dia",
    "Add me": "Adicionar-me",
    "Add my name…": "Adicionar meu nome...",
    "Add schedule: %@ (%@ %@)": "Adicionar horário: %@ (%@ %@)",
    "Add schedule…": "Adicionar calendário...",
    "Adding…": "Adicionar...",
    "Allow app deletion": "Permitir a exclusão de aplicativos",
    "Answer": "Resposta",
    "App deletion": "Apagamento de App",
    "Applies in": "Aplica-se em",
    "Apply now": "Candidar-se agora",
    "Apply now…": "Aplique agora...",
    "Permissions": "Permissões",
    "Demora needs Screen Time access to set limits and block apps, and notifications to tell you when a pending change is ready. iOS will ask for each.": "Demora precisa de acesso ao Tempo de Tela para definir limites e bloquear aplicativos, e notificações para informá-lo quando uma mudança pendente estiver pronta. O iOS pedirá por cada um.",
    "Grant access": "Acesso à subvenção",
    "Welcome to Demora": "Bem-vindo ao Demora",
    "Demora can be a lot at first, so let's set up your first limit together — a quick, hands-on walkthrough of how delays and overrides actually feel. It takes about a minute.": "Demora pode ser muito no início, então vamos configurar seu primeiro limite juntos - um passo rápido e prático de como os atrasos e as substituições realmente se sentem. Demora cerca de um minuto.",
    "Add my first limit": "Adicionar meu primeiro limite",
    "Add your first limit": "Adicione seu primeiro limite",
    "Add a recurring schedule": "Adicionar um horário recorrente",
    "Add a sample contact": "Adicionar um contato de amostra",
    "Add a contact": "Adicionar um contacto",
    "Adding a trusted contact normally waits out a delay. In this tutorial it's instant.": "Adicionar um contato confiável normalmente espera um atraso. Neste tutorial é instantâneo.",
    "Alex (sample)": "Alex (amostra)",
    "Now a schedule. Tap ‘Add a recurring schedule’, pick a time window and some apps, then queue it.": "Agora, toque em 'Adicionar uma programação recorrente', escolha uma janela de tempo e alguns aplicativos e, em seguida, enfileirar.",
    "Two changes are waiting, and you can't wait them out. Tap Select, choose both, Apply — then use the password override. The password is: test": "Duas mudanças estão esperando, e você não pode esperar por elas. Toque em Selecionar, escolha ambas, Aplicar e use a substituição de senha. A senha é: teste",
    "Open Calendar to see everything laid out by day.": "Calendário aberto para ver tudo definido por dia.",
    "Now tidy up: remove the recurring schedule here, and the limit over in Limits.": "Agora, arrume-se: remova o cronograma recorrente aqui e o limite em Limites.",
    "Now tidy up: open Recurring and remove the schedule you made.": "Agora, arrume-se: abra Recorrente e remova o horário que você fez.",
    "And the limit: tap it, then Remove this limit.": "E o limite: toque nele, depois remova esse limite.",
    "Let's add a backup approver. Open Rules → Overrides → Trusted contacts and add a sample contact.": "Vamos adicionar um aprovador de backup. Regras Abertas  Substitui  Contatos confiáveis e adicionar um contato de amostra.",
    "all off": "tudo fora",
    "Home delays": "Home Atrasos",
    "Home overrides": "Sobressalentes da página inicial",
    "shown": "mostrado",
    "hidden": "Escondido",
    "Rules": "Regras",
    "delays, overrides, blocking": "atrasos, ultrapassagens, bloqueio",
    "Current overrides": "Atualidades",
    "No overrides on": "Não há substituições em",
    "People who approve for you": "Pessoas que aprovam para você",
    "Demora code": "Demora código",
    "Code": "Código",
    "Name (optional)": "Nome (opcional)",
    "Unnamed": "Sem nome",
    "Waiting for them to enter their code.": "esperando que eles introduzam seu código.",
    "Added as a trusted contact": "Adicionado como um contato confiável",
    "Add as trusted contact": "Adicionar como contato confiável",
    "They'll get a request to accept before they can approve for you. Adding a contact goes through a delay.": "Eles vão receber um pedido para aceitar antes que possam aprovar para você. Adicionar um contato passa por um atraso.",
    "Removing yourself tells them and stops their requests.": "Remover-se diz-lhes e pára seus pedidos.",
    "That's your own code.": "É o teu próprio código.",
    "These people have you as a trusted contact. Tap one to see their details or add them back. Removing yourself tells them and stops their requests.": "Essas pessoas têm você como um contato confiável. Toque em um para ver seus detalhes ou adicioná-los de volta. Remover-se diz-lhes e pára seus pedidos.",
    "Confirmed": "Confirmado",
    "Send confirmation code": "Enviar código de confirmação",
    "Resend code": "Reenviar código",
    "Confirm contact": "Confirmar contato",
    "Confirm by email": "Confirmar por e-mail",
    "We email a code to this address. Your contact gives you the code, you enter it here, and then they can approve for you. Until then they can't.": "Nós enviamos um código para este endereço. Seu contato dá-lhe o código, você insere aqui, e então eles podem aprovar para você. Até então eles não podem.",
    "Code sent. Ask your contact for it.": "Código enviado. Peça o seu contato para ele.",
    "Daily email limit reached. Try again later.": "Limite de e-mail diário atingido. Tente novamente mais tarde.",
    "You've sent too many codes today. Try again tomorrow.": "Mandaste demasiados códigos hoje, tenta outra vez amanhã.",
    "Couldn't send the code. Check your connection and try again.": "Não consegui enviar o código, verifique a sua ligação e tente novamente.",
    "That code didn't match. Double-check and try again.": "Verifique e tente novamente.",
    "Both email and Demora-user contacts must confirm before they can approve: email contacts enter a code you email them, Demora users accept in their app. Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Tanto os contatos de e-mail quanto os de Demora-usuário devem confirmar antes que possam aprovar: contatos de e-mail inserem um código que você envia por e-mail, usuários de “Demora” aceitam em seu aplicativo. Adicionar um contato é uma mudança menos restrita; remover um é mais rigoroso – ambos passam por atrasos.",
    "Elementary": "Elementar",
    "Middle school": "escola média",
    "High school": "High School",
    "Very easy": "Muito fácil",
    "Your change is ready": "Sua mudança está pronta",
    "Your limits have reset": "Seus limites foram redefinidos",
    "If any apps still look blocked, open Demora to refresh them.": "Se algum aplicativo ainda parecer bloqueado, abra o botão “Demora” para atualizá-lo.",
    "If you denied access, turn on Screen Time for Demora in Settings, then come back.": "Se você negou o acesso, ative o Tempo de Tela para \"Demora\" em Configurações, então volte.",
    "Open Settings": "Abrir definições",
    "Couldn't check the code — check your connection and try again.": "Não foi possível verificar o código verifique a sua conexão e tente novamente.",
    "Couldn't send your response — check your connection and try again.": "Não foi possível enviar sua resposta – verifique sua conexão e tente novamente.",
    "Those changes are still counting down. Wait them out, or turn on an override in Settings → Rules → Overrides to skip the wait.": "Essas alterações ainda estão contando para baixo. Espere-os, ou ative uma substituição em Configurações  Regras  Substituições para pular a espera.",
    "Heads up": "Cabeças para cima",
    "Feature roadmap": "Roteiro de Característica",
    "Software roadmap": "Roteiro de software",
    "features & bugs": "& bugs",
    "links to Trello": "Links para Trello",
    "Safety code": "Código de segurança",
    "Mark as verified": "Marcar como verificado",
    "Verified": "Verificado",
    "Security": "Segurança",
    "Available once you've both added each other.": "Disponível uma vez que ambos tenham se adicionado.",
    "Compare this code with your contact in person or on a call. If it matches on both phones, no one has tampered with the connection.": "Compare este código com o seu contacto pessoalmente ou numa chamada. Se corresponder em ambos os telefones, ninguém adulterou a ligação.",
    "Background blocking may be incomplete": "Bloqueio de fundo pode estar incompleto",
    "iOS limits how many limits and schedules can run in the background at once. Removing a few restores full enforcement.": "O iOS limita quantos limites e horários podem ser executados em segundo plano de uma só vez. Removendo alguns restaura a aplicação completa.",
    "College": "Colégio",
    "Nothing — just a new problem": "Nada – apenas um novo problema",
    "Lose one correct answer": "Perca uma resposta correta",
    "Restart from zero": "Reinicie a partir de zero",
    "Problems to solve": "Problemas para resolver",
    "If an answer is wrong": "Se uma resposta estiver errada",
    "Enable math override (%@, %d problems)": "Habilitar a substituição matemática (problemas do %@, %d)",
    "Solve for x:  %dx + %d = %d": "Solução para x: %d + %d  %d",
    "Solve for x:  (x − %d) × %d = %d": "Resolva para x: (x  %d)  %d  %d",
    "Solve for x:  %dx + %d = %dx + %d": "Resolva para x: %dx + %d = %dx + %d",
    "Solve for x:  %d(x + %d) = %d": "Resolva para x: %d(x + %d) = %d",
    "Wrong — here's a new problem.": "Errado – aqui está um novo problema.",
    "Wrong — you lost one correct answer.": "Errado – você perdeu uma resposta correta.",
    "Wrong — starting over.": "Errado – começar de novo.",
    "Avatar": "avatar",
    "Icon": "cone",
    "Photo": "Foto",
    "Type one emoji": "Tipo um emoji",
    "Choose a photo": "Escolha uma foto",
    "Change photo": "Alterar foto",
    "Remove photo": "Remover foto",
    "Demora %@": "Demora %@",
    "Blocked user": "Usuário bloqueado",
    "Two removals are pending. Tap Select, choose both, Apply — then approve with your trusted contact instead of the password.": "Toque em Selecionar, escolha ambos, Aplicar e depois aprove com seu contato confiável em vez da senha.",
    "This time, use your trusted contact — it'll be approved for you.": "Desta vez, use seu contato confiável – ele será aprovado para você.",
    "Send a request to Alex (sample). A real contact approves from their own Demora app or with an emailed code.": "Enviar um pedido para Alex (amostra). Um contato real aprova a partir de seu próprio aplicativo Demora ou com um código enviado por e-mail.",
    "Waiting for approval…": "Esperando aprovação...",
    "%d changes: %@": "Mudanças no %d: %@",
    "Requested change": "Alteração solicitada",
    "Requested changes": "Alterações solicitadas",
    "Awaiting approval": "Aguardando aprovação",
    "Tap to enter the email code": "Toque para inserir o código de email",
    "Encrypted request — re-add this contact to read it.": "Pedido criptografado – adicione novamente esse contato para lê-lo.",
    "Privacy Policy": "Política de privacidade",
    "Terms of Use": "Termos de Uso",
    "Approved!": "Aprovado!",
    "Almost done": "Quase feito",
    "Nice work — that's the whole loop. Now set the delays and overrides that will actually protect you.": "Bom trabalho esse é todo o loop. Agora defina os atrasos e substituições que realmente o protegerão.",
    "Finish setup": "Configuração do acabamento",
    "Tap ‘Add your first limit’, choose an app or two and a daily budget, then queue the change.": "Toque em “Adicionar seu primeiro limite”, escolha um aplicativo ou dois e um orçamento diário, em seguida, enfileirar a mudança.",
    "Your change is waiting out its delay — and you can't wait this one out. Tap ‘Apply now…’ and use the password override. The password is: test": "Sua mudança está esperando o atraso e você não pode esperar por isso. Toque em ‘Aplicar agora...’ e use a substituição de senha. A senha é: teste",
    "Now remove it: tap the limit, then ‘Remove this limit’.": "Agora remova-o: toque no limite e depois “Remover esse limite”.",
    "Same again — tap ‘Apply now…’ and enter the password (test).": "Mais uma vez, toque em “Aplicar agora...” e digite a senha (teste).",
    "For this tutorial, only the password works. The password is: test": "Para este tutorial, apenas a senha funciona. A senha é: teste",
    "For the tutorial, the password is: test": "Para o tutorial, a senha é: teste",
    "Everything here is just a sample — nothing is saved and nothing is actually blocked. It's only to show how the app works.": "Tudo aqui é apenas uma amostra nada é salvo e nada é realmente bloqueado. É apenas para mostrar como o aplicativo funciona.",
    "Applying…": "A aplicar...",
    "Apps": "Aplicativos",
    "Apps that stay usable": "Apps que podem ser utilizados",
    "Apps to block": "Apps para bloquear",
    "Nothing selected": "Nada selecionado",
    "Apps blocked": "Apps bloqueados",
    "Apps unblocked": "Apps desbloqueados",
    "Blocking the selected apps": "Bloqueando os aplicativos selecionados",
    "Unblocking the selected apps": "Desbloqueando os aplicativos selecionados",
    "Apps to unblock": "Apps para desbloquear",
    "Authorize": "Autorizar",
    "Authorized ✓": "Autorizado",
    "Back": "Voltar",
    "Beta testers": "testadores beta",
    "Block": "Bloquear",
    "Block all except…": "Todos os blocos exceto...",
    "Block app deletion": "Bloquear a exclusão de aplicativos",
    "Block apps": "Bloquear apps",
    "Block only…": "Apenas bloco...",
    "Blocked by Demora": "Bloqueado por Demora",
    "Blocking is enforced by iOS itself through Screen Time, the same system parental controls use.": "O bloqueio é imposto pelo próprio iOS através do Tempo de Tela, o mesmo sistema que os controles dos pais usam.",
    "Cancel": "Cancelar",
    "Change %@ to %d min/day": "Mudança %@ para %d min/dia",
    "Changes that make things LESS STRICT (raise a limit, remove a block, add a free period) wait out your second delay — usually set longer.": "Mudanças que fazem as coisas menos fortes (aumente um limite, remova um bloco, adicione um período livre) espere o seu segundo atraso – geralmente definido por mais tempo.",
    "Changes that make things STRICTER (add a limit, lower minutes, add a schedule) wait out your first delay.": "Mudanças que fazem as coisas ficarem mais difíceis (adicione um limite, minutos mais baixos, adicione um cronograma) espere o seu primeiro atraso.",
    "Changes you make will appear here with a countdown.": "As alterações que você fizer aparecerão aqui com uma contagem regressiva.",
    "Choose apps": "Escolha apps",
    "Close": "Fechar",
    "Confirm password": "Confirmar senha",
    "Continue": "Continuar",
    "Couldn't load names (check iCloud/network).": "Não foi possível carregar nomes (verificar iCloud/rede).",
    "Couldn't submit — make sure you're signed into iCloud and try again.": "Não foi possível enviar – certifique-se de que você está conectado ao iCloud e tente novamente.",
    "Current delays": "Atras actuais",
    "Current: %@": "Atual: %@",
    "Daily limit": "Limite diário",
    "Day %d of every month": "Dia %d de cada mês",
    "Day of month": "Dia do mês",
    "Delay": "Atraso",
    "Delay for LOOSER changes": "Atraso para mudanças LOOSER",
    "Delay for STRICTER changes": "Atraso para mudanças STRICTER",
    "Delays": "Atrasos",
    "Difficulty": "Dificuldade",
    "Disable math override": "Desabilitar a substituição matemática",
    "Disable password override": "Desativar a substituição de palavra-passe",
    "Done": "Feito",
    "Duration": "Duração",
    "During a free period, limits don't block and usage inside the window doesn't count toward them — time used before the window still does.": "Durante um período livre, os limites não bloqueiam e o uso dentro da janela não conta para eles – o tempo usado antes da janela ainda conta.",
    "Easy": "Fácil",
    "Enable math override": "Habilitar a substituição matemática",
    "Enable math override (%@)": "Habilitar a substituição matemática (%@)",
    "Enable password override": "Ativar a substituição de senha",
    "Enable/update password override": "Ativar/atualizar a substituição da palavra-passe",
    "End": "Fim",
    "End early…": "Acabar cedo...",
    "End session early: %@": "Terminar sessão cedo: %@",
    "Ends": "Termina",
    "Enter password": "Enter senha",
    "Every change you make waits out a delay you chose, counting down in the background. You can always change your rules — just not in a moment of weakness.": "Cada mudança que você faz espera um atraso que você escolheu, contando para baixo no fundo. Você sempre pode mudar suas regras - apenas não em um momento de fraqueza.",
    "Every day": "Todos os dias",
    "Everything on the iPhone is blocked during the window except the apps picked here.": "Tudo no iPhone é bloqueado durante a janela, exceto os aplicativos escolhidos aqui.",
    "Free period": "Período livre",
    "Today's usage is reported by iOS Screen Time, which can be slow to load or briefly show nothing. If it looks empty, tap the refresh arrow a couple of times.": "O uso de hoje é relatado pelo Tempo de Tela do iOS, que pode ser lento para carregar ou mostrar brevemente nada. Se parecer vazio, toque na seta de atualização algumas vezes.",
    "Free": "Livre",
    "Free period: %@ (%d min)": "Período livre: %@ (%d min)",
    "Free period — nothing is blocked": "Período livre – nada é bloqueado",
    "Temporarily lifts everything — no app blocks apply, and usage during the free period doesn't count toward your limits.": "Temporariamente levanta tudo – nenhum bloco de aplicativo se aplica, e o uso durante o período livre não conta para seus limites.",
    "Free periods": "Períodos livres",
    "Friction, not passwords": "Fricção, não senhas",
    "Get started": "Começar",
    "Hard": "Difícil",
    "Home": "Início",
    "Hours": "Horas",
    "How does it work?": "Como funciona?",
    "Incorrect password": "Senha incorreta",
    "Keep it appropriate — names are reviewed, and inappropriate ones won't be added.": "Mantenha-o apropriado – os nomes são revisados e os inadequados não serão adicionados.",
    "Language": "Língua",
    "Demora needs Screen Time authorization to set app limits and block apps. iOS will ask for your confirmation.": "Demora precisa de autorização de tempo de tela para definir limites de aplicativos e bloquear aplicativos. O iOS solicitará sua confirmação.",
    "Demora wouldn't exist without the people who tested it, broke it, and told me about it. Thank you. ❤️": "Demora não existiria sem as pessoas que testaram, quebraram-no e me contaram sobre isso. Obrigado.",
    "Less strict": "Menos rigoroso",
    "Less-strict delay": "Atra menos restrito",
    "Limit": "Limite",
    "Limits": "Limites",
    "Limits won't block and usage won't count during this window.": "Limites não bloquearão e o uso não contará durante esta janela.",
    "Limits: daily time budgets per app. When the minutes run out, the app is blocked until midnight.": "Limites: orçamentos diários por aplicativo. Quando os minutos se esgotam, o aplicativo é bloqueado até a meia-noite.",
    "Looser changes": "Mudanças mais lentas",
    "Looser changes wait %@": "Mudanças mais lentas esperam %@",
    "Math override": "Sobreposição matemática",
    "Math problems": "Problemas de matemática",
    "Medium": "Médio",
    "Minutes": "Minutos",
    "Mode": "Modo",
    "Monthly schedules can't cross midnight — set the end time after the start time.": "Horários mensais não podem atravessar a meia-noite – definir o horário de fim após o horário de início.",
    "More strict": "mais rigoroso",
    "More-strict delay": "Atra mais rigoroso",
    "Most screen-time apps protect your rules with a password — which you know, so you cave. Demora protects them with time instead.": "A maioria dos aplicativos de tempo de tela protege suas regras com uma senha – que você sabe, então você cede. Demora protege-os com o tempo em vez disso.",
    "Name": "Nome",
    "Names will appear here soon.": "Os nomes aparecerão aqui em breve.",
    "New free period": "Novo período livre",
    "New limit": "Novo limite",
    "New password": "Nova senha",
    "New schedule": "Novo horário",
    "New session": "Nova sessão",
    "New session…": "Nova sessão...",
    "No free periods": "Sem períodos livres",
    "No limits yet": "Sem limites ainda",
    "No overrides — delays are absolute": "Sem substituições – atrasos são absolutos",
    "No pending changes": "Sem alterações pendentes",
    "No schedules": "Sem horários",
    "No thanks": "Não, obrigado",
    "Nothing planned": "Nada planejado",
    "Nth weekday": "N.o dia da semana",
    "OK": "OK",
    "Off": "Desligado",
    "On": "Ligado",
    "One-off and unplanned, but still delay-gated. A block session waits %@; an unblock session waits %@. Ending early flips the rule (or use an override).": "Uma sessão de bloqueio espera %@; uma sessão de desbloqueio espera %@. Terminar cedo inverte a regra (ou usar uma substituição).",
    "Only the apps picked here are blocked during the window.": "Apenas os aplicativos escolhidos aqui são bloqueados durante a janela.",
    "Overrides": "Exceções",
    "Overrides enabled": "Sobrerides habilitados",
    "Overrides let you skip a pending change's countdown. They're off by default. Adding one later counts as a less-strict change; removing one counts as stricter — both go through delays.": "As substituições permitem que você pule a contagem regressiva de uma mudança pendente. Eles estão desligados por padrão. Adicionando uma conta posterior como uma mudança menos restrita; removendo uma conta como mais estrita - ambas passam por atrasos.",
    "Overrides skip a pending change's countdown. Enabling or weakening one is a less-strict change; disabling or strengthening one is stricter. All edits here go through the matching delay.": "Substituições pular uma mudança pendente contagem regressiva. Habilitar ou enfraquecer um é uma mudança menos estrita; incapacitar ou fortalecer um é mais rigoroso. Todas as edições aqui passar pelo atraso correspondente.",
    "A change for this setting is already pending. Cancel it on the Home tab first if you want something different.": "Uma alteração para esta configuração já está pendente. Cancele-a na guia Início primeiro se quiser algo diferente.",
    "Already pending": "Já pendente",
    "A person you choose approves skipping a countdown — by email code or from their own Demora app. You can also add more later in Settings → Trusted contacts.": "Uma pessoa que você escolher aprova pular uma contagem regressiva por código de e-mail ou a partir de seu próprio aplicativo Demora. Você também pode adicionar mais tarde em Configurações  Contatos confiáveis.",
    "Add": "Adicionar",
    "Message (optional)": "Mensagem (opcional)",
    "Sent along with the request so they know why you're asking.": "Enviada junto com o pedido para que eles saibam por que você está perguntando.",
    "e.g. why you need this": "Por exemplo, por que você precisa disso",
    "%@ — Note: %@": "%@ Nota: %@",
    "Your request was denied.": "O seu pedido foi negado.",
    "Send a new request…": "Enviar um novo pedido...",
    "Cancels this request and lets you pick contacts again.": "Cancela este pedido e permite que você escolha contatos novamente.",
    "Coming soon": "Em breve",
    "Appearance": "Aparência",
    "Theme": "Tema",
    "System": "Sistema",
    "Light": "Luz",
    "Dark": "Escuro",
    "/ de·mo·ra /  noun, Spanish": "/ demora / substantivo, Espanhol",
    "a delay; the time that passes before something takes effect.": "um atraso; o tempo que passa antes que algo entre em vigor.",
    "an iPhone app that protects your screen-time rules with definition 1 instead of a password.": "Um aplicativo para iPhone que protege suas regras de tempo de tela com a definição 1 em vez de uma senha.",
    "Coming soon — payments aren't available yet.": "Em breve – os pagamentos ainda não estão disponíveis.",
    "Password": "Senha",
    "Password override": "Senha desmarcada",
    "Passwords don't match": "Senhas não combinam",
    "Pay %@": "Pague %@",
    "Pay %@ to apply this change now": "Pagar %@ para aplicar esta mudança agora",
    "Pending change": "Mudança pendente",
    "Pending changes": "Alterações pendentes",
    "Pending changes show on the Home tab with a live countdown. You can cancel them anytime before they apply.": "As alterações pendentes são mostradas na guia Início com uma contagem regressiva ao vivo. Você pode cancelá-las a qualquer momento antes de se inscrever.",
    "Plan %@: %@ (%@)": "%@: %@ (%@)",
    "Plan a window": "Planejar uma janela",
    "Plan a window…": "Planejar uma janela...",
    "Plan ahead for specific dates — a trip, a weekend, an exam. Doesn't repeat. Planning a block is stricter; planning a free period is less strict.": "Planeje com antecedência datas específicas uma viagem, um fim de semana, um exame. Não se repete. Planejar um bloco é mais rigoroso; planejar um período livre é menos rigoroso.",
    "Planned (one-off)": "Planejado (one-off)",
    "Planned window": "Janela planejada",
    "Purchasing…": "Comprando...",
    "Queue change": "Alteração de fila",
    "Queue: turn off": "Fiue: Desligar",
    "Queue: turn on": "Fiue: ligar",
    "Recurring schedules": "Horários recorrentes",
    "Remove free period: %@": "Período livre de remoção: %@",
    "Remove limit: %@": "Limite de remoção: %@",
    "Remove planned window: %@": "Janela de remoção planeada: %@",
    "Remove schedule: %@": "Remover horário: %@",
    "Remove this limit": "Remover este limite",
    "Remove…": "Remover...",
    "Repeating windows: every day, chosen weekdays, or monthly patterns. Adding waits %@; removing waits %@.": "Janelas de repetição: todos os dias, dias da semana escolhidos ou padrões mensais. Adicionando esperas %@; removendo esperas %@.",
    "Repeats": "Repetições",
    "Schedule": "Horário",
    "Schedules": "Horários",
    "Schedules: recurring or one-off windows that block chosen apps — or everything except a chosen few. Plus free periods where time doesn't count.": "Horários: janelas recorrentes ou únicas que bloqueiam aplicativos escolhidos ou tudo, exceto alguns escolhidos. Além de períodos livres em que o tempo não conta.",
    "Screen Time access": "Acesso ao Tempo de Uso",
    "Sessions": "Sessões",
    "Set 'less strict' delay to %@": "Definir atraso 'menos rigoroso' para %@",
    "Set 'more strict' delay to %@": "Definir atraso 'mais rigoroso' para %@",
    "Settings": "Configurações",
    "Setup": "Configuração",
    "Simulate payment (beta)": "Simular pagamento (beta)",
    "Skip the wait": "Saltar a espera",
    "Solve %d math problems (%@)": "Resolva problemas matemáticos de %d (%@)",
    "Solve math problems": "Resolver problemas matemáticos",
    "Start": "Iniciar",
    "Start using Demora": "Comece a usar Demora",
    "Starts": "Inicia",
    "Stricter changes": "Mudanças mais rigorosas",
    "Stricter changes wait %@": "Mudanças mais rigorosas esperam %@",
    "Submit": "E-mail",
    "Temporarily lifts limits, schedules, and block sessions for the chosen apps.": "Eleva temporariamente limites, horários e sessões de bloqueio para os aplicativos escolhidos.",
    "Thanks for testing Demora!": "Obrigado por testar Demora!",
    "This app is blocked right now — by a limit, a schedule, or a session. Changing your rules takes a delay; open Demora to queue a change.": "Este aplicativo está bloqueado agora mesmo por um limite, um cronograma ou uma sessão. Alterar suas regras leva um atraso; abra Demora para fazer a fila de uma mudança.",
    "If it should already be unblocked, iOS is sometimes slow to apply a background change — open Demora for an immediate unblock.": "Se já deve ser desbloqueado, o iOS é às vezes lento para aplicar uma mudança de fundo - abra Demora para um desbloqueio imediato.",
    "Two delays rule everything": "Dois atrasos governam tudo",
    "Type": "Tipo",
    "Unblock": "Desbloquear",
    "Unblock apps": "Desbloquear apps",
    "Unlock": "Desbloquear",
    "Wait this long before any change that loosens your rules takes effect. Usually set longer than the first.": "Espere muito antes de qualquer mudança que afrouxe suas regras entrar em vigor. Geralmente definido por mais tempo do que o primeiro.",
    "Wait this long before any change that tightens your rules takes effect.": "Espere muito antes de qualquer mudança que aperta suas regras entrar em vigor.",
    "Want your name in the app's beta-tester thanks page? Pick whatever you'd like to be called.": "Quer seu nome na página de agradecimentos beta do aplicativo? Escolha o que você gostaria de ser chamado.",
    "Weekday": "Semana",
    "Weekdays": "dias da semana",
    "What can it do?": "O que pode fazer?",
    "What's in the box": "O que está na caixa",
    "When": "Quando",
    "When on, deleting ANY app from this iPhone is blocked — including Demora itself, so blocks can't be bypassed by uninstalling.": "Quando ligado, a exclusão de qualquer aplicativo deste iPhone é bloqueada - incluindo o próprio \"Demora\", portanto, os blocos não podem ser contornados pela desinstalação.",
    "Which one": "Qual",
    "Window": "Janela",
    "Wrong — new problem": "Erro novo problema",
    "You're in! Your name will appear in the beta testers page once it's approved.": "O seu nome aparecerá na página beta dos testadores assim que for aprovado.",
    "You're set": "Estás acertada",
    "Your name is in — it'll show up once approved.": "O seu nome está dentro - ele vai aparecer uma vez aprovado.",
    "Your name or nickname": "Seu nome ou apelido",
    "e.g. Airport, weekend trip": "Por exemplo Aeroporto, viagem de fim de semana",
    "e.g. Bedtime": "Por exemplo, Bedtime",
    "e.g. Deep work": "Por exemplo, trabalho profundo",
    "e.g. Instagram": "Por exemplo Instagram",
    "e.g. Lunch break": "Por exemplo, pausa para almoço",
    "free period": "Período livre",
    "limit": "Limite",
    "now": "agora",
    "planned window": "janela planejada",
    "schedule": "calendário",
    "session": "sessão",
    "A passcode is saved. Open the guide below to view it.": "Uma senha é salva. Abra o guia abaixo para visualizá-la.",
    "Access requested. It unlocks after your less-strict delay — track it on the Home tab, where you can also use an override to skip the wait.": "Ele desbloqueia após o seu atraso menos restrito - rastreie-o na guia Home, onde você também pode usar uma substituição para pular a espera.",
    "Can't reach this contact right now — they may have removed Demora or signed out. They won't be able to approve until they're back.": "Não podem chegar a este contacto agora mesmo eles podem ter removido Demora ou assinado. Eles não serão capazes de aprovar até que estejam de volta.",
    "Couldn't start the walkthrough": "Não podia começar a caminhada",
    "Bug tracker": "rastreador de bugs",
    "Demora can't stop you from turning off its Screen Time access in iOS Settings — but a friend can. If Screen Time itself is locked with someone else's passcode, iOS blocks any change to Demora's access, while Demora keeps doing all the blocking.": "Demora não pode impedi-lo de desligar o acesso ao Tempo de Tela nas Configurações do iOS mas um amigo pode. Se o Tempo de Tela em si estiver bloqueado com a senha de outra pessoa, o iOS bloqueia qualquer alteração no acesso do Demora, enquanto o Demora continua fazendo todo o bloqueio.",
    "Demora couldn't safely back up your current setup, so the replay was cancelled to protect your limits. Nothing was changed. Please try again in a moment.": "Demora não poderia fazer backup com segurança da sua configuração atual, então o replay foi cancelado para proteger seus limites. Nada foi alterado. Por favor, tente novamente em um momento.",
    "Done. Now you can't disable Demora's access — or change the passcode — without your friend. To undo it later, your friend enters the passcode and turns it off.": "Agora você não pode desativar o acesso do Demora ou alterar a senha sem seu amigo. Para desfazê-lo mais tarde, seu amigo entra na senha e a desliga.",
    "Email limit": "Limite de e-mail",
    "Emoji": "emoji",
    "Friend: save the passcode here so it isn't lost. It's only shown from this page, which is behind your delay.": "Amigo: guarde a senha aqui para que não seja perdida. É mostrado apenas nesta página, que está por trás do seu atraso.",
    "Hand your phone to your friend. Have THEM enter a 4-digit passcode you don't see — don't watch.": "Mande seu telefone para o seu amigo. Peça a eles que insiram uma senha de 4 dígitos que você não vê - não assista.",
    "Heads up: on your iOS version, a limit only counts screen time from the moment you add it — time you already spent earlier today isn't included. Update to iOS 17.4 or later for exact daily counting.": "Atenção: na sua versão iOS, um limite conta apenas o tempo de tela a partir do momento em que você o adiciona o tempo que você já passou mais cedo hoje não está incluído. Atualize para o iOS 17.4 ou posterior para a contagem diária exata.",
    "Make Demora impossible to disable": "Tornar Demora impossível de desativar",
    "Onboarding demo — you can skip below. It's always available again in Settings → Help.": "Demo de integração você pode pular abaixo. Está sempre disponível novamente em Configurações  Ajuda.",
    "One more safeguard": "Mais uma salvaguarda",
    "Open Settings → Screen Time on this iPhone. If it's off, turn it on.": "Tempo de tela neste iPhone. Se estiver desligado, ligue-o.",
    "Open the guide": "Abra o guia",
    "Opening this is delayed on purpose — so you can't impulsively look up how to undo your own lock.": "A abertura é adiada de propósito – então você não pode impulsivamente procurar como desfazer sua própria fechadura.",
    "Passcode": "Código-passe",
    "Pick someone you trust and can reach. If the passcode and its recovery Apple ID are both lost, removing it may require erasing the device.": "Se a senha e sua recuperação Apple ID forem perdidas, removê-la pode exigir o apagamento do dispositivo.",
    "Prevent disabling": "Impedir a desativação",
    "Protection": "Proteção",
    "Replay walkthrough": "Reexibição do guia passo a passo",
    "Request access": "Pedido de acesso",
    "Save": "Gravar",
    "Saved passcode: %@": "Código de acesso salvo: %@",
    "Unlock viewing the stored passcode": "Desbloquear a senha armazenada",
    "how to lock it with a friend": "Como trancá-lo com um amigo",
    "Screen Time passcode": "Código de acesso do tempo da tela",
    "none saved": "Nenhum salvo",
    "saved": "salvado",
    "Enter passcode": "Digite o código de acesso",
    "save it here so it isn't lost": "Salve aqui para que não seja perdido",
    "replaces the saved one": "Substitui o salvo",
    "behind your delay": "atrás do seu atraso",
    "View passcode": "Ver código de acesso",
    "Change the passcode?": "Mudar a senha?",
    "Are you sure? There is no way to undo this — the saved passcode is replaced only when you save a new one.": "Não há como desfazer isso – a senha salva é substituída apenas quando você salva uma nova.",
    "The friend who set the Screen Time passcode can store it here so it isn't lost. Going back without saving keeps the current one.": "O amigo que definir o código de acesso Screen Time pode armazená-lo aqui para que não seja perdido. Voltar sem salvar mantém o atual.",
    "Viewing the stored passcode is behind your less-strict delay: request it, wait out the delay, and you get one look. After that it locks again.": "Ver a senha armazenada está por trás do seu atraso menos restrito: solicite, espere o atraso e você verá um olhar. Depois disso, ele trava novamente.",
    "Access is spent — viewing it again needs a new request.": "O acesso é gasto – vê-lo novamente precisa de um novo pedido.",
    "Screen Time usually only allows a 4-digit passcode — are you sure this is correct?": "O tempo de tela geralmente só permite uma senha de 4 dígitos - você tem certeza de que isso está correto?",
    "Saved ✓": "Salvo",
    "Show me how": "Mostre-me como",
    "Skip and set up manually": "Saltar e configurar manualmente",
    "Skip walkthrough": "Pular o guia passo a passo",
    "Skip — set up manually": "Skip configurado manualmente",
    "Store the Screen Time passcode": "Armazenar a senha do Tempo de Tela",
    "Take photo": "Foto Foto",
    "Takes about 2 minutes, and you need a second person physically with you.": "Demora cerca de 2 minutos, e você precisa de uma segunda pessoa fisicamente com você.",
    "Tap “Lock Screen Time Settings” (or “Use Screen Time Passcode”).": "Toque em “Lock Screen Time Settings” (ou “Use Screen Time Passcode”).",
    "Thank you. ❤️": "Obrigado.",
    "That's okay. Without Screen Time access Demora can't block apps, but you can continue and turn it on later.": "Sem o acesso ao Screen Time, o Demora não pode bloquear aplicações, mas pode continuar e ligá-las mais tarde.",
    "That's the whole loop. Your real limits, schedules, and settings are still here — nothing changed.": "Seus limites reais, horários e configurações ainda estão aqui - nada mudou.",
    "There's a way to make Demora impossible to turn off — with a friend's help. It takes about 2 minutes and needs a second person physically with you.": "Há uma maneira de tornar o Demora impossível de desligar com a ajuda de um amigo. Leva cerca de 2 minutos e precisa de uma segunda pessoa fisicamente com você.",
    "They call themselves “%@”.": "Eles se chamam de “%@”.",
    "This guide is behind your less-strict delay: request it, wait out the delay, and you get one open. After you view it, it locks again.": "Este guia está por trás do seu atraso menos rigoroso: solicite-o, espere o atraso e você terá um aberto. Depois de vê-lo, ele trava novamente.",
    "Unavailable": "Indisponível",
    "Unlock the “Prevent disabling” guide": "Desbloquear o guia “Prevenir a desativação”",
    "Use photo": "Foto de uso",
    "When asked for Screen Time Passcode Recovery, your friend signs in with THEIR OWN Apple ID — not yours. That's what stops you from resetting the passcode on your own.": "Quando solicitado para Screen Time Passcode Recovery, seu amigo entra com o seu próprio ID Apple não o seu. Isso é o que impede você de redefinir o código por conta própria.",
    "You can always find this later under Help — but there it's behind a delay.": "Você sempre pode encontrar isso mais tarde em Ajuda – mas lá está por trás de um atraso.",
    "You can change these any time under General blocking. Each change then goes through your delays.": "Você pode mudar estes a qualquer momento sob bloqueio geral. Cada mudança, em seguida, passa por seus atrasos.",
    "Your one-time access is ready.": "O seu acesso único está pronto.",
    "lock it with a friend": "Trancá-lo com um amigo",
    "your setup stays safe": "a sua configuração fica segura",
    "—": "—",
]
