//
//  Localization.swift
//  In-app language switching. Strings are written in English in code and
//  looked up in the table below; missing keys fall back to English.
//  Stored in the app group so the extensions localize too.
//

import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case spanish = "es"

    var id: String { rawValue }
    var label: String { self == .english ? "English" : "Español" }

    static var current: AppLanguage {
        get {
            // An explicit in-app choice always wins.
            if let saved = SharedStore.defaults.string(forKey: "latch.language"),
               let lang = AppLanguage(rawValue: saved) {
                return lang
            }
            // Otherwise follow the device: start in Spanish if the device's top
            // preferred language is Spanish, English for everything else.
            let preferred = Locale.preferredLanguages.first ?? "en"
            return preferred.hasPrefix("es") ? .spanish : .english
        }
        set {
            SharedStore.defaults.set(newValue.rawValue, forKey: "latch.language")
        }
    }
}

func tr(_ key: String) -> String {
    guard AppLanguage.current == .spanish else { return key }
    return spanishStrings[key] ?? key
}

private let spanishStrings: [String: String] = [
    "Dismiss": "Descartar",
    "This is a demo — nothing you do here is saved or actually blocked.": "Esto es una demostración — nada de lo que haces aquí se guarda ni se bloquea de verdad.",
    "Limitations": "Limitaciones",
    "iOS reporting notes": "notas de reporte de iOS",
    "Today's usage reporting": "Reporte del uso de hoy",
    "Daily counting on older iOS": "Conteo diario en iOS antiguo",
    "%@ #%d of every month": "%@ #%d de cada mes",
    "%d / %d min": "%d / %d min",
    "blocked until midnight": "bloqueado hasta medianoche",
    "now & next": "ahora y luego",
    "Today's usage": "Uso de hoy",
    "Manage": "Administrar",
    "Week starts": "La semana empieza",
    "Monday": "Lunes",
    "Sunday": "Domingo",
    "Calendar": "Calendario",
    "week / month": "semana / mes",
    "month": "mes",
    "Solve math problems to skip a countdown.": "Resuelve problemas de matemáticas para saltarte una cuenta regresiva.",
    "Enter a password to skip a countdown.": "Ingresa una contraseña para saltarte una cuenta regresiva.",
    "How schedules work": "Cómo funcionan los horarios",
    "Help": "Ayuda",
    "guide, contact, more": "guía, contacto, más",
    "thank you": "gracias",
    "Guide": "Guía",
    "Contact": "Contacto",
    "About": "Acerca de",
    "how each part works": "cómo funciona cada parte",
    "bug, feature, help": "error, función, ayuda",
    "links": "enlaces",
    "Report a bug": "Reportar un error",
    "Request a feature": "Solicitar una función",
    "General help": "Ayuda general",
    "Website": "Sitio web",
    "Instagram": "Instagram",
    "What Demora is": "Qué es Demora",
    "Demora protects your screen-time rules with a delay instead of a password. Every change you make waits out a countdown before it takes effect, so you can always change your mind — just not instantly, in a moment of weakness. Blocking itself is enforced by iOS through Screen Time.": "Demora protege tus reglas de tiempo de pantalla con una espera en lugar de una contraseña. Cada cambio que haces espera una cuenta regresiva antes de tomar efecto, así que siempre puedes cambiar de opinión — solo que no al instante, en un momento de debilidad. El bloqueo en sí lo impone iOS a través de Tiempo de Pantalla.",
    "There are two delays. The more-strict delay gates changes that tighten your rules (adding a limit, lowering minutes, adding a schedule). The less-strict delay gates changes that loosen them (raising a limit, removing a block, adding a free period) — usually set longer. Pending changes show on the Home tab with a live countdown and can be cancelled before they apply.": "Hay dos esperas. La espera más estricta regula los cambios que endurecen tus reglas (agregar un límite, bajar los minutos, agregar un horario). La espera menos estricta regula los que las relajan (subir un límite, quitar un bloqueo, agregar un periodo libre) — normalmente más larga. Los cambios pendientes aparecen en la pestaña de Inicio con una cuenta regresiva en vivo y se pueden cancelar antes de que se apliquen.",
    "A limit is a daily time budget for the apps or categories you choose. When the minutes run out, those apps are blocked until midnight. The Limits tab shows today's usage per limit, and tapping a limit shows exactly which apps it covers.": "Un límite es un presupuesto diario de tiempo para las apps o categorías que elijas. Cuando se acaban los minutos, esas apps se bloquean hasta la medianoche. La pestaña de Límites muestra el uso de hoy por límite, y al tocar un límite ves exactamente qué apps incluye.",
    "Schedules block apps on a repeating or one-off basis. Recurring schedules repeat daily, on chosen weekdays, or monthly. Planned windows are one-offs for specific dates. Sessions are immediate timed blocks or unblocks. Free periods are windows where limits don't block and usage doesn't count.": "Los horarios bloquean apps de forma recurrente o única. Los horarios recurrentes se repiten a diario, en días elegidos de la semana o mensualmente. Las ventanas planificadas son únicas para fechas específicas. Las sesiones son bloqueos o desbloqueos inmediatos con temporizador. Los periodos libres son ventanas donde los límites no bloquean y el uso no cuenta.",
    "A trusted contact can approve skipping a countdown — by email code or from their own Demora app. People you add must accept before they can approve, and you can revoke them at any time.": "Un contacto de confianza puede aprobar saltarse una cuenta regresiva — por código de correo o desde su propia app de Demora. Las personas que agregas deben aceptar antes de poder aprobar, y puedes revocarlas en cualquier momento.",
    "App deletion lock": "Bloqueo de eliminación de apps",
    "the core idea": "la idea central",
    "the two countdowns": "las dos cuentas regresivas",
    "daily app budgets": "presupuestos diarios de apps",
    "recurring, planned, sessions": "recurrentes, planificadas, sesiones",
    "escape hatches": "salidas de emergencia",
    "approval by a person": "aprobación de una persona",
    "can't uninstall to bypass": "no se puede desinstalar para evadir",
    "Most screen-time apps lock your rules behind a password. Because you know the password, you can undo your own rules the moment you feel the urge — so they rarely stick.\n\nDemora protects your rules with time instead. Every change waits out a countdown you set in advance before it takes effect. You stay in full control of your rules, but you can't change them in a single impulsive moment. The blocking itself is enforced by iOS through Screen Time — the same system parental controls use — so it can't be quietly bypassed.": "La mayoría de las apps de tiempo de pantalla protegen tus reglas con una contraseña. Como conoces la contraseña, puedes deshacer tus propias reglas en cuanto sientes el impulso — así que rara vez se mantienen.\n\nDemora protege tus reglas con tiempo en su lugar. Cada cambio espera una cuenta regresiva que defines de antemano antes de tomar efecto. Mantienes el control total de tus reglas, pero no puedes cambiarlas en un solo momento impulsivo. El bloqueo en sí lo impone iOS a través de Tiempo de Pantalla — el mismo sistema que usan los controles parentales — así que no se puede evadir en silencio.",
    "Demora has two delays. The more-strict delay covers any change that tightens your rules: adding a limit, lowering its minutes, adding a schedule, or turning on the deletion lock. The less-strict delay covers changes that loosen them: raising a limit, removing a block, adding a free period, or disabling an override. The less-strict delay is usually set longer, since loosening is where temptation lives.\n\nA change doesn't apply right away — it becomes a pending change with a live countdown on the Home tab. You can cancel it any time before it lands, and when the countdown reaches zero it applies on its own, even if the app is closed.": "Demora tiene dos esperas. La espera más estricta cubre cualquier cambio que endurece tus reglas: agregar un límite, bajar sus minutos, agregar un horario o activar el bloqueo de eliminación. La espera menos estricta cubre los cambios que las relajan: subir un límite, quitar un bloqueo, agregar un periodo libre o desactivar una anulación. La espera menos estricta normalmente se configura más larga, ya que relajar es donde vive la tentación.\n\nUn cambio no se aplica de inmediato — se convierte en un cambio pendiente con una cuenta regresiva en vivo en la pestaña de Inicio. Puedes cancelarlo en cualquier momento antes de que se aplique, y cuando la cuenta llega a cero se aplica solo, incluso si la app está cerrada.",
    "A limit is a daily time budget for a set of apps or whole categories. When the minutes run out, those apps are blocked for the rest of the day and unlock again at midnight.\n\nThe Limits tab shows today's real usage for each limit, read straight from Screen Time, and tapping a limit reveals exactly which apps and categories it covers. Because usage is measured by iOS, time spent before you created the limit still counts toward it that day. Raising or removing a limit is a less-strict change; adding one or lowering its minutes is stricter.": "Un límite es un presupuesto diario de tiempo para un conjunto de apps o categorías completas. Cuando se acaban los minutos, esas apps se bloquean por el resto del día y se desbloquean de nuevo a la medianoche.\n\nLa pestaña de Límites muestra el uso real de hoy para cada límite, leído directamente de Tiempo de Pantalla, y al tocar un límite ves exactamente qué apps y categorías incluye. Como el uso lo mide iOS, el tiempo usado antes de crear el límite también cuenta ese día. Subir o quitar un límite es un cambio menos estricto; agregar uno o bajar sus minutos es más estricto.",
    "Schedules block apps by time rather than by budget, in a few shapes. Recurring schedules repeat — every day, on chosen weekdays, or on a monthly pattern. Planned windows are one-offs for a specific date, like a trip or an exam. Sessions are immediate, timed blocks or unblocks you start right now. Free periods are windows where limits don't block and usage doesn't count toward them.\n\nEach blocking schedule either blocks the apps you pick, or blocks everything except the apps you pick. When rules overlap, the most specific one wins: a session beats a planned window, which beats a recurring schedule, and within the same kind the one added most recently takes priority.": "Los horarios bloquean apps por tiempo en lugar de por presupuesto, en varias formas. Los horarios recurrentes se repiten — cada día, en días elegidos de la semana o en un patrón mensual. Las ventanas planificadas son únicas para una fecha específica, como un viaje o un examen. Las sesiones son bloqueos o desbloqueos inmediatos con temporizador que inicias ahora mismo. Los periodos libres son ventanas donde los límites no bloquean y el uso no cuenta para ellos.\n\nCada horario de bloqueo bloquea las apps que eliges, o bloquea todo excepto las apps que eliges. Cuando las reglas se superponen, gana la más específica: una sesión vence a una ventana planificada, que vence a un horario recurrente, y dentro del mismo tipo la agregada más recientemente tiene prioridad.",
    "Overrides are optional escape hatches that let you skip a pending change's countdown. There are three: solve a set of math problems, enter a password, or ask a trusted contact to approve. They're all off by default, so out of the box your delays are absolute.\n\nTurning an override on, or making it easier, counts as a less-strict change and waits out that delay. Turning one off, or making it harder, is stricter — so you can't instantly weaken your own safety net.": "Las anulaciones son salidas de emergencia opcionales que te permiten saltarte la cuenta regresiva de un cambio pendiente. Hay tres: resolver un conjunto de problemas de matemáticas, ingresar una contraseña o pedirle a un contacto de confianza que apruebe. Todas están desactivadas por defecto, así que de fábrica tus esperas son absolutas.\n\nActivar una anulación, o hacerla más fácil, cuenta como un cambio menos estricto y espera esa demora. Desactivar una, o hacerla más difícil, es más estricto — así no puedes debilitar al instante tu propia red de seguridad.",
    "A trusted contact is a person who can approve skipping a countdown for you. They can approve by entering a short code sent to their email, or directly from their own copy of Demora.\n\nAnyone you add has to accept the request before they can approve anything, so no one is involved without their knowledge. You can revoke a contact at any time, and they can step down on their side too. Adding the override is a less-strict change; removing it is stricter.": "Un contacto de confianza es una persona que puede aprobar saltarse una cuenta regresiva por ti. Puede aprobar ingresando un código corto enviado a su correo, o directamente desde su propia copia de Demora.\n\nCualquier persona que agregues debe aceptar la solicitud antes de poder aprobar algo, así que nadie participa sin saberlo. Puedes revocar un contacto en cualquier momento, y esa persona también puede retirarse por su lado. Agregar la anulación es un cambio menos estricto; quitarla es más estricto.",
    "When the deletion lock is on, deleting any app from this iPhone is blocked — including Demora itself. That closes the most obvious loophole: uninstalling the app to wipe your rules.\n\nBecause turning the lock off makes things easier to bypass, it counts as a less-strict change and waits out that delay before it takes effect.": "Cuando el bloqueo de eliminación está activado, se bloquea eliminar cualquier app de este iPhone — incluida la propia Demora. Eso cierra el hueco más obvio: desinstalar la app para borrar tus reglas.\n\nComo desactivar el bloqueo facilita evadirlo, cuenta como un cambio menos estricto y espera esa demora antes de tomar efecto.",
    "When on, deleting any app from this iPhone is blocked — including Demora itself — so your rules can't be bypassed by uninstalling. Turning it off goes through the less-strict delay.": "Cuando está activado, se bloquea eliminar cualquier app de este iPhone — incluida la propia Demora — para que tus reglas no se puedan evadir desinstalando. Desactivarlo pasa por la espera menos estricta.",
    "Blocks": "Bloqueos",
    "New recurring": "Nuevo recurrente",
    "Week": "Semana",
    "Month": "Mes",
    "Nothing on this day.": "Nada este día.",
    "When things overlap": "Cuando se superponen",
    "One-off, right now: block or unblock chosen apps for a set number of minutes. Still delay-gated to start; ending early flips the rule.": "Puntual, ahora mismo: bloquea o desbloquea apps elegidas por una cantidad de minutos. Aún tiene espera para empezar; terminar antes invierte la regla.",
    "One-off windows for specific dates — a trip, an exam. Block, allow-all-except, or a free period. Doesn't repeat.": "Ventanas únicas para fechas específicas — un viaje, un examen. Bloquear, permitir todo excepto, o un periodo libre. No se repite.",
    "Windows that repeat — daily, by weekday, or monthly. Each is either a block or a free period.": "Ventanas que se repiten — diario, por día de la semana o mensual. Cada una es un bloqueo o un periodo libre.",
    "Limits don't block during the window, and time used inside it doesn't count against your daily budgets.": "Los límites no bloquean durante la ventana, y el tiempo usado dentro no cuenta para tus presupuestos diarios.",
    "Priority: a session beats a planned window, which beats a recurring schedule. Within the same kind, the one you added most recently wins.": "Prioridad: una sesión gana a una ventana planeada, que gana a un horario recurrente. Dentro del mismo tipo, gana la que agregaste más recientemente.",
    "today %@–%@": "hoy %@–%@",
    "Current passcode": "Contraseña actual",
    "New passcode": "Nueva contraseña",
    "Confirm new passcode": "Confirmar nueva contraseña",
    "Change passcode": "Cambiar contraseña",
    "Change passcode now": "Cambiar contraseña ahora",
    "Enter your current passcode to change it instantly. Forgot it? Reset below — that one waits out your delay.": "Ingresa tu contraseña actual para cambiarla al instante. ¿La olvidaste? Restablécela abajo — esa pasa por tu espera.",
    "Forgot it?": "¿La olvidaste?",
    "Reset passcode (forgot)": "Restablecer contraseña (olvidada)",
    "Turn off password override": "Desactivar anulación por contraseña",
    "Wrong passcode.": "Contraseña incorrecta.",
    "Select": "Seleccionar",
    "Cancel %d": "Cancelar %d",
    "Apply %d now": "Aplicar %d ahora",
    "%d changes": "%d cambios",
    "Denied": "Rechazada",
    "My info": "Mi info",
    "view": "ver",
    "Nobody yet": "Nadie aún",
    "language, theme, case": "idioma, tema, formato",
    "%@ · %@": "%@ · %@",
    "none on": "ninguna activa",
    "%d on": "%d activas",
    "Nothing scheduled right now.": "Nada programado por ahora.",
    "Active now": "Activo ahora",
    "Coming up": "Próximamente",
    "until %@": "hasta %@",
    "today at %@": "hoy a las %@",
    "Planned": "Planeado",
    "Recurring": "Recurrentes",
    "none": "ninguno",
    "No active sessions": "Sin sesiones activas",
    "%d · %d active": "%d · %d activos",
    "%d total": "%d en total",
    "Your name": "Tu nombre",
    "Your name (optional)": "Tu nombre (opcional)",
    "Shown to people you ask to approve, so they know it's you.": "Se muestra a las personas a las que pides aprobación, para que sepan que eres tú.",
    "People you approve for": "Personas para las que apruebas",
    "These people have you as a trusted contact. Removing yourself tells them and stops their requests.": "Estas personas te tienen como contacto de confianza. Quitarte se lo avisa y detiene sus solicitudes.",
    "Remove": "Quitar",
    "code %@": "código %@",
    "Demora user %@": "Usuario de Demora %@",
    "%@ removed their permission to be your trusted contact.": "%@ quitó su permiso para ser tu contacto de confianza.",
    "Trusted contact removed": "Contacto de confianza eliminado",
    "A trusted contact": "Un contacto de confianza",
    "That's your own code — add someone else.": "Ese es tu propio código — agrega a alguien más.",
    "You already have this person as a contact.": "Ya tienes a esta persona como contacto.",
    "Request history": "Historial de solicitudes",
    "Blocked users": "Usuarios bloqueados",
    "No requests yet.": "Aún no hay solicitudes.",
    "No blocked users.": "No hay usuarios bloqueados.",
    "Blocked": "Bloqueado",
    "Accepted": "Aceptada",
    "Declined": "Rechazada",
    "Requested": "Solicitó",
    "Accept": "Aceptar",
    "Decline": "Rechazar",
    "Active": "Activo",
    "Pending": "Pendiente",
    "Contact requests": "Solicitudes de contacto",
    "Pending — hasn't accepted yet": "Pendiente — aún no acepta",
    "Waiting for them to accept in their Demora app.": "Esperando a que acepte en su app de Demora.",
    "A trusted contact can let you skip a pending change's countdown — by emailing you a one-time code, or, if they use Demora, by approving from their own app.": "Un contacto de confianza puede dejarte saltar la cuenta regresiva de un cambio pendiente — enviándote un código de un solo uso por correo, o, si usa Demora, aprobando desde su propia app.",
    "Share this code so another Demora user can add you. You get a request to accept before it's active.": "Comparte este código para que otro usuario de Demora pueda agregarte. Recibes una solicitud para aceptar antes de que quede activo.",
    "A Demora user (code %@) wants to add you as their trusted contact.": "Un usuario de Demora (código %@) quiere agregarte como su contacto de confianza.",
    "%@ (code %@) wants to add you as their trusted contact.": "%@ (código %@) quiere agregarte como su contacto de confianza.",
    "If you accept, they can ask you to approve skipping their delays.": "Si aceptas, podrán pedirte que apruebes saltarse sus esperas.",
    "Email contacts work as soon as you add them. Demora-user contacts must accept first. Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Los contactos por correo funcionan en cuanto los agregas. Los contactos usuarios de Demora deben aceptar primero. Agregar un contacto es un cambio menos estricto; quitarlo es más estricto — ambos pasan por esperas.",
    "Ask them for the code in their Demora settings. They'll get a request to accept before they can approve for you.": "Pídeles el código que aparece en sus ajustes de Demora. Recibirán una solicitud para aceptar antes de poder aprobar por ti.",
    "change": "cambiar",
    "Text case": "Formato de texto",
    "lowercase": "minúsculas",
    "Regular": "normal",
    "6-digit code": "Código de 6 dígitos",
    "Add contact": "Agregar contacto",
    "Add contact…": "Agregar contacto…",
    "Add trusted contact: %@": "Agregar contacto de confianza: %@",
    "Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Agregar un contacto es un cambio menos estricto; quitarlo es más estricto — ambos pasan por esperas.",
    "Any one approval unlocks the change.": "Una sola aprobación desbloquea el cambio.",
    "Approval requests": "Solicitudes de aprobación",
    "Approve": "Aprobar",
    "Ask a contact": "Pedir a un contacto",
    "Ask a trusted contact": "Pedir a un contacto de confianza",
    "Ask them for the code shown in their Demora settings.": "Pídele el código que aparece en sus ajustes de Demora.",
    "Checking…": "Verificando…",
    "Checks automatically every few seconds. The request expires after 1 hour.": "Se verifica automáticamente cada pocos segundos. La solicitud expira en 1 hora.",
    "Contacts": "Contactos",
    "approvers, blocked": "aprobadores, bloqueados",
    "Couldn't send the request — check your connection and try again.": "No se pudo enviar la solicitud — revisa tu conexión e inténtalo de nuevo.",
    "Too many requests to this contact right now. Try again later.": "Demasiadas solicitudes a este contacto ahora mismo. Inténtalo más tarde.",
    "You've used all of today's approval emails. Try again tomorrow.": "Ya usaste todos tus correos de aprobación de hoy. Inténtalo mañana.",
    "General blocking": "Bloqueo general",
    "deletion, websites": "borrado, sitios web",
    "Block adult websites": "Bloquear sitios para adultos",
    "Allow adult websites": "Permitir sitios para adultos",
    "Uses Apple's built-in filter to limit adult websites in Safari and other apps.": "Usa el filtro integrado de Apple para limitar sitios para adultos en Safari y otras apps.",
    "Website blocker": "Bloqueador de sitios web",
    "Block website: %@": "Bloquear sitio: %@",
    "Unblock website: %@": "Desbloquear sitio: %@",
    "e.g. reddit.com": "p. ej. reddit.com",
    "Queue: remove": "Programar: quitar",
    "Block specific websites by typing their domain — no need for Apple's site picker, which often comes up empty. Note: blocking sites also turns on Apple's adult-content filter. Adding a site is gated by your delays; removing one waits the longer delay.": "Bloquea sitios específicos escribiendo su dominio — sin depender del selector de sitios de Apple, que muchas veces aparece vacío. Nota: bloquear sitios también activa el filtro de contenido para adultos de Apple. Agregar un sitio respeta tus esperas; quitar uno espera el plazo más largo.",
    "Blocked all day": "Bloqueado todo el día",
    "Adult websites": "Sitios para adultos",
    "%d sites": "%d sitios",
    "Blocked sites": "Sitios bloqueados",
    "Stop apps from being deleted, limit adult websites, or block specific sites by domain. Every change here goes through your delays.": "Evita que se borren apps, limita sitios para adultos o bloquea sitios específicos por dominio. Cada cambio aquí respeta tus esperas.",
    "0 minutes — this app stays blocked all day, every day.": "0 minutos — esta app queda bloqueada todo el día, todos los días.",
    "Approval emails are at capacity right now. Try again later, or use a Demora contact.": "Los correos de aprobación están al límite ahora mismo. Inténtalo más tarde o usa un contacto de Demora.",
    "You've sent today": "Enviados hoy",
    "All users · today": "Todos los usuarios · hoy",
    "All users · this month": "Todos los usuarios · este mes",
    "Email approvals": "Aprobaciones por correo",
    "Email contacts have a daily send limit; Demora-user contacts don't.": "Los contactos por correo tienen un límite diario de envíos; los contactos de Demora no.",
    "one-time, forever": "pago único, para siempre",
    "active": "activo",
    "Deny": "Rechazar",
    "Disable trusted-contact override": "Desactivar anulación por contacto de confianza",
    "Email": "Correo",
    "Email address": "Dirección de correo",
    "Email code": "Código por correo",
    "Email contacts aren't available yet in this build.": "Los contactos por correo aún no están disponibles en esta versión.",
    "Enable trusted-contact override": "Activar anulación por contacto de confianza",
    "Friends who use Demora can add you as their trusted contact with this code.": "Tus amigos que usan Demora pueden agregarte como su contacto de confianza con este código.",
    "Demora user": "Usuario de Demora",
    "My code": "Mi código",
    "No Demora user found with that code.": "No se encontró ningún usuario de Demora con ese código.",
    "No contacts yet": "Aún no hay contactos",
    "Remove trusted contact: %@": "Quitar contacto de confianza: %@",
    "Send request": "Enviar solicitud",
    "Sending…": "Enviando…",
    "Someone set you as their trusted contact and wants to skip a waiting period.": "Alguien te puso como su contacto de confianza y quiere saltarse una espera.",
    "Their Demora code": "Su código de Demora",
    "Trusted contacts": "Contactos de confianza",
    "Trusted-contact override": "Anulación por contacto de confianza",
    "Verify code": "Verificar código",
    "Waiting for approval from their Demora app…": "Esperando aprobación desde su app de Demora…",
    "When enabled, a trusted contact can let you skip a pending change's countdown — by emailing you a code, or by approving from their own Demora app.": "Cuando está activado, un contacto de confianza puede dejarte saltar la cuenta regresiva de un cambio pendiente — enviándote un código por correo o aprobando desde su propia app de Demora.",
    "Who should approve?": "¿Quién debe aprobar?",
    "Wrong or expired code.": "Código incorrecto o expirado.",
    "Your contact received a code by email. Enter it here. It expires in 15 minutes.": "Tu contacto recibió un código por correo. Ingrésalo aquí. Expira en 15 minutos.",
    "contact": "contacto",
    "e.g. Mom, Alex": "p. ej. Mamá, Alex",
    "%@ (%d problems)": "%@ (%d problemas)",
    "%@ session: %@ (%d min)": "Sesión de %@: %@ (%d min)",
    "%@ — session starts in %@, then runs %d min": "%@ — la sesión empieza en %@ y dura %d min",
    "%@ — takes effect in %@": "%@ — se aplica en %@",
    "%d apps, %d categories": "%d apps, %d categorías",
    "%d hr": "%d h",
    "%d min": "%d min",
    "%d min/day": "%d min/día",
    "%d minutes": "%d minutos",
    "%d minutes/day": "%d minutos/día",
    "%d of %d solved": "%d de %d resueltos",
    "%d selected": "%d seleccionadas",
    "ACTIVE": "ACTIVO",
    "Add a daily time limit. It activates after your 'more strict' delay (%@).": "Agrega un límite diario de tiempo. Se activa después de tu espera de 'más estricto' (%@).",
    "Add free period: %@ (%@)": "Agregar periodo libre: %@ (%@)",
    "Add free period…": "Agregar periodo libre…",
    "Add limit: %@ — %d min/day": "Agregar límite: %@ — %d min/día",
    "Add me": "Agrégame",
    "Add my name…": "Agregar mi nombre…",
    "Add schedule: %@ (%@ %@)": "Agregar horario: %@ (%@ %@)",
    "Add schedule…": "Agregar horario…",
    "Adding…": "Agregando…",
    "Allow app deletion": "Permitir borrar apps",
    "Answer": "Respuesta",
    "App deletion": "Borrado de apps",
    "Applies in": "Se aplica en",
    "Apply now": "Aplicar ahora",
    "Apply now…": "Aplicar ahora…",
    "Permissions": "Permisos",
    "Demora needs Screen Time access to set limits and block apps, and notifications to tell you when a pending change is ready. iOS will ask for each.": "Demora necesita acceso a Tiempo de Pantalla para poner límites y bloquear apps, y notificaciones para avisarte cuando un cambio pendiente esté listo. iOS te pedirá cada uno.",
    "Grant access": "Conceder acceso",
    "Welcome to Demora": "Bienvenido a Demora",
    "Demora can be a lot at first, so let's set up your first limit together — a quick, hands-on walkthrough of how delays and overrides actually feel. It takes about a minute.": "Demora puede abrumar al principio, así que configuremos juntos tu primer límite — un recorrido práctico y rápido de cómo se sienten las esperas y las anulaciones. Toma cerca de un minuto.",
    "Add my first limit": "Agregar mi primer límite",
    "Add your first limit": "Agrega tu primer límite",
    "Add a recurring schedule": "Agregar un horario recurrente",
    "Add a sample contact": "Agregar un contacto de ejemplo",
    "Add a contact": "Agregar un contacto",
    "Adding a trusted contact normally waits out a delay. In this tutorial it's instant.": "Agregar un contacto de confianza normalmente espera una demora. En este tutorial es instantáneo.",
    "Alex (sample)": "Alex (ejemplo)",
    "Now a schedule. Tap ‘Add a recurring schedule’, pick a time window and some apps, then queue it.": "Ahora un horario. Toca ‘Agregar un horario recurrente’, elige una franja horaria y algunas apps, luego ponlo en cola.",
    "Two changes are waiting, and you can't wait them out. Tap Select, choose both, Apply — then use the password override. The password is: test": "Dos cambios están esperando, y no los puedes esperar. Toca Seleccionar, elige ambos, Aplicar — luego usa la anulación por contraseña. La contraseña es: test",
    "Open Calendar to see everything laid out by day.": "Abre el Calendario para ver todo organizado por día.",
    "Now tidy up: remove the recurring schedule here, and the limit over in Limits.": "Ahora a ordenar: quita el horario recurrente aquí, y el límite en Límites.",
    "Now tidy up: open Recurring and remove the schedule you made.": "Ahora a ordenar: abre Recurrentes y quita el horario que creaste.",
    "And the limit: tap it, then Remove this limit.": "Y el límite: tócalo, luego Quitar este límite.",
    "Let's add a backup approver. Open Rules → Overrides → Trusted contacts and add a sample contact.": "Agreguemos un aprobador de respaldo. Abre Reglas → Anulaciones → Contactos de confianza y agrega un contacto de ejemplo.",
    "all off": "todas apagadas",
    "Home delays": "Esperas en inicio",
    "Home overrides": "Anulaciones en inicio",
    "shown": "visible",
    "hidden": "oculto",
    "Rules": "Reglas",
    "delays, overrides, blocking": "esperas, anulaciones, bloqueo",
    "Current overrides": "Anulaciones actuales",
    "No overrides on": "Ninguna anulación activa",
    "People who approve for you": "Personas que aprueban por ti",
    "Demora code": "Código de Demora",
    "Code": "Código",
    "Name (optional)": "Nombre (opcional)",
    "Unnamed": "Sin nombre",
    "Waiting for them to enter their code.": "Esperando a que ingresen su código.",
    "Added as a trusted contact": "Agregado como contacto de confianza",
    "Add as trusted contact": "Agregar como contacto de confianza",
    "They'll get a request to accept before they can approve for you. Adding a contact goes through a delay.": "Recibirán una solicitud para aceptar antes de poder aprobar por ti. Agregar un contacto pasa por una espera.",
    "Removing yourself tells them and stops their requests.": "Quitarte les avisa y detiene sus solicitudes.",
    "That's your own code.": "Ese es tu propio código.",
    "These people have you as a trusted contact. Tap one to see their details or add them back. Removing yourself tells them and stops their requests.": "Estas personas te tienen como contacto de confianza. Toca una para ver sus detalles o agregarla de nuevo. Quitarte les avisa y detiene sus solicitudes.",
    "Confirmed": "Confirmado",
    "Send confirmation code": "Enviar código de confirmación",
    "Resend code": "Reenviar código",
    "Confirm contact": "Confirmar contacto",
    "Confirm by email": "Confirmar por correo",
    "We email a code to this address. Your contact gives you the code, you enter it here, and then they can approve for you. Until then they can't.": "Enviamos un código a esta dirección. Tu contacto te da el código, lo ingresas aquí y entonces podrá aprobar por ti. Hasta entonces no puede.",
    "Code sent. Ask your contact for it.": "Código enviado. Pídeselo a tu contacto.",
    "Daily email limit reached. Try again later.": "Se alcanzó el límite diario de correos. Inténtalo más tarde.",
    "You've sent too many codes today. Try again tomorrow.": "Has enviado demasiados códigos hoy. Inténtalo mañana.",
    "Couldn't send the code. Check your connection and try again.": "No se pudo enviar el código. Revisa tu conexión e inténtalo de nuevo.",
    "That code didn't match. Double-check and try again.": "Ese código no coincide. Verifícalo e inténtalo de nuevo.",
    "Both email and Demora-user contacts must confirm before they can approve: email contacts enter a code you email them, Demora users accept in their app. Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Tanto los contactos por correo como los de Demora deben confirmar antes de poder aprobar: los de correo ingresan un código que les envías, los de Demora aceptan en su app. Agregar un contacto es un cambio menos estricto; quitarlo es más estricto — ambos pasan por esperas.",
    "Elementary": "Primaria",
    "Middle school": "Secundaria",
    "High school": "Preparatoria",
    "Very easy": "Muy fácil",
    "Your change is ready": "Tu cambio está listo",
    "If you denied access, turn on Screen Time for Demora in Settings, then come back.": "Si negaste el acceso, activa Tiempo en Pantalla para Demora en Ajustes y vuelve.",
    "Open Settings": "Abrir Ajustes",
    "Couldn't check the code — check your connection and try again.": "No se pudo verificar el código — revisa tu conexión e inténtalo de nuevo.",
    "Couldn't send your response — check your connection and try again.": "No se pudo enviar tu respuesta — revisa tu conexión e inténtalo de nuevo.",
    "Those changes are still counting down. Wait them out, or turn on an override in Settings → Rules → Overrides to skip the wait.": "Esos cambios aún están en cuenta regresiva. Espéralos, o activa una anulación en Ajustes → Reglas → Anulaciones para saltarte la espera.",
    "Heads up": "Atención",
    "Feature roadmap": "Hoja de ruta",
    "Software roadmap": "Hoja de ruta del software",
    "features & bugs": "funciones y errores",
    "links to Trello": "enlaza a Trello",
    "Safety code": "Código de seguridad",
    "Mark as verified": "Marcar como verificado",
    "Verified": "Verificado",
    "Security": "Seguridad",
    "Available once you've both added each other.": "Disponible cuando ambos se hayan agregado.",
    "Compare this code with your contact in person or on a call. If it matches on both phones, no one has tampered with the connection.": "Compara este código con tu contacto en persona o por llamada. Si coincide en ambos teléfonos, nadie ha manipulado la conexión.",
    "Background blocking may be incomplete": "El bloqueo en segundo plano puede estar incompleto",
    "iOS limits how many limits and schedules can run in the background at once. Removing a few restores full enforcement.": "iOS limita cuántos límites y horarios pueden ejecutarse en segundo plano a la vez. Quitar algunos restaura el bloqueo completo.",
    "College": "Universidad",
    "Nothing — just a new problem": "Nada — solo un problema nuevo",
    "Lose one correct answer": "Perder una respuesta correcta",
    "Restart from zero": "Reiniciar desde cero",
    "Problems to solve": "Problemas a resolver",
    "If an answer is wrong": "Si una respuesta es incorrecta",
    "Enable math override (%@, %d problems)": "Activar anulación con matemáticas (%@, %d problemas)",
    "Solve for x:  %dx + %d = %d": "Resuelve x:  %dx + %d = %d",
    "Solve for x:  (x − %d) × %d = %d": "Resuelve x:  (x − %d) × %d = %d",
    "Solve for x:  %dx + %d = %dx + %d": "Resuelve x:  %dx + %d = %dx + %d",
    "Solve for x:  %d(x + %d) = %d": "Resuelve x:  %d(x + %d) = %d",
    "Wrong — here's a new problem.": "Incorrecto — aquí tienes un problema nuevo.",
    "Wrong — you lost one correct answer.": "Incorrecto — perdiste una respuesta correcta.",
    "Wrong — starting over.": "Incorrecto — empezando de nuevo.",
    "Avatar": "Avatar",
    "Icon": "Ícono",
    "Photo": "Foto",
    "Type one emoji": "Escribe un emoji",
    "Choose a photo": "Elegir una foto",
    "Change photo": "Cambiar foto",
    "Remove photo": "Quitar foto",
    "Demora %@": "Demora %@",
    "Blocked user": "Usuario bloqueado",
    "Two removals are pending. Tap Select, choose both, Apply — then approve with your trusted contact instead of the password.": "Hay dos eliminaciones pendientes. Toca Seleccionar, elige ambos, Aplicar — luego aprueba con tu contacto de confianza en lugar de la contraseña.",
    "This time, use your trusted contact — it'll be approved for you.": "Esta vez, usa tu contacto de confianza — se aprobará por ti.",
    "Send a request to Alex (sample). A real contact approves from their own Demora app or with an emailed code.": "Envía una solicitud a Alex (ejemplo). Un contacto real aprueba desde su propia app de Demora o con un código por correo.",
    "Waiting for approval…": "Esperando aprobación…",
    "%d changes: %@": "%d cambios: %@",
    "Requested change": "Cambio solicitado",
    "Requested changes": "Cambios solicitados",
    "Awaiting approval": "Esperando aprobación",
    "Tap to enter the email code": "Toca para ingresar el código del correo",
    "Encrypted request — re-add this contact to read it.": "Solicitud cifrada — vuelve a agregar este contacto para leerla.",
    "Privacy Policy": "Política de privacidad",
    "Terms of Use": "Términos de uso",
    "Approved!": "¡Aprobado!",
    "Almost done": "Casi listo",
    "Nice work — that's the whole loop. Now set the delays and overrides that will actually protect you.": "Buen trabajo — ese es el ciclo completo. Ahora configura las esperas y anulaciones que de verdad te protegerán.",
    "Finish setup": "Finalizar configuración",
    "Tap ‘Add your first limit’, choose an app or two and a daily budget, then queue the change.": "Toca ‘Agrega tu primer límite’, elige una app o dos y un presupuesto diario, luego pon el cambio en cola.",
    "Your change is waiting out its delay — and you can't wait this one out. Tap ‘Apply now…’ and use the password override. The password is: test": "Tu cambio está esperando su demora — y este no lo puedes esperar. Toca ‘Aplicar ahora…’ y usa la anulación por contraseña. La contraseña es: test",
    "Now remove it: tap the limit, then ‘Remove this limit’.": "Ahora quítalo: toca el límite, luego ‘Quitar este límite’.",
    "Same again — tap ‘Apply now…’ and enter the password (test).": "Otra vez — toca ‘Aplicar ahora…’ e ingresa la contraseña (test).",
    "For this tutorial, only the password works. The password is: test": "Para este tutorial, solo funciona la contraseña. La contraseña es: test",
    "For the tutorial, the password is: test": "Para el tutorial, la contraseña es: test",
    "Everything here is just a sample — nothing is saved and nothing is actually blocked. It's only to show how the app works.": "Todo esto es solo una muestra — nada se guarda y nada se bloquea de verdad. Es solo para mostrarte cómo funciona la app.",
    "Applying…": "Aplicando…",
    "Apps": "Apps",
    "Apps that stay usable": "Apps que siguen disponibles",
    "Apps to block": "Apps a bloquear",
    "Nothing selected": "Nada seleccionado",
    "Apps blocked": "Apps bloqueadas",
    "Apps unblocked": "Apps desbloqueadas",
    "Blocking the selected apps": "Bloqueando las apps seleccionadas",
    "Unblocking the selected apps": "Desbloqueando las apps seleccionadas",
    "Apps to unblock": "Apps a desbloquear",
    "Authorize": "Autorizar",
    "Authorized ✓": "Autorizado ✓",
    "Back": "Atrás",
    "Beta testers": "Beta testers",
    "Block": "Bloqueo",
    "Block all except…": "Bloquear todo excepto…",
    "Block app deletion": "Bloquear borrado de apps",
    "Block apps": "Bloquear apps",
    "Block only…": "Bloquear solo…",
    "Blocked by Demora": "Bloqueado por Demora",
    "Blocking is enforced by iOS itself through Screen Time, the same system parental controls use.": "El bloqueo lo aplica el propio iOS a través de Tiempo en Pantalla, el mismo sistema que usan los controles parentales.",
    "Cancel": "Cancelar",
    "Change %@ to %d min/day": "Cambiar %@ a %d min/día",
    "Changes that make things LESS STRICT (raise a limit, remove a block, add a free period) wait out your second delay — usually set longer.": "Los cambios que hacen todo MENOS ESTRICTO (subir un límite, quitar un bloqueo, agregar un periodo libre) esperan tu segunda espera — normalmente más larga.",
    "Changes that make things STRICTER (add a limit, lower minutes, add a schedule) wait out your first delay.": "Los cambios que hacen todo MÁS ESTRICTO (agregar un límite, bajar minutos, agregar un horario) esperan tu primera espera.",
    "Changes you make will appear here with a countdown.": "Los cambios que hagas aparecerán aquí con una cuenta regresiva.",
    "Choose apps": "Elegir apps",
    "Close": "Cerrar",
    "Confirm password": "Confirmar contraseña",
    "Continue": "Continuar",
    "Couldn't load names (check iCloud/network).": "No se pudieron cargar los nombres (revisa iCloud/internet).",
    "Couldn't submit — make sure you're signed into iCloud and try again.": "No se pudo enviar — asegúrate de tener sesión en iCloud e inténtalo de nuevo.",
    "Current delays": "Esperas actuales",
    "Current: %@": "Actual: %@",
    "Daily limit": "Límite diario",
    "Day %d of every month": "Día %d de cada mes",
    "Day of month": "Día del mes",
    "Delay": "Espera",
    "Delay for LOOSER changes": "Espera para cambios MENOS ESTRICTOS",
    "Delay for STRICTER changes": "Espera para cambios MÁS ESTRICTOS",
    "Delays": "Esperas",
    "Difficulty": "Dificultad",
    "Disable math override": "Desactivar anulación por matemáticas",
    "Disable password override": "Desactivar anulación por contraseña",
    "Done": "Listo",
    "Duration": "Duración",
    "During a free period, limits don't block and usage inside the window doesn't count toward them — time used before the window still does.": "Durante un periodo libre, los límites no bloquean y el uso dentro de la ventana no cuenta — el tiempo usado antes sí cuenta.",
    "Easy": "Fácil",
    "Enable math override": "Activar anulación por matemáticas",
    "Enable math override (%@)": "Activar anulación por matemáticas (%@)",
    "Enable password override": "Activar anulación por contraseña",
    "Enable/update password override": "Activar/actualizar anulación por contraseña",
    "End": "Fin",
    "End early…": "Terminar antes…",
    "End session early: %@": "Terminar sesión antes: %@",
    "Ends": "Termina",
    "Enter password": "Ingresar contraseña",
    "Every change you make waits out a delay you chose, counting down in the background. You can always change your rules — just not in a moment of weakness.": "Cada cambio que hagas espera un tiempo que tú elegiste, contando en segundo plano. Siempre puedes cambiar tus reglas — pero no en un momento de debilidad.",
    "Every day": "Todos los días",
    "Everything on the iPhone is blocked during the window except the apps picked here.": "Todo el iPhone se bloquea durante la ventana excepto las apps elegidas aquí.",
    "Free period": "Periodo libre",
    "Today's usage is reported by iOS Screen Time, which can be slow to load or briefly show nothing. If it looks empty, tap the refresh arrow a couple of times.": "El uso de hoy lo reporta Tiempo en Pantalla de iOS, que puede tardar en cargar o mostrarse vacío por un momento. Si se ve vacío, toca la flecha de recarga un par de veces.",
    "Free": "Libre",
    "Free period: %@ (%d min)": "Periodo libre: %@ (%d min)",
    "Free period — nothing is blocked": "Periodo libre — nada está bloqueado",
    "Temporarily lifts everything — no app blocks apply, and usage during the free period doesn't count toward your limits.": "Levanta todo temporalmente — no se aplica ningún bloqueo, y el uso durante el periodo libre no cuenta para tus límites.",
    "Free periods": "Periodos libres",
    "Friction, not passwords": "Fricción, no contraseñas",
    "Get started": "Empezar",
    "Hard": "Difícil",
    "Home": "Inicio",
    "Hours": "Horas",
    "How does it work?": "¿Cómo funciona?",
    "Incorrect password": "Contraseña incorrecta",
    "Keep it appropriate — names are reviewed, and inappropriate ones won't be added.": "Manténlo apropiado — los nombres se revisan y los inapropiados no se agregarán.",
    "Language": "Idioma",
    "Demora needs Screen Time authorization to set app limits and block apps. iOS will ask for your confirmation.": "Demora necesita autorización de Tiempo en Pantalla para poner límites y bloquear apps. iOS te pedirá confirmación.",
    "Demora wouldn't exist without the people who tested it, broke it, and told me about it. Thank you. ❤️": "Demora no existiría sin la gente que lo probó, lo rompió y me lo contó. Gracias. ❤️",
    "Less strict": "Menos estricto",
    "Less-strict delay": "Espera de menos estricto",
    "Limit": "Límite",
    "Limits": "Límites",
    "Limits won't block and usage won't count during this window.": "Los límites no bloquearán y el uso no contará durante esta ventana.",
    "Limits: daily time budgets per app. When the minutes run out, the app is blocked until midnight.": "Límites: presupuestos diarios de tiempo por app. Cuando se acaban los minutos, la app se bloquea hasta medianoche.",
    "Looser changes": "Cambios menos estrictos",
    "Looser changes wait %@": "Los cambios menos estrictos esperan %@",
    "Math override": "Anulación por matemáticas",
    "Math problems": "Problemas de matemáticas",
    "Medium": "Media",
    "Minutes": "Minutos",
    "Mode": "Modo",
    "Monthly schedules can't cross midnight — set the end time after the start time.": "Los horarios mensuales no pueden cruzar la medianoche — pon la hora de fin después de la de inicio.",
    "More strict": "Más estricto",
    "More-strict delay": "Espera de más estricto",
    "Most screen-time apps protect your rules with a password — which you know, so you cave. Demora protects them with time instead.": "La mayoría de las apps de tiempo en pantalla protegen tus reglas con una contraseña — que tú conoces, así que cedes. Demora las protege con tiempo.",
    "Name": "Nombre",
    "Names will appear here soon.": "Los nombres aparecerán aquí pronto.",
    "New free period": "Nuevo periodo libre",
    "New limit": "Nuevo límite",
    "New password": "Nueva contraseña",
    "New schedule": "Nuevo horario",
    "New session": "Nueva sesión",
    "New session…": "Nueva sesión…",
    "No free periods": "Sin periodos libres",
    "No limits yet": "Aún no hay límites",
    "No overrides — delays are absolute": "Sin anulaciones — las esperas son absolutas",
    "No pending changes": "Sin cambios pendientes",
    "No schedules": "Sin horarios",
    "No thanks": "No, gracias",
    "Nothing planned": "Nada planeado",
    "Nth weekday": "N.º día de la semana",
    "OK": "OK",
    "Off": "No",
    "On": "Sí",
    "One-off and unplanned, but still delay-gated. A block session waits %@; an unblock session waits %@. Ending early flips the rule (or use an override).": "Únicas y sin planear, pero igual pasan por esperas. Una sesión de bloqueo espera %@; una de desbloqueo espera %@. Terminarla antes invierte la regla (o usa una anulación).",
    "Only the apps picked here are blocked during the window.": "Solo las apps elegidas aquí se bloquean durante la ventana.",
    "Overrides": "Anulaciones",
    "Overrides enabled": "Anulaciones activadas",
    "Overrides let you skip a pending change's countdown. They're off by default. Adding one later counts as a less-strict change; removing one counts as stricter — both go through delays.": "Las anulaciones te permiten saltarte la cuenta regresiva de un cambio pendiente. Están desactivadas por defecto. Agregar una después cuenta como cambio menos estricto; quitarla cuenta como más estricto — ambas pasan por esperas.",
    "Overrides skip a pending change's countdown. Enabling or weakening one is a less-strict change; disabling or strengthening one is stricter. All edits here go through the matching delay.": "Las anulaciones se saltan la cuenta regresiva de un cambio pendiente. Activar o debilitar una es un cambio menos estricto; desactivarla o reforzarla es más estricto. Todo lo editado aquí pasa por la espera correspondiente.",
    "A change for this setting is already pending. Cancel it on the Home tab first if you want something different.": "Ya hay un cambio pendiente para este ajuste. Cancélalo primero en Inicio si quieres algo diferente.",
    "Already pending": "Ya pendiente",
    "A person you choose approves skipping a countdown — by email code or from their own Demora app. You can also add more later in Settings → Trusted contacts.": "Una persona que elijas aprueba saltarse una cuenta regresiva — con un código por correo o desde su propia app de Demora. También puedes agregar más después en Ajustes → Contactos de confianza.",
    "Add": "Agregar",
    "Message (optional)": "Mensaje (opcional)",
    "Sent along with the request so they know why you're asking.": "Se envía junto con la solicitud para que sepan por qué lo pides.",
    "e.g. why you need this": "p. ej. por qué lo necesitas",
    "%@ — Note: %@": "%@ — Nota: %@",
    "Your request was denied.": "Tu solicitud fue rechazada.",
    "Send a new request…": "Enviar una nueva solicitud…",
    "Cancels this request and lets you pick contacts again.": "Cancela esta solicitud y te deja elegir contactos de nuevo.",
    "Coming soon": "Próximamente",
    "Appearance": "Apariencia",
    "Theme": "Tema",
    "System": "Sistema",
    "Light": "Claro",
    "Dark": "Oscuro",
    "/ de·mo·ra /  noun, Spanish": "/ de·mo·ra /  sustantivo femenino",
    "a delay; the time that passes before something takes effect.": "tardanza; el tiempo que pasa antes de que algo surta efecto.",
    "an iPhone app that protects your screen-time rules with definition 1 instead of a password.": "una app para iPhone que protege tus reglas de tiempo en pantalla con la definición 1 en lugar de una contraseña.",
    "Coming soon — payments aren't available yet.": "Próximamente — los pagos aún no están disponibles.",
    "Password": "Contraseña",
    "Password override": "Anulación por contraseña",
    "Passwords don't match": "Las contraseñas no coinciden",
    "Pay %@": "Pagar %@",
    "Pay %@ to apply this change now": "Paga %@ para aplicar este cambio ahora",
    "Pending change": "Cambio pendiente",
    "Pending changes": "Cambios pendientes",
    "Pending changes show on the Home tab with a live countdown. You can cancel them anytime before they apply.": "Los cambios pendientes aparecen en Inicio con una cuenta regresiva en vivo. Puedes cancelarlos en cualquier momento antes de que se apliquen.",
    "Plan %@: %@ (%@)": "Planear %@: %@ (%@)",
    "Plan a window": "Planear una ventana",
    "Plan a window…": "Planear una ventana…",
    "Plan ahead for specific dates — a trip, a weekend, an exam. Doesn't repeat. Planning a block is stricter; planning a free period is less strict.": "Planea con anticipación para fechas específicas — un viaje, un fin de semana, un examen. No se repite. Planear un bloqueo es más estricto; planear un periodo libre es menos estricto.",
    "Planned (one-off)": "Planeado (una vez)",
    "Planned window": "Ventana planeada",
    "Purchasing…": "Comprando…",
    "Queue change": "Programar cambio",
    "Queue: turn off": "Programar: desactivar",
    "Queue: turn on": "Programar: activar",
    "Recurring schedules": "Horarios recurrentes",
    "Remove free period: %@": "Quitar periodo libre: %@",
    "Remove limit: %@": "Quitar límite: %@",
    "Remove planned window: %@": "Quitar ventana planeada: %@",
    "Remove schedule: %@": "Quitar horario: %@",
    "Remove this limit": "Quitar este límite",
    "Remove…": "Quitar…",
    "Repeating windows: every day, chosen weekdays, or monthly patterns. Adding waits %@; removing waits %@.": "Ventanas que se repiten: todos los días, días elegidos de la semana o patrones mensuales. Agregar espera %@; quitar espera %@.",
    "Repeats": "Se repite",
    "Schedule": "Horario",
    "Schedules": "Horarios",
    "Schedules: recurring or one-off windows that block chosen apps — or everything except a chosen few. Plus free periods where time doesn't count.": "Horarios: ventanas recurrentes o únicas que bloquean apps elegidas — o todo excepto unas pocas. Además, periodos libres donde el tiempo no cuenta.",
    "Screen Time access": "Acceso a Tiempo en Pantalla",
    "Sessions": "Sesiones",
    "Set 'less strict' delay to %@": "Cambiar espera de 'menos estricto' a %@",
    "Set 'more strict' delay to %@": "Cambiar espera de 'más estricto' a %@",
    "Settings": "Ajustes",
    "Setup": "Configuración",
    "Simulate payment (beta)": "Simular pago (beta)",
    "Skip the wait": "Saltarse la espera",
    "Solve %d math problems (%@)": "Resolver %d problemas de matemáticas (%@)",
    "Solve math problems": "Resolver problemas de matemáticas",
    "Start": "Inicio",
    "Start using Demora": "Empezar a usar Demora",
    "Starts": "Empieza",
    "Stricter changes": "Cambios más estrictos",
    "Stricter changes wait %@": "Los cambios más estrictos esperan %@",
    "Submit": "Enviar",
    "Temporarily lifts limits, schedules, and block sessions for the chosen apps.": "Levanta temporalmente límites, horarios y sesiones de bloqueo para las apps elegidas.",
    "Thanks for testing Demora!": "¡Gracias por probar Demora!",
    "This app is blocked right now — by a limit, a schedule, or a session. Changing your rules takes a delay; open Demora to queue a change.": "Esta app está bloqueada ahora — por un límite, un horario o una sesión. Cambiar tus reglas toma una espera; abre Demora para programar un cambio.",
    "If it should already be unblocked, iOS is sometimes slow to apply a background change — open Demora for an immediate unblock.": "Si ya debería estar desbloqueada, iOS a veces tarda en aplicar un cambio en segundo plano — abre Demora para desbloquearla de inmediato.",
    "Two delays rule everything": "Dos esperas lo gobiernan todo",
    "Type": "Tipo",
    "Unblock": "Desbloqueo",
    "Unblock apps": "Desbloquear apps",
    "Unlock": "Desbloquear",
    "Wait this long before any change that loosens your rules takes effect. Usually set longer than the first.": "Espera este tiempo antes de que cualquier cambio que afloje tus reglas surta efecto. Normalmente se pone más larga que la primera.",
    "Wait this long before any change that tightens your rules takes effect.": "Espera este tiempo antes de que cualquier cambio que endurezca tus reglas surta efecto.",
    "Want your name in the app's beta-tester thanks page? Pick whatever you'd like to be called.": "¿Quieres tu nombre en la página de agradecimiento a beta testers? Elige cómo quieres que te llamen.",
    "Weekday": "Día de la semana",
    "Weekdays": "Días de la semana",
    "What can it do?": "¿Qué puede hacer?",
    "What's in the box": "Qué incluye",
    "When": "Cuándo",
    "When on, deleting ANY app from this iPhone is blocked — including Demora itself, so blocks can't be bypassed by uninstalling.": "Cuando está activado, borrar CUALQUIER app de este iPhone queda bloqueado — incluido Demora, para que los bloqueos no se puedan evadir desinstalando.",
    "Which one": "Cuál",
    "Window": "Ventana",
    "Wrong — new problem": "Incorrecto — nuevo problema",
    "You're in! Your name will appear in the beta testers page once it's approved.": "¡Listo! Tu nombre aparecerá en la página de beta testers cuando se apruebe.",
    "You're set": "Todo listo",
    "Your name is in — it'll show up once approved.": "Tu nombre ya está — aparecerá cuando se apruebe.",
    "Your name or nickname": "Tu nombre o apodo",
    "e.g. Airport, weekend trip": "p. ej. Aeropuerto, viaje de finde",
    "e.g. Bedtime": "p. ej. Hora de dormir",
    "e.g. Deep work": "p. ej. Trabajo profundo",
    "e.g. Instagram": "p. ej. Instagram",
    "e.g. Lunch break": "p. ej. Hora de comer",
    "free period": "periodo libre",
    "limit": "límite",
    "now": "ahora",
    "planned window": "ventana planeada",
    "schedule": "horario",
    "session": "sesión",

    // Prevent disabling, walkthrough replay — added after the
    // 2026-07 update (App Attest, ContactCrypto, LatchReport extension).
    "A passcode is saved. Open the guide below to view it.": "Hay una contraseña guardada. Abre la guía de abajo para verla.",
    "Access requested. It unlocks after your less-strict delay — track it on the Home tab, where you can also use an override to skip the wait.": "Acceso solicitado. Se desbloquea después de tu espera menos estricta — síguelo en la pestaña de Inicio, donde también puedes usar una anulación para saltarte la espera.",
    "Can't reach this contact right now — they may have removed Demora or signed out. They won't be able to approve until they're back.": "No se puede contactar a esta persona ahora mismo — puede que haya quitado Demora o cerrado sesión. No podrá aprobar hasta que vuelva.",
    "Couldn't start the walkthrough": "No se pudo iniciar el recorrido",
    "Bug tracker": "Registro de errores",
    "Demora can't stop you from turning off its Screen Time access in iOS Settings — but a friend can. If Screen Time itself is locked with someone else's passcode, iOS blocks any change to Demora's access, while Demora keeps doing all the blocking.": "Demora no puede impedir que desactives su acceso a Tiempo en Pantalla desde Ajustes de iOS — pero un amigo sí puede. Si Tiempo en Pantalla está bloqueado con la contraseña de otra persona, iOS bloquea cualquier cambio al acceso de Demora, mientras Demora sigue haciendo todo el bloqueo.",
    "Demora couldn't safely back up your current setup, so the replay was cancelled to protect your limits. Nothing was changed. Please try again in a moment.": "Demora no pudo respaldar de forma segura tu configuración actual, así que el recorrido se canceló para proteger tus límites. No se cambió nada. Inténtalo de nuevo en un momento.",
    "Done. Now you can't disable Demora's access — or change the passcode — without your friend. To undo it later, your friend enters the passcode and turns it off.": "Listo. Ahora no puedes desactivar el acceso de Demora — ni cambiar la contraseña — sin tu amigo. Para deshacerlo después, tu amigo ingresa la contraseña y lo desactiva.",
    "Email limit": "Límite de correo",
    "Emoji": "Emoji",
    "Friend: save the passcode here so it isn't lost. It's only shown from this page, which is behind your delay.": "Amigo: guarda la contraseña aquí para que no se pierda. Solo se muestra desde esta página, que está detrás de tu espera.",
    "Hand your phone to your friend. Have THEM enter a 4-digit passcode you don't see — don't watch.": "Dale tu teléfono a tu amigo. Que ÉL o ELLA ingrese una contraseña de 4 dígitos que tú no veas — no mires.",
    "Heads up: on your iOS version, a limit only counts screen time from the moment you add it — time you already spent earlier today isn't included. Update to iOS 17.4 or later for exact daily counting.": "Aviso: en tu versión de iOS, un límite solo cuenta el tiempo de pantalla desde el momento en que lo agregas — el tiempo que ya usaste antes hoy no se incluye. Actualiza a iOS 17.4 o posterior para un conteo diario exacto.",
    "Make Demora impossible to disable": "Haz que Demora sea imposible de desactivar",
    "Onboarding demo — you can skip below. It's always available again in Settings → Help.": "Demo de bienvenida — puedes saltártela abajo. Siempre está disponible de nuevo en Ajustes → Ayuda.",
    "One more safeguard": "Una protección más",
    "Open Settings → Screen Time on this iPhone. If it's off, turn it on.": "Abre Ajustes → Tiempo en Pantalla en este iPhone. Si está desactivado, actívalo.",
    "Open the guide": "Abrir la guía",
    "Opening this is delayed on purpose — so you can't impulsively look up how to undo your own lock.": "Abrir esto tiene una espera a propósito — para que no puedas buscar impulsivamente cómo deshacer tu propio bloqueo.",
    "Passcode": "Contraseña",
    "Pick someone you trust and can reach. If the passcode and its recovery Apple ID are both lost, removing it may require erasing the device.": "Elige a alguien de confianza a quien puedas contactar. Si se pierden tanto la contraseña como el Apple ID de recuperación, quitarlo puede requerir borrar el dispositivo.",
    "Prevent disabling": "Evitar desactivación",
    "Protection": "Protección",
    "Replay walkthrough": "Repetir el recorrido",
    "Request access": "Solicitar acceso",
    "Save": "Guardar",
    "Saved passcode: %@": "Contraseña guardada: %@",
    "Saved ✓": "Guardado ✓",
    "Show me how": "Muéstrame cómo",
    "Skip and set up manually": "Omitir y configurar manualmente",
    "Skip walkthrough": "Saltar el recorrido",
    "Skip — set up manually": "Omitir — configurar manualmente",
    "Store the Screen Time passcode": "Guardar la contraseña de Tiempo en Pantalla",
    "Take photo": "Tomar foto",
    "Takes about 2 minutes, and you need a second person physically with you.": "Toma unos 2 minutos, y necesitas tener a otra persona físicamente contigo.",
    "Tap “Lock Screen Time Settings” (or “Use Screen Time Passcode”).": "Toca “Bloquear ajustes de Tiempo en Pantalla” (o “Usar contraseña de Tiempo en Pantalla”).",
    "Thank you. ❤️": "Gracias. ❤️",
    "That's okay. Without Screen Time access Demora can't block apps, but you can continue and turn it on later.": "No pasa nada. Sin acceso a Tiempo en Pantalla, Demora no puede bloquear apps, pero puedes continuar y activarlo más tarde.",
    "That's the whole loop. Your real limits, schedules, and settings are still here — nothing changed.": "Ese es todo el recorrido. Tus límites, horarios y ajustes reales siguen aquí — nada cambió.",
    "There's a way to make Demora impossible to turn off — with a friend's help. It takes about 2 minutes and needs a second person physically with you.": "Hay una forma de hacer que Demora sea imposible de desactivar — con la ayuda de un amigo. Toma unos 2 minutos y necesitas tener a otra persona físicamente contigo.",
    "They call themselves “%@”.": "Se hace llamar “%@”.",
    "This guide is behind your less-strict delay: request it, wait out the delay, and you get one open. After you view it, it locks again.": "Esta guía está detrás de tu espera menos estricta: solicítala, espera el tiempo y obtienes un acceso único. Después de verla, se bloquea de nuevo.",
    "Unavailable": "No disponible",
    "Unlock the “Prevent disabling” guide": "Desbloquear la guía “Evitar desactivación”",
    "Use photo": "Usar foto",
    "When asked for Screen Time Passcode Recovery, your friend signs in with THEIR OWN Apple ID — not yours. That's what stops you from resetting the passcode on your own.": "Cuando se pida la recuperación de la contraseña de Tiempo en Pantalla, tu amigo inicia sesión con SU PROPIO Apple ID — no el tuyo. Eso es lo que evita que restablezcas la contraseña tú mismo.",
    "You can always find this later under Help — but there it's behind a delay.": "Siempre puedes encontrar esto después en Ayuda — pero ahí está detrás de una espera.",
    "You can change these any time under General blocking. Each change then goes through your delays.": "Puedes cambiar esto en cualquier momento en Bloqueo general. Cada cambio pasa por tus esperas.",
    "Your one-time access is ready.": "Tu acceso único está listo.",
    "lock it with a friend": "bloquéalo con un amigo",
    "your setup stays safe": "tu configuración se mantiene segura",
    "—": "—",
]
