//
//  Localization+French.swift
//  Full in-app localization table. Missing keys fall back to English.
//

import Foundation

let frenchStrings: [String: String] = [
    "Demora now speaks more languages": "Demora parle désormais plus de langues",
    "We've added support for German, French, Portuguese, Polish, Turkish, and Hindi.": "Nous avons ajouté la prise en charge de l’allemand, du français, du portugais, du polonais, du turc et de l’hindi.",
    "Choose your language here. You can change it anytime under Settings → Appearance → Language.": "Choisissez votre langue ici. Vous pourrez la modifier à tout moment dans Paramètres → Apparence → Langue.",
    "Apply language": "Appliquer la langue",
    "Translation in beta": "Traduction en version bêta",
    "This language is in beta. Please report any mistranslations or unclear phrasing to hello@getdemora.app.": "Cette traduction est en version bêta. Merci de signaler toute erreur de traduction ou formulation peu claire à hello@getdemora.app.",
    "Dismiss": "Fermer",
    "Recheck blocked limits": "Revérifier les limites bloquées",
    "Takes around 30 seconds": "Prend environ 30 secondes",
    "Recheck keeps current blocks in place while iOS verifies today's usage. Limits iOS confirms stay blocked.": "La vérification maintient les blocages actuels pendant qu’iOS contrôle l’utilisation du jour. Les limites confirmées par iOS restent bloquées.",
    "Limit recheck": "Vérification des limites",
    "Released %d stale limit blocks. %d limits were freshly confirmed by iOS.": "%d blocages de limite obsolètes ont été levés. %d limites ont été confirmées à nouveau par iOS.",
    "iOS freshly confirmed all current limit blocks.": "iOS a confirmé à nouveau tous les blocages de limite actuels.",
    "No blocked limits need to be rechecked.": "Aucune limite bloquée ne doit être revérifiée.",
    "Wait until the active free period ends, then recheck again.": "Attendez la fin de la période libre active, puis réessayez.",
    "You can recheck again in %@.": "Nouvelle vérification possible dans %@.",
    "The recheck was interrupted. No blocks were changed.": "La vérification a été interrompue. Aucun blocage n’a été modifié.",
    "iOS couldn't complete the verification safely. No blocks were changed. Try again later.": "iOS n’a pas pu terminer la vérification en toute sécurité. Aucun blocage n’a été modifié. Réessayez plus tard.",
    "Safe limit rechecking requires iOS 17.4 or later. No blocks were changed.": "La vérification sécurisée des limites nécessite iOS 17.4 ou une version ultérieure. Aucun blocage n’a été modifié.",
    "This is a demo — nothing you do here is saved or actually blocked.": "C'est une démo — rien que vous ne faites ici n'est sauvé ou en fait bloqué.",
    "Limitations": "Limites",
    "iOS reporting notes": "Notes de rapport iOS",
    "Today's usage reporting": "Les rapports d'utilisation d'aujourd'hui",
    "Daily counting on older iOS": "Compte quotidien sur iOS plus ancien",
    "%@ #%d of every month": "%@ #%d de chaque mois",
    "%d / %d min": "%d / %d min",
    "blocked until midnight": "bloqué jusqu'à minuit",
    "now & next": "maintenant & suivant",
    "Today's usage": "Utilisation actuelle",
    "Manage": "Gérer",
    "Week starts": "Début de la semaine",
    "Monday": "Lundi",
    "Sunday": "Dimanche",
    "Calendar": "Calendrier",
    "week / month": "semaine / mois",
    "month": "mois",
    "Solve math problems to skip a countdown.": "Résoudre les problèmes de maths pour sauter un compte à rebours.",
    "Enter a password to skip a countdown.": "Saisissez un mot de passe pour sauter un compte à rebours.",
    "How schedules work": "Comment les horaires fonctionnent",
    "Help": "Aide",
    "guide, contact, more": "guide, contact, plus",
    "thank you": "Je vous remercie.",
    "Guide": "guide",
    "Contact": "Contact",
    "About": "À propos",
    "how each part works": "comment chaque partie fonctionne",
    "bug, feature, help": "bug, fonctionnalité, aide",
    "links": "liens",
    "Report a bug": "Signaler un bug",
    "Request a feature": "Demander une fonctionnalité",
    "General help": "Aide générale",
    "Website": "Site Web",
    "Instagram": "Instagram",
    "What Demora is": "Qu'est-ce que Demora",
    "Demora protects your screen-time rules with a delay instead of a password. Every change you make waits out a countdown before it takes effect, so you can always change your mind — just not instantly, in a moment of weakness. Blocking itself is enforced by iOS through Screen Time.": "Demora protège vos règles de temps d'écran avec un retard au lieu d'un mot de passe. Chaque changement que vous faites attend un compte à rebours avant qu'il ne prenne effet, de sorte que vous pouvez toujours changer d'avis — juste pas instantanément, dans un moment de faiblesse.",
    "There are two delays. The more-strict delay gates changes that tighten your rules (adding a limit, lowering minutes, adding a schedule). The less-strict delay gates changes that loosen them (raising a limit, removing a block, adding a free period) — usually set longer. Pending changes show on the Home tab with a live countdown and can be cancelled before they apply.": "Les portes de retard plus strictes modifient vos règles (en ajoutant une limite, des minutes de baisse, en ajoutant un horaire).Les portes de retard moins strictes changent qui les délient (en augmentant une limite, en supprimant un bloc, en ajoutant une période libre) – généralement plus longtemps.",
    "A limit is a daily time budget for the apps or categories you choose. When the minutes run out, those apps are blocked until midnight. The Limits tab shows today's usage per limit, and tapping a limit shows exactly which apps it covers.": "Une limite est un budget de temps quotidien pour les applications ou catégories que vous choisissez. Lorsque les minutes sont épuisées, ces applications sont bloquées jusqu'à minuit. L'onglet Limites affiche l'utilisation d'aujourd'hui par limite, et tapotant une limite indique exactement quelles applications il couvre.",
    "Schedules block apps on a repeating or one-off basis. Recurring schedules repeat daily, on chosen weekdays, or monthly. Planned windows are one-offs for specific dates. Sessions are immediate timed blocks or unblocks. Free periods are windows where limits don't block and usage doesn't count.": "Les horaires bloquent les applications sur une base répétitive ou ponctuelle. Les horaires récurrents répètent quotidiennement, les jours de semaine choisis ou mensuellement. Les fenêtres prévues sont uniques pour des dates précises. Les sessions sont des blocs à temps immédiat ou déblocage. Les périodes gratuites sont des fenêtres où les limites ne bloquent pas et l'utilisation ne compte pas.",
    "A trusted contact can approve skipping a countdown — by email code or from their own Demora app. People you add must accept before they can approve, and you can revoke them at any time.": "Un contact de confiance peut approuver le saut d'un compte à rebours — par e-mail ou de leur propre application Demora. Les personnes que vous ajoutez doivent accepter avant qu'ils puissent approuver, et vous pouvez les révoquer à tout moment.",
    "App deletion lock": "Verrouillage de suppression de l'application",
    "the core idea": "l'idée fondamentale",
    "the two countdowns": "les deux comptes à rebours",
    "daily app budgets": "budgets quotidiens de l'application",
    "recurring, planned, sessions": "sessions périodiques, prévues",
    "escape hatches": "trappes d'évacuation",
    "approval by a person": "approbation par une personne",
    "can't uninstall to bypass": "ne peut pas désinstaller pour contourner",
    "Most screen-time apps lock your rules behind a password. Because you know the password, you can undo your own rules the moment you feel the urge — so they rarely stick.\n\nDemora protects your rules with time instead. Every change waits out a countdown you set in advance before it takes effect. You stay in full control of your rules, but you can't change them in a single impulsive moment. The blocking itself is enforced by iOS through Screen Time — the same system parental controls use — so it can't be quietly bypassed.": "La plupart des applications à temps d'écran verrouillent vos règles derrière un mot de passe. Parce que vous connaissez le mot de passe, vous pouvez annuler vos propres règles dès que vous ressentez l'envie — donc elles restent rarement. Demora protège vos règles avec le temps. Chaque changement attend un compte à rebours que vous avez établi à l'avance avant qu'il ne prenne effet. Vous restez en plein contrôle de vos règles, mais vous ne pouvez pas les changer en un seul moment impulsif. Le blocage lui-même est imposé par iOS via Screen Time — le même système de contrôle parental utilisation — afin qu'il ne puisse pas être contourné tranquillement.",
    "Demora has two delays. The more-strict delay covers any change that tightens your rules: adding a limit, lowering its minutes, adding a schedule, or turning on the deletion lock. The less-strict delay covers changes that loosen them: raising a limit, removing a block, adding a free period, or disabling an override. The less-strict delay is usually set longer, since loosening is where temptation lives.\n\nA change doesn't apply right away — it becomes a pending change with a live countdown on the Home tab. You can cancel it any time before it lands, and when the countdown reaches zero it applies on its own, even if the app is closed.": "Demora — Le délai plus strict couvre tout changement qui resserre vos règles : ajouter une limite, abaisser ses minutes, ajouter un calendrier ou activer le verrou de suppression. Le délai moins strict couvre les changements qui les délient : élever une limite, supprimer un bloc, ajouter une période libre, ou désactiver une dérogation. Le délai moins strict est généralement plus long, puisque le relâchement est là où la tentation vit. Un changement ne s'applique pas immédiatement – il devient un changement en suspens avec un compte à rebours en direct sur l'onglet Maison. Vous pouvez l'annuler à tout moment avant qu'il ne débarque, et lorsque le compte à rebours atteint zéro, il s'applique à lui seul, même si l'application est fermée.",
    "A limit is a daily time budget for a set of apps or whole categories. When the minutes run out, those apps are blocked for the rest of the day and unlock again at midnight.\n\nThe Limits tab shows today's real usage for each limit, read straight from Screen Time, and tapping a limit reveals exactly which apps and categories it covers. Because usage is measured by iOS, time spent before you created the limit still counts toward it that day. Raising or removing a limit is a less-strict change; adding one or lowering its minutes is stricter.": "Une limite est un budget quotidien pour un ensemble d'applications ou de catégories entières. Lorsque les minutes sont épuisées, ces applications sont bloquées pour le reste de la journée et déverrouillent à nouveau à minuit. L'onglet Limites montre l'utilisation réelle d'aujourd'hui pour chaque limite, lire directement à partir de l'heure d'écran, et taper une limite révèle exactement quelles applications et catégories il couvre. Parce que l'utilisation est mesurée par iOS, le temps passé avant que vous n'ayez créé la limite compte encore vers elle ce jour-là.",
    "Schedules block apps by time rather than by budget, in a few shapes. Recurring schedules repeat — every day, on chosen weekdays, or on a monthly pattern. Planned windows are one-offs for a specific date, like a trip or an exam. Sessions are immediate, timed blocks or unblocks you start right now. Free periods are windows where limits don't block and usage doesn't count toward them.\n\nEach blocking schedule either blocks the apps you pick, or blocks everything except the apps you pick. When rules overlap, the most specific one wins: a session beats a planned window, which beats a recurring schedule, and within the same kind the one added most recently takes priority.": "Les horaires de travail se répètent — tous les jours, les jours de semaine choisis ou sur un modèle mensuel. Les fenêtres prévues sont uniques pour une date précise, comme un voyage ou un examen. Les sessions sont immédiates, chronométrées ou déblocées que vous commencez dès maintenant. Les périodes gratuites sont des fenêtres où les limites ne bloquent pas et l'utilisation ne compte pas vers elles. Chaque calendrier de blocage bloque les applications que vous choisissez, ou bloque tout sauf les applications que vous choisissez. Lorsque les règles se chevauchent, la plus spécifique gagne : une session bat une fenêtre planifiée, qui bat contre un horaire récurrent, et dans le même genre que celle ajoutée la plus récente prend la priorité.",
    "Overrides are optional escape hatches that let you skip a pending change's countdown. There are three: solve a set of math problems, enter a password, or ask a trusted contact to approve. They're all off by default, so out of the box your delays are absolute.\n\nTurning an override on, or making it easier, counts as a less-strict change and waits out that delay. Turning one off, or making it harder, is stricter — so you can't instantly weaken your own safety net.": "Les dépassements sont des trappes d'évacuation optionnelles qui vous permettent de sauter le compte à rebours d'un changement en attente. Il y en a trois : résoudre un ensemble de problèmes mathématiques, entrer un mot de passe ou demander à un contact de confiance d'approuver. Ils sont tous désactivés par défaut, donc hors de la boîte vos retards sont absolus. Allumer une surcharge, ou la rendre plus facile, compte comme un changement moins strict et attend ce retard.",
    "A trusted contact is a person who can approve skipping a countdown for you. They can approve by entering a short code sent to their email, or directly from their own copy of Demora.\n\nAnyone you add has to accept the request before they can approve anything, so no one is involved without their knowledge. You can revoke a contact at any time, and they can step down on their side too. Adding the override is a less-strict change; removing it is stricter.": "Un contact de confiance est une personne qui peut approuver le saut d'un compte à rebours pour vous. Ils peuvent approuver en entrant un court code envoyé à leur email, ou directement de leur propre copie de Demora. Quiconque que vous ajoutez doit accepter la demande avant qu'ils puissent approuver quoi que ce soit, donc personne n'est impliqué à leur insu. Vous pouvez révoquer un contact à tout moment, et ils peuvent aussi descendre de leur côté. Ajouter la priorité est un changement moins strict; supprimer il est plus strict.",
    "When the deletion lock is on, deleting any app from this iPhone is blocked — including Demora itself. That closes the most obvious loophole: uninstalling the app to wipe your rules.\n\nBecause turning the lock off makes things easier to bypass, it counts as a less-strict change and waits out that delay before it takes effect.": "Lorsque le verrou de suppression est activé, supprimer une application de cet iPhone est bloqué — y compris Demora lui-même. Cela ferme la faille la plus évidente: désinstaller l'application pour effacer vos règles. Parce que l'arrêt du verrou facilite les choses de contournement, il compte comme un changement moins strict et attend ce retard avant qu'il ne prenne effet.",
    "When on, deleting any app from this iPhone is blocked — including Demora itself — so your rules can't be bypassed by uninstalling. Turning it off goes through the less-strict delay.": "Lorsque vous activez, supprimer une application de cet iPhone est bloqué — y compris Demora lui-même — de sorte que vos règles ne peuvent pas être contournées par désinstallation.",
    "Blocks": "Blocs",
    "New recurring": "Nouveau périodique",
    "Week": "Semaine",
    "Month": "Mois",
    "Nothing on this day.": "Rien en ce jour.",
    "When things overlap": "Quand les choses se chevauchent",
    "One-off, right now: block or unblock chosen apps for a set number of minutes. Still delay-gated to start; ending early flips the rule.": "One-off, en ce moment : bloquez ou débloquez les applications choisies pour un nombre de minutes défini. Toujours retard-dépôt pour commencer; fin de la première fois retourne la règle.",
    "One-off windows for specific dates — a trip, an exam. Block, allow-all-except, or a free period. Doesn't repeat.": "Fenêtres uniques pour des dates précises — un voyage, un examen. Bloquez, autorisez-tout sauf, ou une période libre. Ne répète pas.",
    "Windows that repeat — daily, by weekday, or monthly. Each is either a block or a free period.": "Les fenêtres qui répètent — tous les jours, par semaine, ou par mois. Chacun est soit un bloc ou une période libre.",
    "Limits don't block during the window, and time used inside it doesn't count against your daily budgets.": "Les limites ne bloquent pas pendant la fenêtre, et le temps utilisé à l'intérieur ne compte pas en fonction de vos budgets quotidiens.",
    "Priority: a session beats a planned window, which beats a recurring schedule. Within the same kind, the one you added most recently wins.": "Priorité : une session bat une fenêtre planifiée, qui bat un horaire récurrent. Dans le même genre, celle que vous avez ajoutée le plus récemment gagne.",
    "today %@–%@": "aujourd'hui %@–%@",
    "Current passcode": "Code d'accès actuel",
    "New passcode": "Nouveau code d'accès",
    "Confirm new passcode": "Confirmer le nouveau code d'accès",
    "Change passcode": "Modifier le code d'accès",
    "Change passcode now": "Changer le code d'accès maintenant",
    "Enter your current passcode to change it instantly. Forgot it? Reset below — that one waits out your delay.": "Entrez votre code d'accès actuel pour le modifier instantanément. Vous avez oublié? Réinitialisez ci-dessous — celui-ci attend votre retard.",
    "Forgot it?": "Vous l'avez oublié ?",
    "Reset passcode (forgot)": "Réinitialiser le code d'accès (forgot)",
    "Turn off password override": "Éteignez la commande de mot de passe",
    "Wrong passcode.": "Mauvais code.",
    "Select": "Sélectionner",
    "Cancel %d": "Annuler %d",
    "Apply %d now": "Appliquer %d maintenant",
    "%d changes": "Changements de %d",
    "Denied": "Refusé",
    "My info": "Mes infos",
    "view": "vue",
    "Nobody yet": "Personne pour l'instant.",
    "language, theme, case": "langue, thème, cas",
    "%@ · %@": "%@ · %@",
    "none on": "Aucune",
    "%d on": "%d sur",
    "Nothing scheduled right now.": "Rien de prévu pour le moment.",
    "Active now": "Active maintenant",
    "Coming up": "Ça vient.",
    "until %@": "jusqu'à %@",
    "today at %@": "aujourd'hui à %@",
    "Planned": "Planifié",
    "Recurring": "Récurrent",
    "none": "aucune",
    "No active sessions": "Pas de sessions actives",
    "%d · %d active": "%d · %d actif",
    "%d total": "Total %d",
    "Your name": "Votre nom",
    "Your name (optional)": "Votre nom (facultatif)",
    "Shown to people you ask to approve, so they know it's you.": "Il s'est montré aux gens que vous demandez d'approuver, donc ils savent que c'est vous.",
    "People you approve for": "Les gens que tu approuves",
    "These people have you as a trusted contact. Removing yourself tells them and stops their requests.": "Ces personnes vous ont comme un contact de confiance. En vous enlevant vous-même leur dit et arrête leurs demandes.",
    "Remove": "Supprimer",
    "code %@": "Code %@",
    "Demora user %@": "Utilisateur Demora %@",
    "%@ removed their permission to be your trusted contact.": "%@ a supprimé leur autorisation d'être votre contact de confiance.",
    "Trusted contact removed": "Contact fiable supprimé",
    "A trusted contact": "Un contact de confiance",
    "That's your own code — add someone else.": "C'est votre propre code — ajoutez quelqu'un d'autre.",
    "You already have this person as a contact.": "Vous avez déjà cette personne comme contact.",
    "Request history": "Demander l'historique",
    "Blocked users": "Utilisateurs bloqués",
    "No requests yet.": "Pas encore de demande.",
    "No blocked users.": "Aucun utilisateur bloqué.",
    "Blocked": "Bloqué",
    "Accepted": "Acceptée",
    "Declined": "Déclinée",
    "Requested": "Demande",
    "Accept": "Accepter",
    "Decline": "Baisse",
    "Active": "Activité",
    "Pending": "En attente",
    "Contact requests": "Demandes de contact",
    "Pending — hasn't accepted yet": "En attente — n'a pas encore accepté",
    "Waiting for them to accept in their Demora app.": "En attendant qu'ils acceptent dans leur application Demora.",
    "A trusted contact can let you skip a pending change's countdown — by emailing you a one-time code, or, if they use Demora, by approving from their own app.": "Un contact de confiance peut vous permettre de sauter le compte à rebours d'un changement en attente — en vous envoyant un courriel à un code unique, ou, s'ils utilisent Demora, en approuvant de leur propre application.",
    "Share this code so another Demora user can add you. You get a request to accept before it's active.": "Partagez ce code afin qu'un autre utilisateur Demora puisse vous ajouter. Vous obtenez une demande à accepter avant qu'il ne soit actif.",
    "A Demora user (code %@) wants to add you as their trusted contact.": "Un utilisateur Demora (code %@) veut vous ajouter comme leur contact de confiance.",
    "%@ (code %@) wants to add you as their trusted contact.": "%@ (code %@) veut vous ajouter comme leur contact de confiance.",
    "If you accept, they can ask you to approve skipping their delays.": "Si vous acceptez, ils peuvent vous demander d'approuver de sauter leurs retards.",
    "Email contacts work as soon as you add them. Demora-user contacts must accept first. Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Les contacts par e-mail fonctionnent dès que vous les ajoutez. Les contacts Demora-utilisateur doivent d'abord accepter. L'ajout d'un contact est un changement moins strict; l'élimination d'un contact est plus stricte — les deux subissent des retards.",
    "Ask them for the code in their Demora settings. They'll get a request to accept before they can approve for you.": "Demandez-leur le code dans leurs paramètres Demora. Ils auront une demande à accepter avant de pouvoir vous approuver.",
    "change": "changement",
    "Text case": "Casse du texte",
    "lowercase": "minuscule",
    "Regular": "Régulière",
    "6-digit code": "Code à 6 chiffres",
    "Add contact": "Ajouter un contact",
    "Add contact…": "Ajouter un contact...",
    "Add trusted contact: %@": "Ajouter un contact fiable: %@",
    "Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "L'ajout d'un contact est un changement moins strict; l'élimination d'un contact est plus stricte — les deux subissent des retards.",
    "Any one approval unlocks the change.": "Toute approbation débloque la modification.",
    "Approval requests": "Demandes d'agrément",
    "Approve": "Approuver",
    "Ask a contact": "Demandez un contact",
    "Ask a trusted contact": "Demandez un contact de confiance",
    "Ask them for the code shown in their Demora settings.": "Demandez-leur le code affiché dans leurs paramètres Demora.",
    "Checking…": "Contrôle...",
    "Checks automatically every few seconds. The request expires after 1 hour.": "Contrôle automatiquement toutes les quelques secondes. La demande expire après 1 heure.",
    "Contacts": "Contacts",
    "approvers, blocked": "les approbations, bloquées",
    "Couldn't send the request — check your connection and try again.": "Impossible d'envoyer la demande — vérifiez votre connexion et essayez à nouveau.",
    "Too many requests to this contact right now. Try again later.": "Trop de demandes à ce contact en ce moment. Essayez encore plus tard.",
    "You've used all of today's approval emails. Try again tomorrow.": "Vous avez utilisé tous les courriels d'approbation d'aujourd'hui.",
    "General blocking": "Blocage général",
    "deletion, websites": "suppression, sites Web",
    "Block adult websites": "Bloquer les sites web pour adultes",
    "Allow adult websites": "Permettre aux sites web pour adultes",
    "Uses Apple's built-in filter to limit adult websites in Safari and other apps.": "Utilise le filtre intégré d'Apple pour limiter les sites web adultes dans Safari et d'autres applications.",
    "Website blocker": "Bloceur de site Web",
    "Block website: %@": "Site web bloc: %@",
    "Unblock website: %@": "Débloquer le site web: %@",
    "e.g. reddit.com": "Par exemple reddit.com",
    "Queue: remove": "Enquêté : supprimer",
    "Block specific websites by typing their domain — no need for Apple's site picker, which often comes up empty. Note: blocking sites also turns on Apple's adult-content filter. Adding a site is gated by your delays; removing one waits the longer delay.": "Bloquez des sites web spécifiques en tapant leur domaine — pas besoin de se procurer le site d'Apple, qui arrive souvent vide. Remarque: les sites de blocage s'allument également sur le filtre à contenu adulte d'Apple. L'ajout d'un site est bloqué par vos retards; le retrait d'un site attend le délai plus long.",
    "Blocked all day": "Bloqué toute la journée",
    "Adult websites": "Sites web pour adultes",
    "%d sites": "Sites %d",
    "Blocked sites": "Sites bloqués",
    "Stop apps from being deleted, limit adult websites, or block specific sites by domain. Every change here goes through your delays.": "Arrêtez les applications d'être supprimées, limitez les sites web adultes, ou bloquez des sites spécifiques par domaine. Chaque changement ici passe par vos retards.",
    "0 minutes — this app stays blocked all day, every day.": "0 minutes — cette application reste bloquée toute la journée, tous les jours.",
    "Approval emails are at capacity right now. Try again later, or use a Demora contact.": "Les e-mails d'approbation sont à capacité en ce moment. Essayez à nouveau plus tard, ou utilisez un contact Demora.",
    "You've sent today": "Vous avez envoyé aujourd'hui.",
    "All users · today": "Tous les utilisateurs · aujourd'hui",
    "All users · this month": "Tous les utilisateurs · ce mois",
    "Email approvals": "Approbations par courriel",
    "Email contacts have a daily send limit; Demora-user contacts don't.": "Les contacts par courriel ont une limite d'envoi quotidienne; les contacts Demora-utilisateur ne le font pas.",
    "one-time, forever": "une fois, pour toujours",
    "active": "actif",
    "Deny": "Refuser",
    "Disable trusted-contact override": "Désactiver la fonction de contact de confiance",
    "Email": "Courriel",
    "Email address": "Adresse électronique",
    "Email code": "Code électronique",
    "Email contacts aren't available yet in this build.": "Les contacts de courriel ne sont pas encore disponibles dans cette compilation.",
    "Enable trusted-contact override": "Activer la fonction de contact de confiance",
    "Friends who use Demora can add you as their trusted contact with this code.": "Les amis qui utilisent Demora peuvent vous ajouter comme leur contact de confiance avec ce code.",
    "Demora user": "Utilisateur Demora",
    "My code": "Mon code",
    "No Demora user found with that code.": "Aucun utilisateur Demora trouvé avec ce code.",
    "No contacts yet": "Pas encore de contacts",
    "Remove trusted contact: %@": "Supprimer le contact de confiance: %@",
    "Send request": "Envoyer la demande",
    "Sending…": "Envoyer...",
    "Someone set you as their trusted contact and wants to skip a waiting period.": "Quelqu'un vous a mis en contact de confiance et veut sauter une période d'attente.",
    "Their Demora code": "Leur code Demora",
    "Trusted contacts": "Contacts de confiance",
    "Trusted-contact override": "Précédant de contact fiable",
    "Verify code": "Vérifier le code",
    "Waiting for approval from their Demora app…": "En attente d'approbation de leur application Demora...",
    "When enabled, a trusted contact can let you skip a pending change's countdown — by emailing you a code, or by approving from their own Demora app.": "Lorsque activé, un contact de confiance peut vous permettre de sauter le compte à rebours d'un changement en attente — en vous envoyant un courriel ou en approuvant leur propre application Demora.",
    "Who should approve?": "Qui devrait approuver?",
    "Wrong or expired code.": "Code erroné ou périmé.",
    "Your contact received a code by email. Enter it here. It expires in 15 minutes.": "Votre contact a reçu un code par courriel. Entrez-le ici. Il expire dans 15 minutes.",
    "contact": "contact",
    "e.g. Mom, Alex": "Par exemple, maman, Alex",
    "%@ (%d problems)": "%@ (problèmes de %d)",
    "%@ session: %@ (%d min)": "Session %@: %@ (%d min)",
    "%@ — session starts in %@, then runs %d min": "%@ — la session commence en %@, puis lance %d min",
    "%@ — takes effect in %@": "%@ — prend effet dans %@",
    "%d apps, %d categories": "Applications %d, catégories %d",
    "%d hr": "%d h",
    "%d min": "%d min",
    "%d min/day": "%d min/jour",
    "%d minutes": "%d minutes",
    "%d minutes/day": "%d minutes/jour",
    "%d of %d solved": "%d de %d résolu",
    "%d selected": "%d sélectionné",
    "ACTIVE": "ACTIF",
    "Add a daily time limit. It activates after your 'more strict' delay (%@).": "Ajoutez une limite de temps quotidienne. Elle s'active après votre retard « plus strict » (%@).",
    "Add free period: %@ (%@)": "Ajouter une période libre: %@ (%@)",
    "Add free period…": "Ajouter une période libre...",
    "Add limit: %@ — %d min/day": "Ajouter une limite: %@ — %d min/jour",
    "Add me": "Ajoute-moi",
    "Add my name…": "Ajouter mon nom...",
    "Add schedule: %@ (%@ %@)": "Ajouter l'horaire : %@ (%@ %@)",
    "Add schedule…": "Ajouter un horaire...",
    "Adding…": "Ajout...",
    "Allow app deletion": "Permettre la suppression de l'application",
    "Answer": "Réponse",
    "App deletion": "Suppression de l'application",
    "Applies in": "S'applique",
    "Apply now": "Appliquer maintenant",
    "Apply now…": "Postulez maintenant...",
    "Permissions": "Autorisations",
    "Demora needs Screen Time access to set limits and block apps, and notifications to tell you when a pending change is ready. iOS will ask for each.": "Demora a besoin d'un accès à Screen Time pour définir les limites et bloquer les applications, et des notifications pour vous dire quand un changement en attente est prêt. iOS demandera pour chaque.",
    "Grant access": "Accorder un accès",
    "Welcome to Demora": "Bienvenue dans Demora",
    "Demora can be a lot at first, so let's set up your first limit together — a quick, hands-on walkthrough of how delays and overrides actually feel. It takes about a minute.": "Demora peut être beaucoup au début, alors réglons votre première limite ensemble — une rapide, pratique, à travers comment les retards et les dépassements se sentent réellement. Cela prend environ une minute.",
    "Add my first limit": "Ajouter ma première limite",
    "Add your first limit": "Ajouter votre première limite",
    "Add a recurring schedule": "Ajouter un horaire récurrent",
    "Add a sample contact": "Ajouter un contact avec l'échantillon",
    "Add a contact": "Ajouter un contact",
    "Adding a trusted contact normally waits out a delay. In this tutorial it's instant.": "Ajouter un contact de confiance attend normalement un retard. Dans ce tutoriel, c'est instantané.",
    "Alex (sample)": "Alex (échantillon)",
    "Now a schedule. Tap ‘Add a recurring schedule’, pick a time window and some apps, then queue it.": "Maintenant un horaire. Appuyez sur «Ajouter un horaire récurrent, choisissez une fenêtre de temps et certaines applications, puis faites la file d'attente.",
    "Two changes are waiting, and you can't wait them out. Tap Select, choose both, Apply — then use the password override. The password is: test": "Deux changements sont en attente, et vous ne pouvez pas les attendre. Appuyez sur Sélectionner, choisissez les deux, Appliquez — puis utilisez le mot de passe de remplacement. Le mot de passe est : test",
    "Open Calendar to see everything laid out by day.": "Ouvrez le calendrier pour voir tout ce qui est prévu de jour.",
    "Now tidy up: remove the recurring schedule here, and the limit over in Limits.": "Maintenant rangé : supprimez le calendrier récurrent ici, et la limite sur dans Limites.",
    "Now tidy up: open Recurring and remove the schedule you made.": "Maintenant rangé : ouvrez Récurrent et retirez le programme que vous avez fait.",
    "And the limit: tap it, then Remove this limit.": "Et la limite : tapez dessus, puis Enlevez cette limite.",
    "Let's add a backup approver. Open Rules → Overrides → Trusted contacts and add a sample contact.": "Ajoutons un ordonnateur de sauvegarde. Ouvrir les règles → Surpasser → Contacts fiables et ajouter un exemple de contact.",
    "all off": "Tout est éteint",
    "Home delays": "Délais dans les foyers",
    "Home overrides": "Remplacements à domicile",
    "shown": "montré",
    "hidden": "caché",
    "Rules": "Règles",
    "delays, overrides, blocking": "retards, dépassements, blocage",
    "Current overrides": "Les dépassements actuels",
    "No overrides on": "Pas de dépassements",
    "People who approve for you": "Les gens qui approuvent pour vous",
    "Demora code": "Code Demora",
    "Code": "code",
    "Name (optional)": "Nom (facultatif)",
    "Unnamed": "Sans nom",
    "Waiting for them to enter their code.": "Ils attendent qu'ils entrent leur code.",
    "Added as a trusted contact": "Ajouté comme un contact de confiance",
    "Add as trusted contact": "Ajouter comme contact de confiance",
    "They'll get a request to accept before they can approve for you. Adding a contact goes through a delay.": "Ils auront une demande à accepter avant de pouvoir vous approuver. L'ajout d'un contact passe par un retard.",
    "Removing yourself tells them and stops their requests.": "En vous retirant vous leur dit et arrête leurs demandes.",
    "That's your own code.": "C'est ton code.",
    "These people have you as a trusted contact. Tap one to see their details or add them back. Removing yourself tells them and stops their requests.": "Ces personnes vous ont comme un contact de confiance. Appuyez sur un pour voir leurs détails ou les ajouter en arrière. Enlever vous-même leur dit et arrête leurs demandes.",
    "Confirmed": "Confirmé",
    "Send confirmation code": "Envoyer le code de confirmation",
    "Resend code": "Remettre le code",
    "Confirm contact": "Confirmer le contact",
    "Confirm by email": "Confirmer par courriel",
    "We email a code to this address. Your contact gives you the code, you enter it here, and then they can approve for you. Until then they can't.": "Nous envoyons un code par courriel à cette adresse. Votre contact vous donne le code, vous l'introduisez ici, puis ils peuvent approuver pour vous. Jusqu'à ce qu'ils ne puissent pas.",
    "Code sent. Ask your contact for it.": "Demandez à votre contact.",
    "Daily email limit reached. Try again later.": "La limite quotidienne des courriels a été atteinte.",
    "You've sent too many codes today. Try again tomorrow.": "Vous avez envoyé trop de codes aujourd'hui.",
    "Couldn't send the code. Check your connection and try again.": "Je n'ai pas pu envoyer le code, vérifiez votre connexion et essayez encore.",
    "That code didn't match. Double-check and try again.": "Ce code ne correspond pas, vérifie et réessaie.",
    "Both email and Demora-user contacts must confirm before they can approve: email contacts enter a code you email them, Demora users accept in their app. Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Les contacts utilisateurs de l'email et de Demora doivent confirmer avant de pouvoir approuver: les contacts de l'email entrent un code que vous leur envoyez par e-mail, les utilisateurs de Demora acceptent dans leur application. L'ajout d'un contact est un changement moins strict; l'élimination d'un contact est plus stricte — les deux passent par des retards.",
    "Elementary": "Enseignement primaire",
    "Middle school": "École moyenne",
    "High school": "École secondaire",
    "Very easy": "Très facile",
    "Your change is ready": "Votre changement est prêt",
    "Your limits have reset": "Vos limites ont été réinitialisées",
    "If any apps still look blocked, open Demora to refresh them.": "Si les applications semblent encore bloquées, ouvrez Demora pour les rafraîchir.",
    "If you denied access, turn on Screen Time for Demora in Settings, then come back.": "Si vous refusez l'accès, allumez l'heure d'écran pour Demora dans Paramètres, puis revenez.",
    "Open Settings": "Ouvrir les paramètres",
    "Couldn't check the code — check your connection and try again.": "Impossible de vérifier le code — vérifiez votre connexion et essayez à nouveau.",
    "Couldn't send your response — check your connection and try again.": "Impossible d'envoyer votre réponse — vérifiez votre connexion et essayez à nouveau.",
    "Those changes are still counting down. Wait them out, or turn on an override in Settings → Rules → Overrides to skip the wait.": "Ces changements comptent toujours. Attendez-les ou activez une overline dans Paramètres → Règles → Dépasse pour sauter l'attente.",
    "Heads up": "Têtes en haut",
    "Feature roadmap": "Feuille de route",
    "Software roadmap": "Feuille de route logicielle",
    "features & bugs": "fonctionnalités & bugs",
    "links to Trello": "liens vers Trello",
    "Safety code": "Code de sécurité",
    "Mark as verified": "Marquer comme vérifié",
    "Verified": "Vérifié",
    "Security": "Sécurité",
    "Available once you've both added each other.": "Disponible une fois que vous vous êtes ajoutés.",
    "Compare this code with your contact in person or on a call. If it matches on both phones, no one has tampered with the connection.": "Comparez ce code avec votre contact en personne ou sur un appel. Si il correspond sur les deux téléphones, personne n'a altéré la connexion.",
    "Background blocking may be incomplete": "Le blocage des antécédents peut être incomplet",
    "iOS limits how many limits and schedules can run in the background at once. Removing a few restores full enforcement.": "iOS limite le nombre de limites et d'horaires qui peuvent être exécutés en arrière-plan à la fois.",
    "College": "Collège",
    "Nothing — just a new problem": "Rien — juste un nouveau problème",
    "Lose one correct answer": "Perdre une réponse correcte",
    "Restart from zero": "Redémarrer de zéro",
    "Problems to solve": "Problèmes à résoudre",
    "If an answer is wrong": "Si une réponse est erronée",
    "Enable math override (%@, %d problems)": "Activer la surcharge mathématique (problèmes %@, %d)",
    "Solve for x:  %dx + %d = %d": "Résolvez x: %d + %d = %d",
    "Solve for x:  (x − %d) × %d = %d": "Résolvez x: (x − %d) × %d = %d",
    "Solve for x:  %dx + %d = %dx + %d": "Résolvez x: %d + %d = %d + %d",
    "Solve for x:  %d(x + %d) = %d": "Résolvez pour x: %d(x + %d) = %d",
    "Wrong — here's a new problem.": "Faux — voici un nouveau problème.",
    "Wrong — you lost one correct answer.": "Faux: vous avez perdu une réponse correcte.",
    "Wrong — starting over.": "Faux, à partir de maintenant.",
    "Avatar": "avatar",
    "Icon": "Icône",
    "Photo": "photo",
    "Type one emoji": "Type un emoji",
    "Choose a photo": "Choisissez une photo",
    "Change photo": "Changer de photo",
    "Remove photo": "Supprimer la photo",
    "Demora %@": "Demora %@",
    "Blocked user": "Utilisateur bloqué",
    "Two removals are pending. Tap Select, choose both, Apply — then approve with your trusted contact instead of the password.": "Deux suppressions sont en cours. Appuyez sur Sélectionner, choisissez les deux, Appliquez — puis approuvez avec votre contact de confiance au lieu du mot de passe.",
    "This time, use your trusted contact — it'll be approved for you.": "Cette fois, utilisez votre contact de confiance — il sera approuvé pour vous.",
    "Send a request to Alex (sample). A real contact approves from their own Demora app or with an emailed code.": "Envoyer une demande à Alex (échantillon). Un vrai contact approuve de leur propre application Demora ou avec un code par courriel.",
    "Waiting for approval…": "En attente d'approbation...",
    "%d changes: %@": "%d change: %@",
    "Requested change": "Changement demandé",
    "Requested changes": "Modifications demandées",
    "Awaiting approval": "En attente d'approbation",
    "Tap to enter the email code": "Appuyez sur pour entrer le code de courriel",
    "Encrypted request — re-add this contact to read it.": "Demande chiffrée — re-ajouter ce contact pour le lire.",
    "Privacy Policy": "Politique de confidentialité",
    "Terms of Use": "Conditions d'utilisation",
    "Approved!": "Approuvé !",
    "Almost done": "Presque fini",
    "Nice work — that's the whole loop. Now set the delays and overrides that will actually protect you.": "Bon travail — c'est toute la boucle. Maintenant, réglez les retards et les dépassements qui vous protégeront réellement.",
    "Finish setup": "Configuration de finition",
    "Tap ‘Add your first limit’, choose an app or two and a daily budget, then queue the change.": "Appuyez sur « Ajouter votre première limite », choisissez une ou deux applications et un budget quotidien, puis faites la file d'attente du changement.",
    "Your change is waiting out its delay — and you can't wait this one out. Tap ‘Apply now…’ and use the password override. The password is: test": "Votre changement attend son retard — et vous ne pouvez pas attendre celui-ci. Appuyez sur «Appliquer maintenant... - et utilisez le mot de passe de remplacement. Le mot de passe est: test",
    "Now remove it: tap the limit, then ‘Remove this limit’.": "Maintenant, retirez-le: appuyez sur la limite, puis ‘Supprimer cette limite.",
    "Same again — tap ‘Apply now…’ and enter the password (test).": "Même chose encore — appuyez sur «Appliquer maintenant...» et entrez le mot de passe (test).",
    "For this tutorial, only the password works. The password is: test": "Pour ce tutoriel, seul le mot de passe fonctionne. Le mot de passe est : test",
    "For the tutorial, the password is: test": "Pour le tutoriel, le mot de passe est : test",
    "Everything here is just a sample — nothing is saved and nothing is actually blocked. It's only to show how the app works.": "Tout ici n'est qu'un échantillon — rien n'est sauvé et rien n'est bloqué. C'est seulement pour montrer comment fonctionne l'application.",
    "Applying…": "Appliquer...",
    "Apps": "Applications",
    "Apps that stay usable": "Applis qui restent utilisables",
    "Apps to block": "Apps pour bloquer",
    "Nothing selected": "Rien sélectionné",
    "Apps blocked": "Applications bloquées",
    "Apps unblocked": "Apps débloquées",
    "Blocking the selected apps": "Blocage des applications sélectionnées",
    "Unblocking the selected apps": "Débloquer les applications sélectionnées",
    "Apps to unblock": "Apps pour débloquer",
    "Authorize": "Autoriser",
    "Authorized ✓": "Autorisé ✓",
    "Back": "Précédent",
    "Beta testers": "Bêta-testeurs",
    "Block": "Bloquer",
    "Block all except…": "Bloquez tout sauf...",
    "Block app deletion": "Bloc de suppression de l'application",
    "Block apps": "Bloquer les applications",
    "Block only…": "Bloc seulement...",
    "Blocked by Demora": "Bloqué par Demora",
    "Blocking is enforced by iOS itself through Screen Time, the same system parental controls use.": "Le blocage est imposé par iOS lui-même via Screen Time, le même système de contrôle parental utiliser.",
    "Cancel": "Annuler",
    "Change %@ to %d min/day": "Changer %@ en %d min/jour",
    "Changes that make things LESS STRICT (raise a limit, remove a block, add a free period) wait out your second delay — usually set longer.": "Les changements qui font des choses MOINS STRICT (monter une limite, supprimer un bloc, ajouter une période libre) attendent votre deuxième retard — habituellement défini plus longtemps.",
    "Changes that make things STRICTER (add a limit, lower minutes, add a schedule) wait out your first delay.": "Les changements qui font les choses STRICTER (ajouter une limite, des minutes inférieures, ajouter un horaire) attendent votre premier retard.",
    "Changes you make will appear here with a countdown.": "Les changements que vous faites apparaîtront ici avec un compte à rebours.",
    "Choose apps": "Choisir des applications",
    "Close": "Fermer",
    "Confirm password": "Confirmer le mot de passe",
    "Continue": "Continuer",
    "Couldn't load names (check iCloud/network).": "Impossible de charger les noms (cochez iCloud/network).",
    "Couldn't submit — make sure you're signed into iCloud and try again.": "Impossible de soumettre — assurez-vous d'être connecté à iCloud et essayez à nouveau.",
    "Current delays": "Délais actuels",
    "Current: %@": "Actuellement: %@",
    "Daily limit": "Limite quotidienne",
    "Day %d of every month": "Jour %d de chaque mois",
    "Day of month": "Jour du mois",
    "Delay": "Délai",
    "Delay for LOOSER changes": "Retard pour les modifications de LOOSER",
    "Delay for STRICTER changes": "Retard pour les changements STRICTER",
    "Delays": "Délais",
    "Difficulty": "Difficulté",
    "Disable math override": "Désactiver la préséance mathématique",
    "Disable password override": "Désactiver la préséance du mot de passe",
    "Done": "Fait",
    "Duration": "Durée",
    "During a free period, limits don't block and usage inside the window doesn't count toward them — time used before the window still does.": "Pendant une période libre, les limites ne bloquent pas et l'utilisation à l'intérieur de la fenêtre ne compte pas pour eux — le temps utilisé avant que la fenêtre ne le fasse encore.",
    "Easy": "Facile",
    "Enable math override": "Activer la préséance mathématique",
    "Enable math override (%@)": "Activer la surcharge mathématique (%@)",
    "Enable password override": "Activer la fonction de remplacement du mot de passe",
    "Enable/update password override": "Activer/mise à jour la préséance du mot de passe",
    "End": "Fin",
    "End early…": "Finis tôt...",
    "End session early: %@": "Fin de la session tôt: %@",
    "Ends": "Fin",
    "Enter password": "Saisissez le mot de passe",
    "Every change you make waits out a delay you chose, counting down in the background. You can always change your rules — just not in a moment of weakness.": "Chaque changement que vous faites attend un retard que vous avez choisi, en comptant vers le bas dans le fond. Vous pouvez toujours changer vos règles — tout simplement pas dans un moment de faiblesse.",
    "Every day": "Tous les jours",
    "Everything on the iPhone is blocked during the window except the apps picked here.": "Tout sur l'iPhone est bloqué pendant la fenêtre sauf les applications sélectionnées ici.",
    "Free period": "Période libre",
    "Today's usage is reported by iOS Screen Time, which can be slow to load or briefly show nothing. If it looks empty, tap the refresh arrow a couple of times.": "L'utilisation d'aujourd'hui est rapportée par iOS Screen Time, qui peut être lent à charger ou ne montrer brièvement rien. S'il semble vide, appuyez sur la flèche de rafraîchissement quelques fois.",
    "Free": "Libre",
    "Free period: %@ (%d min)": "Période libre: %@ (%d min)",
    "Free period — nothing is blocked": "Période libre — rien n'est bloqué",
    "Temporarily lifts everything — no app blocks apply, and usage during the free period doesn't count toward your limits.": "Il lève temporairement tout — aucun bloc d'application ne s'applique, et l'utilisation pendant la période libre ne compte pas pour vos limites.",
    "Free periods": "Périodes libres",
    "Friction, not passwords": "Friction, pas mots de passe",
    "Get started": "Commencez",
    "Hard": "Difficile",
    "Home": "Accueil",
    "Hours": "Heures",
    "How does it work?": "Comment ça marche ?",
    "Incorrect password": "Mot de passe incorrect",
    "Keep it appropriate — names are reviewed, and inappropriate ones won't be added.": "Gardez-le approprié — les noms sont examinés, et ceux inappropriés ne seront pas ajoutés.",
    "Language": "Langue",
    "Demora needs Screen Time authorization to set app limits and block apps. iOS will ask for your confirmation.": "Demora a besoin d'une autorisation de temps d'écran pour définir les limites des applications et bloquer les applications. iOS demandera votre confirmation.",
    "Demora wouldn't exist without the people who tested it, broke it, and told me about it. Thank you. ❤️": "Demora n'existerait pas sans les gens qui l'ont testé, cassé, et m'en a parlé. Merci.",
    "Less strict": "Moins strict",
    "Less-strict delay": "Délai moins strict",
    "Limit": "Limite",
    "Limits": "Limites",
    "Limits won't block and usage won't count during this window.": "Les limites ne bloquent pas et l'utilisation ne compte pas pendant cette fenêtre.",
    "Limits: daily time budgets per app. When the minutes run out, the app is blocked until midnight.": "Limites : budgets de temps journaliers par application. Lorsque les minutes s'épuisent, l'application est bloquée jusqu'à minuit.",
    "Looser changes": "Changements de l'écart de vitesse",
    "Looser changes wait %@": "Changements de l'écartement d'attente %@",
    "Math override": "Redéfinition mathématique",
    "Math problems": "Problèmes de mathématiques",
    "Medium": "Moyenne",
    "Minutes": "Procès-verbal",
    "Mode": "mode",
    "Monthly schedules can't cross midnight — set the end time after the start time.": "Les horaires mensuels ne peuvent pas traverser minuit — fixer l'heure de fin après l'heure de début.",
    "More strict": "Plus strict",
    "More-strict delay": "Délai plus strict",
    "Most screen-time apps protect your rules with a password — which you know, so you cave. Demora protects them with time instead.": "La plupart des applications d'écran protègent vos règles avec un mot de passe, que vous savez, donc vous coulissez. Demora les protège avec le temps à la place.",
    "Name": "Dénomination",
    "Names will appear here soon.": "Les noms apparaîtront bientôt ici.",
    "New free period": "Nouvelle période libre",
    "New limit": "Nouvelle limite",
    "New password": "Nouveau mot de passe",
    "New schedule": "Nouveau calendrier",
    "New session": "Nouvelle session",
    "New session…": "Nouvelle session...",
    "No free periods": "Pas de périodes libres",
    "No limits yet": "Pas encore de limites",
    "No overrides — delays are absolute": "Pas de dépassements — les retards sont absolus",
    "No pending changes": "Aucun changement n'est en cours",
    "No schedules": "Pas de calendrier",
    "No thanks": "Pas de merci",
    "Nothing planned": "Rien de prévu",
    "Nth weekday": "Nième jour de semaine",
    "OK": "Très bien.",
    "Off": "Hors",
    "On": "À",
    "One-off and unplanned, but still delay-gated. A block session waits %@; an unblock session waits %@. Ending early flips the rule (or use an override).": "Une session de bloc attend %@; une session de déblocage attend %@. Fin de la première fois, la règle est inversée (ou une nouvelle fonction de remplacement).",
    "Only the apps picked here are blocked during the window.": "Seules les applications sélectionnées ici sont bloquées pendant la fenêtre.",
    "Overrides": "Dérogations",
    "Overrides enabled": "Surpassement activé",
    "Overrides let you skip a pending change's countdown. They're off by default. Adding one later counts as a less-strict change; removing one counts as stricter — both go through delays.": "Les dépassements vous permettent de sauter le compte à rebours d'un changement en attente. Ils sont désactivés par défaut. Ajouter un compte plus tard comme un changement moins strict; supprimer un compte comme plus strict — les deux passent par des retards.",
    "Overrides skip a pending change's countdown. Enabling or weakening one is a less-strict change; disabling or strengthening one is stricter. All edits here go through the matching delay.": "Les dépassements sautent le compte à rebours d'un changement en attente. L'activation ou l'affaiblissement d'un changement est un changement moins strict; l'invalidation ou le renforcement d'un changement est plus strict.",
    "A change for this setting is already pending. Cancel it on the Home tab first if you want something different.": "Un changement pour ce paramètre est déjà en cours. Annulez-le d'abord sur l'onglet Accueil si vous voulez quelque chose de différent.",
    "Already pending": "Déjà en attente",
    "A person you choose approves skipping a countdown — by email code or from their own Demora app. You can also add more later in Settings → Trusted contacts.": "Une personne que vous choisissez approuve la suppression d'un compte à rebours — par e-mail ou à partir de sa propre application Demora. Vous pouvez également ajouter plus tard dans Paramètres → Contacts fiables.",
    "Add": "Ajouter",
    "Message (optional)": "Message (facultatif)",
    "Sent along with the request so they know why you're asking.": "Envoyé avec la demande pour qu'ils sachent pourquoi vous demandez.",
    "e.g. why you need this": "Par exemple, pourquoi vous avez besoin de ceci",
    "%@ — Note: %@": "%@ — Remarque : %@",
    "Your request was denied.": "Votre demande a été rejetée.",
    "Send a new request…": "Envoyer une nouvelle demande...",
    "Cancels this request and lets you pick contacts again.": "Annule cette demande et vous permet de choisir à nouveau des contacts.",
    "Coming soon": "Bientôt",
    "Appearance": "Apparence",
    "Theme": "Thème",
    "System": "Système",
    "Light": "Lumière",
    "Dark": "Ténébreux",
    "/ de·mo·ra /  noun, Spanish": "/ demo·ra / nom, espagnol",
    "a delay; the time that passes before something takes effect.": "un délai; le temps qui passe avant que quelque chose ne prenne effet.",
    "an iPhone app that protects your screen-time rules with definition 1 instead of a password.": "une application iPhone qui protège vos règles d'écran-temps avec la définition 1 au lieu d'un mot de passe.",
    "Coming soon — payments aren't available yet.": "Bientôt — les paiements ne sont pas encore disponibles.",
    "Password": "Mot de passe",
    "Password override": "Password redéfinition",
    "Passwords don't match": "Les mots de passe ne correspondent pas",
    "Pay %@": "Payer %@",
    "Pay %@ to apply this change now": "Payer %@ pour appliquer ce changement maintenant",
    "Pending change": "Changements en cours",
    "Pending changes": "Changements en suspens",
    "Pending changes show on the Home tab with a live countdown. You can cancel them anytime before they apply.": "Les modifications en attente s'affichent sur l'onglet Accueil avec un compte à rebours en direct. Vous pouvez les annuler à tout moment avant qu'ils ne s'appliquent.",
    "Plan %@: %@ (%@)": "Plan %@ : %@ (%@)",
    "Plan a window": "Planifiez une fenêtre",
    "Plan a window…": "Planifiez une fenêtre...",
    "Plan ahead for specific dates — a trip, a weekend, an exam. Doesn't repeat. Planning a block is stricter; planning a free period is less strict.": "Planifiez des dates précises — un voyage, un week-end, un examen. Ne répète pas. La planification d'un bloc est plus stricte; la planification d'une période libre est moins stricte.",
    "Planned (one-off)": "Prévue (une fois)",
    "Planned window": "Fenêtre prévue",
    "Purchasing…": "Achats...",
    "Queue change": "Changement de file d'attente",
    "Queue: turn off": "Requête: éteindre",
    "Queue: turn on": "Date: allumer",
    "Recurring schedules": "Calendriers périodiques",
    "Remove free period: %@": "Supprimer la période libre: %@",
    "Remove limit: %@": "Supprimer la limite: %@",
    "Remove planned window: %@": "Supprimer la fenêtre prévue : %@",
    "Remove schedule: %@": "Supprimer le programme: %@",
    "Remove this limit": "Supprimer cette limite",
    "Remove…": "Supprimer...",
    "Repeating windows: every day, chosen weekdays, or monthly patterns. Adding waits %@; removing waits %@.": "Fenêtres répétées : tous les jours, les jours de semaine choisis ou les modèles mensuels. Ajouter des attente %@; supprimer des attente %@.",
    "Repeats": "Répéter",
    "Schedule": "Tableau",
    "Schedules": "Horaires",
    "Schedules: recurring or one-off windows that block chosen apps — or everything except a chosen few. Plus free periods where time doesn't count.": "Horaires : fenêtres récurrentes ou uniques qui bloquent les applications choisies — ou tout sauf quelques-unes choisies. Plus des périodes libres où le temps ne compte pas.",
    "Screen Time access": "Accès à Temps d’écran",
    "Sessions": "Sessions",
    "Set 'less strict' delay to %@": "Définissez le délai «moins strict» à %@",
    "Set 'more strict' delay to %@": "Définissez le délai « plus strict » à %@",
    "Settings": "Paramètres",
    "Setup": "Configuration",
    "Simulate payment (beta)": "Simuler le paiement (bêta)",
    "Skip the wait": "Ne pas attendre",
    "Solve %d math problems (%@)": "Résoudre les problèmes de mathématiques de %d (%@)",
    "Solve math problems": "Résoudre les problèmes de maths",
    "Start": "Démarrer",
    "Start using Demora": "Commencez à utiliser Demora",
    "Starts": "Début",
    "Stricter changes": "Changements plus stricts",
    "Stricter changes wait %@": "Les changements plus stricts attendent %@",
    "Submit": "Soumettre",
    "Temporarily lifts limits, schedules, and block sessions for the chosen apps.": "Relève temporairement les limites, les horaires et les sessions de bloc pour les applications choisies.",
    "Thanks for testing Demora!": "Merci pour le test Demora!",
    "This app is blocked right now — by a limit, a schedule, or a session. Changing your rules takes a delay; open Demora to queue a change.": "Cette application est bloquée en ce moment — par une limite, un calendrier, ou une session. Changer vos règles prend un retard; ouvrir Demora pour faire une file d'attente.",
    "If it should already be unblocked, iOS is sometimes slow to apply a background change — open Demora for an immediate unblock.": "Si elle doit déjà être débloquée, iOS est parfois lent à appliquer un changement de fond — ouvrir Demora pour un déblocage immédiat.",
    "Two delays rule everything": "Deux retards règlent tout",
    "Type": "type",
    "Unblock": "Débloquer",
    "Unblock apps": "Débloquer les applications",
    "Unlock": "Déverrouillage",
    "Wait this long before any change that loosens your rules takes effect. Usually set longer than the first.": "Attendez bien avant que tout changement qui relâche vos règles ne prenne effet. Habituellement, défini plus longtemps que le premier.",
    "Wait this long before any change that tightens your rules takes effect.": "Attendez bien avant que tout changement qui resserre vos règles ne prenne effet.",
    "Want your name in the app's beta-tester thanks page? Pick whatever you'd like to be called.": "Vous voulez votre nom sur la page de remerciement beta-tester de l'application ? Choisissez ce que vous souhaitez être appelé.",
    "Weekday": "Jours de semaine",
    "Weekdays": "Jours de semaine",
    "What can it do?": "Que peut-il faire ?",
    "What's in the box": "Qu'est-ce qu'il y a dans la boîte ?",
    "When": "Quand",
    "When on, deleting ANY app from this iPhone is blocked — including Demora itself, so blocks can't be bypassed by uninstalling.": "Lorsque vous activez, supprimer une application de cet iPhone est bloquée — y compris Demora lui-même, de sorte que les blocs ne peuvent pas être contournés par désinstallation.",
    "Which one": "Lequel",
    "Window": "Fenêtre",
    "Wrong — new problem": "Faux — nouveau problème",
    "You're in! Your name will appear in the beta testers page once it's approved.": "Votre nom apparaîtra sur la page des bêta-testeurs une fois qu'il aura été approuvé.",
    "You're set": "Vous êtes prêt",
    "Your name is in — it'll show up once approved.": "Votre nom est dans — il apparaîtra une fois approuvé.",
    "Your name or nickname": "Votre nom ou surnom",
    "e.g. Airport, weekend trip": "Par exemple, aéroport, week-end",
    "e.g. Bedtime": "Par exemple, heure du coucher",
    "e.g. Deep work": "Par exemple, travail en profondeur",
    "e.g. Instagram": "Par exemple, Instagram",
    "e.g. Lunch break": "Par exemple, pause déjeuner",
    "free period": "période libre",
    "limit": "limite",
    "now": "Maintenant",
    "planned window": "fenêtre prévue",
    "schedule": "Calendrier",
    "session": "de la session",
    "A passcode is saved. Open the guide below to view it.": "Un code passe est enregistré. Ouvrez le guide ci-dessous pour le visualiser.",
    "Access requested. It unlocks after your less-strict delay — track it on the Home tab, where you can also use an override to skip the wait.": "Accès demandé. Il se déverrouille après votre délai moins strict — suivre sur l'onglet Accueil, où vous pouvez également utiliser une overforance pour sauter l'attente.",
    "Can't reach this contact right now — they may have removed Demora or signed out. They won't be able to approve until they're back.": "Impossible d'atteindre ce contact dès maintenant — ils ont peut-être enlevé Demora ou signé. Ils ne pourront pas approuver jusqu'à leur retour.",
    "Couldn't start the walkthrough": "Je ne pouvais pas commencer la marche",
    "Bug tracker": "Tracker des bugs",
    "Demora can't stop you from turning off its Screen Time access in iOS Settings — but a friend can. If Screen Time itself is locked with someone else's passcode, iOS blocks any change to Demora's access, while Demora keeps doing all the blocking.": "Demora — Si le temps d'écran lui-même est verrouillé avec le code d'accès de quelqu'un d'autre, iOS bloque tout changement à l'accès de Demora, tandis que Demora continue de faire tout le blocage.",
    "Demora couldn't safely back up your current setup, so the replay was cancelled to protect your limits. Nothing was changed. Please try again in a moment.": "Demora n'a pas pu sauvegarder votre configuration actuelle en toute sécurité, donc le replay a été annulé pour protéger vos limites. Rien n'a été changé. Veuillez réessayer en un instant.",
    "Done. Now you can't disable Demora's access — or change the passcode — without your friend. To undo it later, your friend enters the passcode and turns it off.": "Maintenant, vous ne pouvez pas désactiver l'accès de Demora — ou changer le code d'accès — sans votre ami. Pour le défaire plus tard, votre ami entre le code d'accès et l'éteint.",
    "Email limit": "Limite du courriel",
    "Emoji": "émoticône",
    "Friend: save the passcode here so it isn't lost. It's only shown from this page, which is behind your delay.": "Ami : sauvegardez le code de passe ici pour qu'il ne soit pas perdu. Il est seulement affiché à partir de cette page, qui est derrière votre retard.",
    "Hand your phone to your friend. Have THEM enter a 4-digit passcode you don't see — don't watch.": "Donnez votre téléphone à votre ami. Faites-leur entrer un code à 4 chiffres que vous ne voyez pas — ne regardez pas.",
    "Heads up: on your iOS version, a limit only counts screen time from the moment you add it — time you already spent earlier today isn't included. Update to iOS 17.4 or later for exact daily counting.": "En tête : sur votre version iOS, une limite ne compte que le temps d'écran à partir du moment où vous l'ajoutez — le temps que vous avez déjà passé plus tôt aujourd'hui n'est pas inclus.",
    "Make Demora impossible to disable": "Ne pas désactiver Demora",
    "Onboarding demo — you can skip below. It's always available again in Settings → Help.": "Démo embarquée — vous pouvez sauter ci-dessous. Il est toujours disponible à nouveau dans Paramètres → Aide.",
    "One more safeguard": "Une autre sauvegarde",
    "Open Settings → Screen Time on this iPhone. If it's off, turn it on.": "Ouvrez Paramètres → Heure d'écran sur cet iPhone. Si c'est désactivé, allumez-le.",
    "Open the guide": "Ouvrir le guide",
    "Opening this is delayed on purpose — so you can't impulsively look up how to undo your own lock.": "L'ouverture de cette porte est retardée sur le but — de sorte que vous ne pouvez pas regarder impulsivement comment défaire votre propre serrure.",
    "Passcode": "Code passe",
    "Pick someone you trust and can reach. If the passcode and its recovery Apple ID are both lost, removing it may require erasing the device.": "Choisissez quelqu'un en qui vous avez confiance et pouvez atteindre. Si le code passe et son identifiant Apple de récupération sont tous les deux perdus, supprimer il peut nécessiter l'effacement de l'appareil.",
    "Prevent disabling": "Empêcher l'infirmité",
    "Protection": "Protection des personnes",
    "Replay walkthrough": "Rejouer la marche à travers",
    "Request access": "Demande d'accès",
    "Save": "Enregistrer",
    "Saved passcode: %@": "Code d'enregistrement: %@",
    "Unlock viewing the stored passcode": "Déverrouiller la vue du code d'accès stocké",
    "how to lock it with a friend": "comment le verrouiller avec un ami",
    "Screen Time passcode": "Code de passe de l'écran",
    "none saved": "Aucun sauvé",
    "saved": "sauvé",
    "Enter passcode": "Saisissez le code d'accès",
    "save it here so it isn't lost": "Garde-le ici pour qu'il ne soit pas perdu",
    "replaces the saved one": "remplace le sauvé",
    "behind your delay": "derrière votre retard",
    "View passcode": "Affichage du code d'accès",
    "Change the passcode?": "Changer le code d'accès ?",
    "Are you sure? There is no way to undo this — the saved passcode is replaced only when you save a new one.": "Vous êtes sûr? Il n'y a aucun moyen de le défaire — le code de passe enregistré est remplacé seulement lorsque vous en enregistrez un nouveau.",
    "The friend who set the Screen Time passcode can store it here so it isn't lost. Going back without saving keeps the current one.": "L'ami qui a défini le code Passcode Screen Time peut le stocker ici pour qu'il ne soit pas perdu.",
    "Viewing the stored passcode is behind your less-strict delay: request it, wait out the delay, and you get one look. After that it locks again.": "La visualisation du code de passe stocké est derrière votre délai moins strict : demandez-le, attendez le délai, et vous obtenez un regard. Après cela, il se verrouille à nouveau.",
    "Access is spent — viewing it again needs a new request.": "L'accès est dépensé — le visionner à nouveau nécessite une nouvelle demande.",
    "Screen Time usually only allows a 4-digit passcode — are you sure this is correct?": "Le temps d'écran permet généralement un code de passe à 4 chiffres — êtes-vous sûr que c'est correct?",
    "Saved ✓": "Enregistrer ✓",
    "Show me how": "Montre-moi comment",
    "Skip and set up manually": "Sauter et configurer manuellement",
    "Skip walkthrough": "Sautez la marche",
    "Skip — set up manually": "Sauter — configurer manuellement",
    "Store the Screen Time passcode": "Conservez le code d'accès à l'heure d'écran",
    "Take photo": "Prendre une photo",
    "Takes about 2 minutes, and you need a second person physically with you.": "Ça prend environ 2 minutes, et vous avez besoin d'une seconde personne physiquement avec vous.",
    "Tap “Lock Screen Time Settings” (or “Use Screen Time Passcode”).": "Appuyez sur -Lock Paramètres de l'écran Temps (ou -Utilisez le code de passe de l'écran Temps).",
    "Thank you. ❤️": "Merci. Je vous remercie.",
    "That's okay. Without Screen Time access Demora can't block apps, but you can continue and turn it on later.": "Sans l'accès à l'écran Time Demora ne peut pas bloquer les applications, mais vous pouvez continuer et l'allumer plus tard.",
    "That's the whole loop. Your real limits, schedules, and settings are still here — nothing changed.": "C'est toute la boucle. Vos vraies limites, vos horaires et vos paramètres sont toujours là — rien n'a changé.",
    "There's a way to make Demora impossible to turn off — with a friend's help. It takes about 2 minutes and needs a second person physically with you.": "Il y a un moyen de rendre Demora impossible à désactiver, avec l'aide d'un ami. Il faut environ 2 minutes et a besoin d'une seconde personne physiquement avec vous.",
    "They call themselves “%@”.": "Ils se disent eux-mêmes -%@.",
    "This guide is behind your less-strict delay: request it, wait out the delay, and you get one open. After you view it, it locks again.": "Ce guide est derrière votre délai moins strict : demandez-le, attendez le délai, et vous obtenez un ouvert. Après vous le voyez, il se verrouille à nouveau.",
    "Unavailable": "Indisponible",
    "Unlock the “Prevent disabling” guide": "Déverrouillez le guide --Prévenir l'invalidation",
    "Use photo": "Utiliser la photo",
    "When asked for Screen Time Passcode Recovery, your friend signs in with THEIR OWN Apple ID — not yours. That's what stops you from resetting the passcode on your own.": "Lorsqu'on vous demande de récupérer le code Passcode de l'écran, votre ami s'inscrit avec LEUR ID Apple OWN — pas le vôtre. C'est ce qui vous empêche de réinitialiser le code pass sur votre propre.",
    "You can always find this later under Help — but there it's behind a delay.": "Vous pouvez toujours trouver cela plus tard sous Aide — mais il y a un retard.",
    "You can change these any time under General blocking. Each change then goes through your delays.": "Vous pouvez les modifier à tout moment sous le blocage général. Chaque changement passe par vos retards.",
    "Your one-time access is ready.": "Votre accès unique est prêt.",
    "lock it with a friend": "Verrouillez-le avec un ami.",
    "your setup stays safe": "votre installation reste en sécurité",
    "—": "—",
]
