//
//  Localization+Polish.swift
//  Full in-app localization table. Missing keys fall back to English.
//

import Foundation

let polishStrings: [String: String] = [
    "Dismiss": "Zamknij",
    "Recheck blocked limits": "Sprawdź ponownie zablokowane limity",
    "Takes around 30 seconds": "Trwa około 30 sekund",
    "Recheck keeps current blocks in place while iOS verifies today's usage. Limits iOS confirms stay blocked.": "Podczas ponownego sprawdzania obecne blokady pozostają aktywne, a iOS weryfikuje dzisiejsze użycie. Limity potwierdzone przez iOS pozostają zablokowane.",
    "Limit recheck": "Ponowne sprawdzanie limitów",
    "Released %d stale limit blocks. %d limits were freshly confirmed by iOS.": "Usunięto %d nieaktualnych blokad limitów. iOS ponownie potwierdził %d limitów.",
    "iOS freshly confirmed all current limit blocks.": "iOS ponownie potwierdził wszystkie obecne blokady limitów.",
    "No blocked limits need to be rechecked.": "Nie ma zablokowanych limitów wymagających ponownego sprawdzenia.",
    "Wait until the active free period ends, then recheck again.": "Poczekaj na zakończenie aktywnego okresu wolnego i spróbuj ponownie.",
    "You can recheck again in %@.": "Ponowne sprawdzenie będzie możliwe za %@.",
    "The recheck was interrupted. No blocks were changed.": "Sprawdzanie zostało przerwane. Żadne blokady nie zostały zmienione.",
    "iOS couldn't complete the verification safely. No blocks were changed. Try again later.": "iOS nie mógł bezpiecznie ukończyć sprawdzania. Żadne blokady nie zostały zmienione. Spróbuj ponownie później.",
    "Safe limit rechecking requires iOS 17.4 or later. No blocks were changed.": "Bezpieczne ponowne sprawdzanie limitów wymaga iOS 17.4 lub nowszego. Żadne blokady nie zostały zmienione.",
    "This is a demo — nothing you do here is saved or actually blocked.": "To demo — nic, co tutaj robisz, nie jest zapisane ani faktycznie zablokowane.",
    "Limitations": "Ograniczenia",
    "iOS reporting notes": "Uwagi sprawozdawcze iOS",
    "Today's usage reporting": "Dzisiaj raportujemy o wykorzystaniu",
    "Daily counting on older iOS": "Codzienne liczenie na starsze iOS",
    "%@ #%d of every month": "%@ #%d każdego miesiąca",
    "%d / %d min": "%d / %d min",
    "blocked until midnight": "zablokowany do północy",
    "now & next": "& teraz",
    "Today's usage": "Dzisiaj używamy",
    "Manage": "Zarządzaj",
    "Week starts": "Zaczyna się tydzień",
    "Monday": "Poniedziałek",
    "Sunday": "Niedziela",
    "Calendar": "Kalendarz",
    "week / month": "tydzień / miesiąc",
    "month": "miesiąc",
    "Solve math problems to skip a countdown.": "Rozwiąż problemy z matematyką, aby pominąć odliczanie.",
    "Enter a password to skip a countdown.": "Podaj hasło, aby pominąć odliczanie.",
    "How schedules work": "Jak działa rozkłady",
    "Help": "Pomoc",
    "guide, contact, more": "przewodnik, kontakt, więcej",
    "thank you": "Dziękuję.",
    "Guide": "Przewodnik",
    "Contact": "Kontakt",
    "About": "O aplikacji",
    "how each part works": "jak działa każda część",
    "bug, feature, help": "Błąd, funkcja, pomoc",
    "links": "linki",
    "Report a bug": "Zgłoś błąd",
    "Request a feature": "Prośba o funkcję",
    "General help": "Pomoc ogólna",
    "Website": "Strona internetowa",
    "Instagram": "Instagram",
    "What Demora is": "Co to jest Demora",
    "Demora protects your screen-time rules with a delay instead of a password. Every change you make waits out a countdown before it takes effect, so you can always change your mind — just not instantly, in a moment of weakness. Blocking itself is enforced by iOS through Screen Time.": "Demora chroni reguły czasu ekranu z opóźnieniem zamiast hasła. Każda zmiana, którą zrobisz czeka odliczanie zanim zacznie działać, więc zawsze możesz zmienić zdanie — po prostu nie natychmiast, w chwili słabości. Blokowanie się przez iOS przez czas ekranu.",
    "There are two delays. The more-strict delay gates changes that tighten your rules (adding a limit, lowering minutes, adding a schedule). The less-strict delay gates changes that loosen them (raising a limit, removing a block, adding a free period) — usually set longer. Pending changes show on the Home tab with a live countdown and can be cancelled before they apply.": "Istnieją dwa opóźnienia. Im bardziej ograniczające się opóźnienia bramy zmieniają się, które zaostrzają Twoje zasady (dodając limit, obniżając minuty, dodając harmonogram). Mniej ograniczone opóźnienia bramy zmieniają się, które ich rozluźniają (zwiększają limit, usuwają blok, dodając wolny okres) – zwykle ustalają się dłużej. Do czasu zmian w zakładce Home z odliczaniem na żywo i mogą zostać odwołane przed ich zastosowaniem.",
    "A limit is a daily time budget for the apps or categories you choose. When the minutes run out, those apps are blocked until midnight. The Limits tab shows today's usage per limit, and tapping a limit shows exactly which apps it covers.": "Limit czasu jest dziennym budżetem czasu dla aplikacji lub kategorii, które wybierasz. Kiedy kończy się protokół, aplikacje te są zablokowane do północy. Zakładka Limity pokazuje dzisiejsze wykorzystanie na limit, i kliknięcie limitu pokazuje dokładnie, które aplikacje pokrywa.",
    "Schedules block apps on a repeating or one-off basis. Recurring schedules repeat daily, on chosen weekdays, or monthly. Planned windows are one-offs for specific dates. Sessions are immediate timed blocks or unblocks. Free periods are windows where limits don't block and usage doesn't count.": "Plany blokowania aplikacji na zasadzie powtarzania lub jednorazowego. Powtórzone rozkłady powtarzania codziennie, w wybranych dni lub miesięcznie. Planowane okna są jednorazowe dla określonych dat. Sesje są natychmiastowe bloki lub odblokowania. Darmowe okresy to okna, w których limity nie blokują i nie liczą się.",
    "A trusted contact can approve skipping a countdown — by email code or from their own Demora app. People you add must accept before they can approve, and you can revoke them at any time.": "Zaufany kontakt może zatwierdzić pominięcie odliczania — kodem e-mailowym lub z własnej aplikacji „Demora”. Ludzie, których dodajesz, muszą zaakceptować przed ich przyjęciem, a w każdej chwili można je odwołać.",
    "App deletion lock": "Zamek usuwania aplikacji",
    "the core idea": "podstawową ideę",
    "the two countdowns": "dwa odliczania",
    "daily app budgets": "budżety aplikacji na co dzień",
    "recurring, planned, sessions": "powtarzające się, planowane, sesje",
    "escape hatches": "włazy ucieczki",
    "approval by a person": "zatwierdzenie przez osobę",
    "can't uninstall to bypass": "Nie można odinstalować by ominąć",
    "Most screen-time apps lock your rules behind a password. Because you know the password, you can undo your own rules the moment you feel the urge — so they rarely stick.\n\nDemora protects your rules with time instead. Every change waits out a countdown you set in advance before it takes effect. You stay in full control of your rules, but you can't change them in a single impulsive moment. The blocking itself is enforced by iOS through Screen Time — the same system parental controls use — so it can't be quietly bypassed.": "Większość aplikacji w czasie ekranu zamyka swoje zasady za hasłem. Ponieważ znasz hasło, możesz cofnąć swoje własne zasady w momencie, gdy poczujesz potrzebę — więc rzadko trzymają się zasad. Demora chroni Twoje zasady z czasem. Każda zmiana czeka na odliczanie, które ustawiłeś przed wejściem w życie. Pozostajesz w pełnej kontroli swoich zasad, ale nie możesz ich zmienić w jednej chwili impulsywnej. Blokowanie jest egzekwowane przez iOS przez czas ekranu — ten sam system kontroli rodzicielskiej, więc nie można bez żadnych zmian.",
    "Demora has two delays. The more-strict delay covers any change that tightens your rules: adding a limit, lowering its minutes, adding a schedule, or turning on the deletion lock. The less-strict delay covers changes that loosen them: raising a limit, removing a block, adding a free period, or disabling an override. The less-strict delay is usually set longer, since loosening is where temptation lives.\n\nA change doesn't apply right away — it becomes a pending change with a live countdown on the Home tab. You can cancel it any time before it lands, and when the countdown reaches zero it applies on its own, even if the app is closed.": "„Demora” ma dwa opóźnienia. Opóźnienie bardziej ograniczone obejmuje każdą zmianę, która zaostrza Twoje zasady: dodanie limitu, zmniejszenie jego minuty, dodanie harmonogramu, lub włączenie blokady usuwania. Im mniej czas opóźnienia obejmuje zmiany, które ich złagodzi: podniesienie limitu, usunięcie bloku, dodanie okresu wolnego, lub wyłączenie nadrzędnego. Im mniej ograniczone opóźnienia jest zwykle ustalane dłużej, ponieważ rozluźnienie jest miejsce, gdzie pokuszenie żyje. Zmiana nie stosuje się od razu — staje się ona w oczekiwaniu na zmianę z odliczaniem na żywo na karcie Home. Możesz ją odwołać w dowolnym momencie przed lądowaniem, a gdy odliczanie osiąga zerową wartość, stosuje się w własnej postaci, nawet jeśli aplikacja jest zamknięta.",
    "A limit is a daily time budget for a set of apps or whole categories. When the minutes run out, those apps are blocked for the rest of the day and unlock again at midnight.\n\nThe Limits tab shows today's real usage for each limit, read straight from Screen Time, and tapping a limit reveals exactly which apps and categories it covers. Because usage is measured by iOS, time spent before you created the limit still counts toward it that day. Raising or removing a limit is a less-strict change; adding one or lowering its minutes is stricter.": "Limit czasu jest dziennym budżetem dla zestawu aplikacji lub wszystkich kategorii. Gdy kończy się protokół, aplikacje są zablokowane na resztę dnia i odblokować ponownie o północy. Zakładka Limity pokazuje rzeczywiste wykorzystanie dla każdego limitu, odczytać bezpośrednio z czasu ekranu i pochylić limit pokazuje dokładnie, które aplikacje i kategorie, które obejmuje. Ponieważ korzystanie jest mierzone przez iOS, czas spędzony przed utworzeniem limit nadal liczy się do niego tego dnia. Wzniesienie lub usunięcie limitu jest mniej ograniczoną zmianą; dodanie jednej lub obniżania jego minut jest surowsze.",
    "Schedules block apps by time rather than by budget, in a few shapes. Recurring schedules repeat — every day, on chosen weekdays, or on a monthly pattern. Planned windows are one-offs for a specific date, like a trip or an exam. Sessions are immediate, timed blocks or unblocks you start right now. Free periods are windows where limits don't block and usage doesn't count toward them.\n\nEach blocking schedule either blocks the apps you pick, or blocks everything except the apps you pick. When rules overlap, the most specific one wins: a session beats a planned window, which beats a recurring schedule, and within the same kind the one added most recently takes priority.": "Harmonogramy blokują aplikacje w czasie, a nie w budżecie, w kilku kształtach. Powstające rozkłady powtarzają się — każdego dnia, w wybranych dniach dnia, lub na miesięcznym wzorze. Planowane okna są jednorazowymi oknami na określony termin, jak podróż lub egzamin. Sesje są natychmiastowe, bloki czasowe lub odblokowuje się od teraz. Wolne okresy to okna, w których granice nie blokują i nie używają ich. Każdy harmonogram blokowania albo blokuje aplikacje, które wybierasz, albo blokuje wszystko, z wyjątkiem aplikacji, które wybierasz. Kiedy zasady pokrywają się, to najbardziej konkretne wygrane: sesja przebija planowane okno, które pobije powtarzający się harmonogram, a w tym samym rodzaju jeden dodany ostatnio ma priorytet.",
    "Overrides are optional escape hatches that let you skip a pending change's countdown. There are three: solve a set of math problems, enter a password, or ask a trusted contact to approve. They're all off by default, so out of the box your delays are absolute.\n\nTurning an override on, or making it easier, counts as a less-strict change and waits out that delay. Turning one off, or making it harder, is stricter — so you can't instantly weaken your own safety net.": "Wybór to opcjonalne włazy ewakuacyjne, które pozwalają pominąć wyczekiwaną zmianę. Istnieją trzy: rozwiązanie wielu problemów z matematyką, wpisywanie hasła lub zapytanie o zaufany kontakt, aby zaakceptować. Są one domyślnie wyłączone, więc z pola opóźnienia są absolutne. Włączanie nadrzędnego, lub ułatwianie, liczy się jako mniej ograniczona zmiana i czeka na tę zmianę. Wyłączenie jednego z opóźnień, lub utrudnienie, jest bardziej surowe – więc nie można natychmiast osłabić własnej sieci bezpieczeństwa.",
    "A trusted contact is a person who can approve skipping a countdown for you. They can approve by entering a short code sent to their email, or directly from their own copy of Demora.\n\nAnyone you add has to accept the request before they can approve anything, so no one is involved without their knowledge. You can revoke a contact at any time, and they can step down on their side too. Adding the override is a less-strict change; removing it is stricter.": "Zaufany kontakt to osoba, która może zatwierdzić odliczanie dla Ciebie. Mogą zatwierdzić wprowadzenie krótkiego kodu wysyłanego na swój e-mail lub bezpośrednio z własnej kopii Demora. Każdy, kto dodasz musi przyjąć żądanie zanim mogą zatwierdzić cokolwiek, więc nikt nie jest zaangażowany bez ich wiedzy. Możesz odwołać kontakt w każdej chwili, i mogą ustąpić po swojej stronie. Dodawanie ostrzeżenia jest mniej ograniczoną zmianą, usunięcie tego urządzenia jest bardziej surowsze.",
    "When the deletion lock is on, deleting any app from this iPhone is blocked — including Demora itself. That closes the most obvious loophole: uninstalling the app to wipe your rules.\n\nBecause turning the lock off makes things easier to bypass, it counts as a less-strict change and waits out that delay before it takes effect.": "Gdy jest włączona blokada usuwania, usuwanie dowolnej aplikacji z tego iPhone jest zablokowane – w tym sam „Demora». To zamyka najbardziej oczywiste luki: odinstalowanie aplikacji do usunięcia reguł. Ponieważ wyłączenie blokady ułatwia obejście, liczy się jako mniej ograniczona zmiana i czeka na opóźnienie zanim zacznie działać.",
    "When on, deleting any app from this iPhone is blocked — including Demora itself — so your rules can't be bypassed by uninstalling. Turning it off goes through the less-strict delay.": "Kiedy się w to wszystko, usuwanie dowolnej aplikacji z tego iPhone jest zablokowane – w tym „Demora” – więc Twoje zasady nie mogą być pominięte przez odinstalowanie. Wyłączanie jest wyłączone przez mniej ograniczone opóźnienie.",
    "Blocks": "Bloki",
    "New recurring": "Nowe powtarzanie",
    "Week": "Tydzień",
    "Month": "Miesiąc",
    "Nothing on this day.": "Nic w tym dniu.",
    "When things overlap": "Kiedy rzeczy się pokrywają",
    "One-off, right now: block or unblock chosen apps for a set number of minutes. Still delay-gated to start; ending early flips the rule.": "Jednorazowe, teraz: blok lub odblokuj wybrane aplikacje na ustawioną liczbę minut. Nadal opóźnione, aby rozpocząć; kończące wcześnie przewraca regułę.",
    "One-off windows for specific dates — a trip, an exam. Block, allow-all-except, or a free period. Doesn't repeat.": "Jednorazowe okna dla określonych dat — wycieczka, egzamin. Blok, dozwolenie wszystkich, lub wolny okres. Nie powtarza.",
    "Windows that repeat — daily, by weekday, or monthly. Each is either a block or a free period.": "Okna, które powtarzają się codziennie, w ciągu dnia, lub co miesiąc. Każdy jest blokiem lub okresem wolnym.",
    "Limits don't block during the window, and time used inside it doesn't count against your daily budgets.": "Limity nie blokują w czasie okna, a czas używany w nim nie jest wliczany w codzienne budżety.",
    "Priority: a session beats a planned window, which beats a recurring schedule. Within the same kind, the one you added most recently wins.": "Priorytet: sesja przebija planowane okno, które przebije powtarzający się harmonogram. W tym samym rodzaju, ten, który dodałeś ostatnio wygrane.",
    "today %@–%@": "dzisiaj %@–%@",
    "Current passcode": "Bieżący kod przepustowy",
    "New passcode": "Nowy kod przepustki",
    "Confirm new passcode": "Potwierdź nowy kod przepustki",
    "Change passcode": "Zmiana kodu przepustowego",
    "Change passcode now": "Zmień kod przepustki teraz",
    "Enter your current passcode to change it instantly. Forgot it? Reset below — that one waits out your delay.": "Podaj swój aktualny kod, aby go zmienić natychmiast. Zapomniałeś? Przywróć poniżej - że ten czeka opóźnienie.",
    "Forgot it?": "Zapomniałeś?",
    "Reset passcode (forgot)": "Przepustka resetowa (wykres)",
    "Turn off password override": "Wyłącz obejście hasła",
    "Wrong passcode.": "Niewłaściwy kod.",
    "Select": "Wybierz",
    "Cancel %d": "Anuluj %d",
    "Apply %d now": "Zastosuj teraz %d",
    "%d changes": "%d zmian",
    "Denied": "Odmawiano",
    "My info": "Moje informacje",
    "view": "widok",
    "Nobody yet": "Jeszcze nikt.",
    "language, theme, case": "język, temat, przypadek",
    "%@ · %@": "%@ · %@",
    "none on": "nie ma",
    "%d on": "%d",
    "Nothing scheduled right now.": "Nic zaplanowanego.",
    "Active now": "Aktywny",
    "Coming up": "Już się robi.",
    "until %@": "do czasu %@",
    "today at %@": "dzisiaj w %@",
    "Planned": "Planowane",
    "Recurring": "Cykliczne",
    "none": "brak",
    "No active sessions": "Brak aktywnych sesji",
    "%d · %d active": "%d · %d aktywnych",
    "%d total": "%d łącznie",
    "Your name": "Twoje imię",
    "Your name (optional)": "Twoje imię (opcjonalnie)",
    "Shown to people you ask to approve, so they know it's you.": "Pokazałeś ludziom, którzy cię proszą o zgodę, żeby wiedzieli, że to ty.",
    "People you approve for": "Ludzie, dla których się zgadzasz",
    "These people have you as a trusted contact. Removing yourself tells them and stops their requests.": "Ci ludzie mają cię jako zaufanego kontaktu.",
    "Remove": "Usuń",
    "code %@": "kod %@",
    "Demora user %@": "„Demora” użytkownik %@",
    "%@ removed their permission to be your trusted contact.": "%@ usunięto ich zgodę na zaufany kontakt.",
    "Trusted contact removed": "Usunięto zaufany kontakt",
    "A trusted contact": "Zaufany kontakt",
    "That's your own code — add someone else.": "To twój własny kod - dodaj kogoś innego.",
    "You already have this person as a contact.": "Masz już tę osobę jako kontakt.",
    "Request history": "Wymaganie historii wniosku",
    "Blocked users": "Zablokowani użytkownicy",
    "No requests yet.": "Nie ma jeszcze życzeń.",
    "No blocked users.": "Brak zablokowanych użytkowników.",
    "Blocked": "Zablokowane",
    "Accepted": "Zaakceptowane",
    "Declined": "Oddany",
    "Requested": "Zwrócone",
    "Accept": "Akceptuj",
    "Decline": "Oddanie",
    "Active": "Aktywny",
    "Pending": "W oczekiwaniu",
    "Contact requests": "Wnioski o kontakt",
    "Pending — hasn't accepted yet": "Do czasu przyjęcia jeszcze nie zaakceptowano",
    "Waiting for them to accept in their Demora app.": "Czekając na ich akceptację w aplikacji „Demora”.",
    "A trusted contact can let you skip a pending change's countdown — by emailing you a one-time code, or, if they use Demora, by approving from their own app.": "Zaufany kontakt może pominąć wychodzące zmiany — wysyłając Ci jednorazowe kody, lub, jeśli używają Demora, zatwierdzając z własnej aplikacji.",
    "Share this code so another Demora user can add you. You get a request to accept before it's active.": "Podziel ten kod, aby inny użytkownik Demora mógł dodać do Ciebie. Otrzymasz prośbę o zaakceptowanie przed jego aktywnością.",
    "A Demora user (code %@) wants to add you as their trusted contact.": "Użytkownik „Demora” (kod %@) chce dodać Cię jako zaufany kontakt.",
    "%@ (code %@) wants to add you as their trusted contact.": "%@ (kod %@) chce dodać Cię jako ich zaufany kontakt.",
    "If you accept, they can ask you to approve skipping their delays.": "Jeśli się zgodzisz, mogą poprosić cię o to, żebyś pominął ich opóźnienia.",
    "Email contacts work as soon as you add them. Demora-user contacts must accept first. Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Kontakt e-mail działa jak tylko je dodasz. Demora-kontakty użytkownika muszą zaakceptować najpierw. Dodawanie kontaktu jest mniej rygorystyczną zmianą; usunięcie jednego jest bardziej surowe — oba idą w opóźnienia.",
    "Ask them for the code in their Demora settings. They'll get a request to accept before they can approve for you.": "Zapytaj o kod w ustawieniach „Demora”. Otrzymają prośbę o zaakceptowanie, zanim zatwierdzą dla Ciebie.",
    "change": "Zmiana",
    "Text case": "Wielkość liter",
    "lowercase": "małe",
    "Regular": "Regularne",
    "6-digit code": "6-cyfrowy kod",
    "Add contact": "Dodaj kontakt",
    "Add contact…": "Dodaj kontakt...",
    "Add trusted contact: %@": "Dodaj zaufany kontakt: %@",
    "Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Dodawanie kontaktu jest mniej rygorystyczną zmianą; usunięcie jednego jest bardziej rygorystyczne — obie idą w czasie opóźnień.",
    "Any one approval unlocks the change.": "Każda z nich odblokuje zmianę.",
    "Approval requests": "Wnioski o zatwierdzenie",
    "Approve": "Zatwierdzenie",
    "Ask a contact": "Zapytaj o kontakt.",
    "Ask a trusted contact": "Zapytaj o zaufany kontakt.",
    "Ask them for the code shown in their Demora settings.": "Zapytaj o kod pokazane w ustawieniach „Demora”.",
    "Checking…": "Sprawdzam...",
    "Checks automatically every few seconds. The request expires after 1 hour.": "Sprawdza automatycznie co kilka sekund.",
    "Contacts": "Kontakty",
    "approvers, blocked": "zatwierdzające, zablokowane",
    "Couldn't send the request — check your connection and try again.": "Nie można wysłać zapytania – sprawdź połączenie i spróbuj ponownie.",
    "Too many requests to this contact right now. Try again later.": "Zbyt wiele prośb do tego kontaktu. Spróbuj później.",
    "You've used all of today's approval emails. Try again tomorrow.": "Użyłeś wszystkich e-maili od dzisiejszego zatwierdzenia.",
    "General blocking": "Ogólne blokowanie",
    "deletion, websites": "usunięcie, strony internetowe",
    "Block adult websites": "Zablokuj strony internetowe dla dorosłych",
    "Allow adult websites": "Zezwól na strony internetowe dla dorosłych",
    "Uses Apple's built-in filter to limit adult websites in Safari and other apps.": "Używa wbudowanego filtra Apple do ograniczenia stron internetowych dorosłych w Safari i innych aplikacjach.",
    "Website blocker": "Bloker stron internetowych",
    "Block website: %@": "Strona internetowa bloku: %@",
    "Unblock website: %@": "Strona internetowa Unblock: %@",
    "e.g. reddit.com": "np. reddit.com",
    "Queue: remove": "Ręka: usunąć",
    "Block specific websites by typing their domain — no need for Apple's site picker, which often comes up empty. Note: blocking sites also turns on Apple's adult-content filter. Adding a site is gated by your delays; removing one waits the longer delay.": "Blokują konkretne strony internetowe, wpisując domenę — nie ma potrzeby zbierania witryny Apple, która często pojawia się pusta. Uwaga: strony blokujące włączają również filtr zawarty w Apple. Dodanie witryny jest zablokowane przez opóźnienia; usunięcie jednego czeka dłużej.",
    "Blocked all day": "Zablokowano cały dzień",
    "Adult websites": "Dorosłe strony internetowe",
    "%d sites": "%d stron",
    "Blocked sites": "Miejsca zablokowane",
    "Stop apps from being deleted, limit adult websites, or block specific sites by domain. Every change here goes through your delays.": "Zatrzymanie aplikacji od usunięcia, ograniczenie stron internetowych dorosłych lub blokowanie określonych stron przez domenę. Każda zmiana tutaj przechodzi przez Twoje opóźnienia.",
    "0 minutes — this app stays blocked all day, every day.": "0 minut – aplikacja ta pozostaje zablokowana przez cały dzień, codziennie.",
    "Approval emails are at capacity right now. Try again later, or use a Demora contact.": "Zatwierdzenia e-maile są już w pojemności. Spróbuj później, lub użyj kontaktu Demora.",
    "You've sent today": "Przysłałeś dziś",
    "All users · today": "Wszyscy użytkownicy · dzisiaj",
    "All users · this month": "Wszyscy użytkownicy · w tym miesiącu",
    "Email approvals": "Zatwierdzenia poczty elektronicznej",
    "Email contacts have a daily send limit; Demora-user contacts don't.": "Kontakty e-mail mają limit dziennego wysyłania; Demora-kontakty użytkownika nie.",
    "one-time, forever": "jednorazowo, na zawsze",
    "active": "aktywna",
    "Deny": "Odmowa",
    "Disable trusted-contact override": "Wyłącz nadpisywanie zaufanego kontaktu",
    "Email": "E- mail",
    "Email address": "Adres e- mail",
    "Email code": "Kod e- mail",
    "Email contacts aren't available yet in this build.": "W tym budynku nie ma jeszcze kontaktów e-mailowych.",
    "Enable trusted-contact override": "Włącz nadpisywanie zaufanego kontaktu",
    "Friends who use Demora can add you as their trusted contact with this code.": "Przyjaciele, którzy używają Demora, mogą dodać jako swój zaufany kontakt z tym kodem.",
    "Demora user": "„Demora” użytkownik",
    "My code": "Mój kod",
    "No Demora user found with that code.": "Nie znaleziono użytkownika „Demora” z tym kodem.",
    "No contacts yet": "Brak jeszcze kontaktów",
    "Remove trusted contact: %@": "Usuń zaufany kontakt: %@",
    "Send request": "Wyślij zapytanie",
    "Sending…": "Wysyłam...",
    "Someone set you as their trusted contact and wants to skip a waiting period.": "Ktoś ustawił cię na zaufany kontakt i chce ominąć okres oczekiwania.",
    "Their Demora code": "Ich kod „Demora”",
    "Trusted contacts": "Zaufane kontakty",
    "Trusted-contact override": "Zaufane obejście kontaktu",
    "Verify code": "Kod weryfikacji",
    "Waiting for approval from their Demora app…": "Czekanie na zatwierdzenie z aplikacji \"Demora\"...",
    "When enabled, a trusted contact can let you skip a pending change's countdown — by emailing you a code, or by approving from their own Demora app.": "Jeśli jest to włączone, zaufany kontakt może pominąć wychodzące zmiany — wysyłając Ci kod lub zatwierdzając z własnej aplikacji „Demora”.",
    "Who should approve?": "Kto powinien się zgodzić?",
    "Wrong or expired code.": "Zły lub wygasły kod.",
    "Your contact received a code by email. Enter it here. It expires in 15 minutes.": "Twój kontakt otrzymał kod e-mail. Wpisz go tutaj. To wygasa w 15 minut.",
    "contact": "kontakt",
    "e.g. Mom, Alex": "np. mama, Alex",
    "%@ (%d problems)": "%@ (%d problemów)",
    "%@ session: %@ (%d min)": "%@ sesja: %@ (%d min)",
    "%@ — session starts in %@, then runs %d min": "%@ — sesja rozpoczyna się w %@, a następnie działa %d min.",
    "%@ — takes effect in %@": "%@ — wchodzi w życie w %@",
    "%d apps, %d categories": "%d apps, %d kategorie",
    "%d hr": "%d godz.",
    "%d min": "%d min",
    "%d min/day": "%d min/dzień",
    "%d minutes": "%d minut",
    "%d minutes/day": "%d minut/dzień",
    "%d of %d solved": "%d z %d rozwiązanych",
    "%d selected": "%d wybrano",
    "ACTIVE": "CZYNNOŚĆ",
    "Add a daily time limit. It activates after your 'more strict' delay (%@).": "Dodaj dzienny limit czasu. Uruchamia się po \"bardziej surowym\" opóźnieniu (%@).",
    "Add free period: %@ (%@)": "Dodaj wolny okres: %@ (%@)",
    "Add free period…": "Dodaj wolny okres...",
    "Add limit: %@ — %d min/day": "Dodaj limit: %@ — %d min/dzień",
    "Add me": "Dodaj mnie",
    "Add my name…": "Dodaj moje imię...",
    "Add schedule: %@ (%@ %@)": "Dodaj harmonogram: %@ (%@ %@)",
    "Add schedule…": "Dodaj harmonogram...",
    "Adding…": "Dodając...",
    "Allow app deletion": "Zezwól na usunięcie aplikacji",
    "Answer": "Odpowiedź",
    "App deletion": "Usuwanie aplikacji",
    "Applies in": "Dotyczy",
    "Apply now": "Zastosuj teraz",
    "Apply now…": "Zastosuj teraz...",
    "Permissions": "Uprawnienia",
    "Demora needs Screen Time access to set limits and block apps, and notifications to tell you when a pending change is ready. iOS will ask for each.": "Demora potrzebuje dostępu czasu ekranu do ustalania limitów i aplikacji blokowych, a powiadomienia, aby powiedzieć, kiedy jest gotowa zmiana w toku. iOS poprosi o każde.",
    "Grant access": "Dostęp do dotacji",
    "Welcome to Demora": "Witamy w Demora",
    "Demora can be a lot at first, so let's set up your first limit together — a quick, hands-on walkthrough of how delays and overrides actually feel. It takes about a minute.": "Demora może być na początku dużo, więc ustawić swoją pierwszą granicę razem — szybki, praktyczny spacer po tym, jak opóźnienia i nadrzędne w rzeczywistości czują. To trwa około minutę.",
    "Add my first limit": "Dodaj moją pierwszą granicę",
    "Add your first limit": "Dodaj swój pierwszy limit",
    "Add a recurring schedule": "Dodaj powtarzający się harmonogram",
    "Add a sample contact": "Dodaj kontakt z próbką",
    "Add a contact": "Dodaj kontakt",
    "Adding a trusted contact normally waits out a delay. In this tutorial it's instant.": "Dodawanie zaufanego kontaktu zwykle czeka opóźnienie.",
    "Alex (sample)": "Alex (pojedyncza)",
    "Now a schedule. Tap ‘Add a recurring schedule’, pick a time window and some apps, then queue it.": "Teraz program. Kliknij na „Dodaj powtarzający się harmonogram”, wybierz okno czasowe i niektóre aplikacje, a następnie w kolejce.",
    "Two changes are waiting, and you can't wait them out. Tap Select, choose both, Apply — then use the password override. The password is: test": "Dwie zmiany czekają, a nie możesz ich czekać. Kliknij Zaznacz, wybierz obie, Zastosuj — a następnie użyj nadpisu hasła. Hasło to: test",
    "Open Calendar to see everything laid out by day.": "Otwarty kalendarz, aby zobaczyć wszystko ustawione w dzień.",
    "Now tidy up: remove the recurring schedule here, and the limit over in Limits.": "Teraz posprzątaj: zdejmij powtarzający się harmonogram tutaj, a limit w limitach.",
    "Now tidy up: open Recurring and remove the schedule you made.": "Teraz posprzątaj: otwórz Powrót i zdejmij harmonogram, który zrobiłeś.",
    "And the limit: tap it, then Remove this limit.": "I granica: stuknij, a następnie usuń tę granicę.",
    "Let's add a backup approver. Open Rules → Overrides → Trusted contacts and add a sample contact.": "Dodajmy do tego autora kopii zapasowej. Otwarte zasady → Przestrzega → Zaufane kontakty i dodajmy do nich kontakt z próbką.",
    "all off": "wszystkie",
    "Home delays": "Opóźnienia w domu",
    "Home overrides": "Określa",
    "shown": "pokazane",
    "hidden": "ukryte",
    "Rules": "Zasady",
    "delays, overrides, blocking": "opóźnienia, omija, blokowanie",
    "Current overrides": "Bieżące nadrzędne",
    "No overrides on": "Brak nadpisów",
    "People who approve for you": "Ludzie, którzy się dla ciebie zgadzają",
    "Demora code": "Demora — Kod demory",
    "Code": "Kod",
    "Name (optional)": "Nazwa (opcjonalnie)",
    "Unnamed": "Bez nazwy",
    "Waiting for them to enter their code.": "Czekam, aż wpiszą kod.",
    "Added as a trusted contact": "Dodano jako zaufany kontakt",
    "Add as trusted contact": "Dodaj jako zaufany kontakt",
    "They'll get a request to accept before they can approve for you. Adding a contact goes through a delay.": "Dostają prośbę o przyjęcie, zanim zatwierdzą.",
    "Removing yourself tells them and stops their requests.": "Sam się im pouczasz i przestajesz ich prośbę.",
    "That's your own code.": "To twój własny kod.",
    "These people have you as a trusted contact. Tap one to see their details or add them back. Removing yourself tells them and stops their requests.": "Ci ludzie mają Cię jako zaufanego kontaktu. Kliknij, aby zobaczyć ich szczegóły lub dodać je do tyłu. Usuwanie się mówi im i zatrzymuje ich prośby.",
    "Confirmed": "Potwierdzone",
    "Send confirmation code": "Wyślij kod potwierdzenia",
    "Resend code": "Kod ponownie",
    "Confirm contact": "Potwierdź kontakt",
    "Confirm by email": "Potwierdzenie pocztą elektroniczną",
    "We email a code to this address. Your contact gives you the code, you enter it here, and then they can approve for you. Until then they can't.": "Twój kontakt daje ci kod, ty go tu wpisujesz, a oni mogą go zatwierdzić.",
    "Code sent. Ask your contact for it.": "Kod wysłany.",
    "Daily email limit reached. Try again later.": "Dotarło do codziennego limitu poczty elektronicznej. Spróbuj ponownie później.",
    "You've sent too many codes today. Try again tomorrow.": "Wysłałeś dziś zbyt wiele kodów.",
    "Couldn't send the code. Check your connection and try again.": "Nie można wysłać kodu.",
    "That code didn't match. Double-check and try again.": "Kod nie pasuje.",
    "Both email and Demora-user contacts must confirm before they can approve: email contacts enter a code you email them, Demora users accept in their app. Adding a contact is a less-strict change; removing one is stricter — both go through delays.": "Zarówno e-mail jak i \"Demora\"-kontakty użytkownika muszą potwierdzić, zanim mogą zatwierdzić: kontakty e-mail wpisać kod, który je wysyłasz, \"Demora\" użytkownicy akceptują w swojej aplikacji. Dodawanie kontaktu jest mniej ograniczoną zmianą; usunięcie jednego jest bardziej surowe — oba idą w opóźnienia.",
    "Elementary": "Podstawowy",
    "Middle school": "Szkoła średnia",
    "High school": "Szkoła średnia",
    "Very easy": "Bardzo łatwe.",
    "Your change is ready": "Twoja reszta jest gotowa.",
    "Your limits have reset": "Twoje limity są resetowane",
    "If any apps still look blocked, open Demora to refresh them.": "Jeśli aplikacje nadal wyglądają zablokowane, otwórz Demora, aby je odświeżyć.",
    "If you denied access, turn on Screen Time for Demora in Settings, then come back.": "Jeśli odmówisz dostępu, włącz czas ekranu dla Demora w ustawieniach, a następnie wróć.",
    "Open Settings": "Otwórz ustawienia",
    "Couldn't check the code — check your connection and try again.": "Nie można sprawdzić kodu – sprawdzić połączenie i spróbować ponownie.",
    "Couldn't send your response — check your connection and try again.": "Nie można było wysłać odpowiedzi – sprawdź połączenie i spróbuj ponownie.",
    "Those changes are still counting down. Wait them out, or turn on an override in Settings → Rules → Overrides to skip the wait.": "Zmiany te nadal odliczają. Czekaj, lub włączy się ominięcie w Ustawieniach → Zasady → Przestrzeganie oczekiwania.",
    "Heads up": "Uwaga.",
    "Feature roadmap": "Funkcjonowanie planu działania",
    "Software roadmap": "Plan działania oprogramowania",
    "features & bugs": "funkcje i błędy",
    "links to Trello": "linky do Trello",
    "Safety code": "Kod bezpieczeństwa",
    "Mark as verified": "Zaznacz jako zweryfikowane",
    "Verified": "Weryfikacja",
    "Security": "Bezpieczeństwo",
    "Available once you've both added each other.": "Dostępny, gdy obaj się dodacie.",
    "Compare this code with your contact in person or on a call. If it matches on both phones, no one has tampered with the connection.": "Porównaj ten kod z kontaktem osobiście lub na wezwanie. Jeśli pasuje do obu telefonów, nikt nie majstrował z połączeniem.",
    "Background blocking may be incomplete": "Blokowanie tła może być niekompletne",
    "iOS limits how many limits and schedules can run in the background at once. Removing a few restores full enforcement.": "iOS ogranicza ilość limitów i harmonogramów w tle. Usunięcie kilku przywraca pełne egzekwowanie.",
    "College": "Kolegium",
    "Nothing — just a new problem": "Nic — tylko nowy problem",
    "Lose one correct answer": "Straciła jedną poprawną odpowiedź",
    "Restart from zero": "Uruchom ponownie od zera",
    "Problems to solve": "Problemy do rozwiązania",
    "If an answer is wrong": "Jeśli odpowiedź jest zła",
    "Enable math override (%@, %d problems)": "Włącz nadpisanie matematyki (%@, %d problemów)",
    "Solve for x:  %dx + %d = %d": "Rozpuszczalnik dla x: %d + %d = %d",
    "Solve for x:  (x − %d) × %d = %d": "Rozwiąż równanie na x: (x − %d) × %d = %d",
    "Solve for x:  %dx + %d = %dx + %d": "Rozwiąż równanie dla x: %dx + %d = %dx + %d",
    "Solve for x:  %d(x + %d) = %d": "Rozpuszczalnik dla x: %d(x + %d) = %d",
    "Wrong — here's a new problem.": "Źle. Mam nowy problem.",
    "Wrong — you lost one correct answer.": "Źle — straciłeś jedną poprawną odpowiedź.",
    "Wrong — starting over.": "Źle — zaczynamy od nowa.",
    "Avatar": "Avatar",
    "Icon": "Ikona",
    "Photo": "Zdjęcie",
    "Type one emoji": "Typ 1 emoji",
    "Choose a photo": "Wybierz zdjęcie",
    "Change photo": "Zmień zdjęcie",
    "Remove photo": "Usuń zdjęcie",
    "Demora %@": "Demora %@",
    "Blocked user": "Zablokowany użytkownik",
    "Two removals are pending. Tap Select, choose both, Apply — then approve with your trusted contact instead of the password.": "Do czasu dotarcia do celu. Kliknij na Wybierz, wybierz obie, Zastosuj — a następnie zatwierdzj zaufany kontakt zamiast hasła.",
    "This time, use your trusted contact — it'll be approved for you.": "Tym razem użyj zaufanego kontaktu. Będzie on zatwierdzony dla ciebie.",
    "Send a request to Alex (sample). A real contact approves from their own Demora app or with an emailed code.": "Wyślij zapytanie do Alex (smutne). Prawdziwy kontakt zatwierdza ich własną aplikację „Demora” lub kodem e-mailowym.",
    "Waiting for approval…": "Czekam na zgodę...",
    "%d changes: %@": "%d zmian: %@",
    "Requested change": "Wnioskowana zmiana",
    "Requested changes": "Wnioskowane zmiany",
    "Awaiting approval": "Oczekujące zatwierdzenia",
    "Tap to enter the email code": "Kliknij, aby wpisać kod e- mail",
    "Encrypted request — re-add this contact to read it.": "Zaszyfrowany wniosek – ponownie dodaj ten kontakt do odczytu.",
    "Privacy Policy": "Polityka prywatności",
    "Terms of Use": "Warunki użytkowania",
    "Approved!": "Zatwierdzone!",
    "Almost done": "Prawie koniec.",
    "Nice work — that's the whole loop. Now set the delays and overrides that will actually protect you.": "Dobra robota, to jest cała pętla. Teraz ustaw opóźnienia i nadrzędne, które faktycznie cię ochroni.",
    "Finish setup": "Ustawienia wykończenia",
    "Tap ‘Add your first limit’, choose an app or two and a daily budget, then queue the change.": "Kliknij na „Dodaj pierwszą granicę”, wybierz aplikację lub dwa oraz budżet dzienny, a następnie wykieruj zmianę.",
    "Your change is waiting out its delay — and you can't wait this one out. Tap ‘Apply now…’ and use the password override. The password is: test": "Twoja zmiana czeka na opóźnienie — i nie możesz czekać tego. Kliknij na przycisk „Zastosowaj teraz...” i użyj nadpisu hasła. Hasło to: test",
    "Now remove it: tap the limit, then ‘Remove this limit’.": "Teraz usunąć: dotknij granicę, a następnie „zmniejsz tę granicę”.",
    "Same again — tap ‘Apply now…’ and enter the password (test).": "To samo ponownie – kliknij przycisk „Uzupełnij teraz...” i wpisz hasło (test).",
    "For this tutorial, only the password works. The password is: test": "W tym poradniku działa tylko hasło. Hasło to: test",
    "For the tutorial, the password is: test": "Dla szkolenia hasło brzmi: test",
    "Everything here is just a sample — nothing is saved and nothing is actually blocked. It's only to show how the app works.": "Wszystko jest tylko próbką — nic nie jest zapisane i nic nie jest faktycznie zablokowane. To tylko pokazanie, jak działa aplikacja.",
    "Applying…": "Naklejam...",
    "Apps": "Aplikacje",
    "Apps that stay usable": "Aplikacje, które pozostają użyteczne",
    "Apps to block": "Aplikacje do zablokowania",
    "Nothing selected": "Nic nie zostało wybrane",
    "Apps blocked": "Aplikacje zablokowane",
    "Apps unblocked": "Aplikacje nieblokowane",
    "Blocking the selected apps": "Zablokowanie wybranych aplikacji",
    "Unblocking the selected apps": "Odblokuj wybrane aplikacje",
    "Apps to unblock": "Aplikacje do odblokowania",
    "Authorize": "Autoryzacja",
    "Authorized ✓": "Upoważniony         í",
    "Back": "Tył",
    "Beta testers": "Beta testery",
    "Block": "Blokuj",
    "Block all except…": "Zablokuj wszystkie poza...",
    "Block app deletion": "Usuwanie aplikacji blokuj",
    "Block apps": "Aplikacje blokujące",
    "Block only…": "Tylko blokuj...",
    "Blocked by Demora": "Zablokowany przez Demora",
    "Blocking is enforced by iOS itself through Screen Time, the same system parental controls use.": "Blokowanie jest wykonywane przez iOS same przez Czas ekranu, ten sam system kontroli rodzicielskiej używa.",
    "Cancel": "Anuluj",
    "Change %@ to %d min/day": "Zmień %@ na %d min/dobę",
    "Changes that make things LESS STRICT (raise a limit, remove a block, add a free period) wait out your second delay — usually set longer.": "Zmiany, które sprawiają, że rzeczy LESS STRICT (zwiększaj limit, zdejmij blok, dodaj wolny okres) czekają na drugie opóźnienie – zwykle ustawiają dłużej.",
    "Changes that make things STRICTER (add a limit, lower minutes, add a schedule) wait out your first delay.": "Zmiany, które sprawiają, że rzeczy STRICTER (dodaj limit, niższe minuty, dodać harmonogram) czekać na pierwsze opóźnienie.",
    "Changes you make will appear here with a countdown.": "Zmiany, które dokonasz, pojawią się tutaj z odliczaniem.",
    "Choose apps": "Wybierz aplikacje",
    "Close": "Zamknij",
    "Confirm password": "Potwierdź hasło",
    "Continue": "Kontynuuj",
    "Couldn't load names (check iCloud/network).": "Nie można wczytać nazw (zaznacz iCloud/network).",
    "Couldn't submit — make sure you're signed into iCloud and try again.": "Nie można się złożyć – upewnij się, że jesteś zapisany na iCloud i spróbuj ponownie.",
    "Current delays": "Obecne opóźnienia",
    "Current: %@": "Bieżący: %@",
    "Daily limit": "Limit dzienny",
    "Day %d of every month": "Dzień %d każdego miesiąca",
    "Day of month": "Dzień miesiąca",
    "Delay": "Opóźnienie",
    "Delay for LOOSER changes": "Opóźnienie w przypadku zmian LOOSER",
    "Delay for STRICTER changes": "Opóźnienie w przypadku zmian w systemie STRICTER",
    "Delays": "Opóźnienia",
    "Difficulty": "Trudności",
    "Disable math override": "Wyłącz obejście matematyki",
    "Disable password override": "Wyłącz obejście hasła",
    "Done": "Gotowe",
    "Duration": "Czas trwania",
    "During a free period, limits don't block and usage inside the window doesn't count toward them — time used before the window still does.": "W okresie wolnym granice nie blokują i nie używają w oknie, co nie oznacza, że są używane przed oknem.",
    "Easy": "Spokojnie.",
    "Enable math override": "Włącz obejście matematyki",
    "Enable math override (%@)": "Włącz nadpisywanie matematyki (%@)",
    "Enable password override": "Włącz obejście hasła",
    "Enable/update password override": "Włącz/aktualizuj obejście hasła",
    "End": "Koniec",
    "End early…": "Skończ wcześniej...",
    "End session early: %@": "Początek sesji: %@",
    "Ends": "Końce",
    "Enter password": "Podaj hasło",
    "Every change you make waits out a delay you chose, counting down in the background. You can always change your rules — just not in a moment of weakness.": "Każda zmiana, którą dokonasz, czeka na twój wybór opóźnienia, odliczając się od tego, co się dzieje w tle. Zawsze możesz zmienić swoje zasady — tylko nie w chwili słabości.",
    "Every day": "Codziennie",
    "Everything on the iPhone is blocked during the window except the apps picked here.": "Wszystko na iPhone jest zablokowane w czasie okna, z wyjątkiem aplikacji wybranych tutaj.",
    "Free period": "Okres wolny",
    "Today's usage is reported by iOS Screen Time, which can be slow to load or briefly show nothing. If it looks empty, tap the refresh arrow a couple of times.": "Dzisiejsze użycie jest zgłaszane przez iOS Screen Time, który może być wolny do załadowania lub krótkiego nie pokazuje niczego. Jeśli wygląda puste, kliknąć strzałkę odświeżając kilka razy.",
    "Free": "Wolny",
    "Free period: %@ (%d min)": "Okres wolny: %@ (%d min)",
    "Free period — nothing is blocked": "Okres wolny – nic nie jest zablokowane",
    "Temporarily lifts everything — no app blocks apply, and usage during the free period doesn't count toward your limits.": "Tymczasowo podnosi wszystko — nie stosuje się bloków aplikacji, a korzystanie z nich w okresie wolnym nie jest wliczone w granice.",
    "Free periods": "Okresy wolne",
    "Friction, not passwords": "Płyta, nie hasła",
    "Get started": "Zaczynaj",
    "Hard": "Twardy",
    "Home": "Strona główna",
    "Hours": "Godziny",
    "How does it work?": "Jak to działa?",
    "Incorrect password": "Niepoprawne hasło",
    "Keep it appropriate — names are reviewed, and inappropriate ones won't be added.": "Nie należy tego zmieniać – przeglądują się nazwy, a nie będą dodawane nieodpowiednie.",
    "Language": "Język",
    "Demora needs Screen Time authorization to set app limits and block apps. iOS will ask for your confirmation.": "Demora potrzebuje autoryzacji czasu ekranu do ustawienia limitów aplikacji i aplikacji blokujących. iOS poprosi o potwierdzenie.",
    "Demora wouldn't exist without the people who tested it, broke it, and told me about it. Thank you. ❤️": "Demora nie istniałby bez ludzi, którzy ją przetestowali, złamali i opowiedział mi o tym. Dziękuję.",
    "Less strict": "Mniej rygorystyczne",
    "Less-strict delay": "Mniej ograniczone opóźnienie",
    "Limit": "Granica",
    "Limits": "Limity",
    "Limits won't block and usage won't count during this window.": "Ograniczenia nie będą blokować i używanie nie będzie w tym oknie liczyć.",
    "Limits: daily time budgets per app. When the minutes run out, the app is blocked until midnight.": "Limity: dzienne budżety czasu na aplikację. Kiedy kończy się protokół, aplikacja jest zablokowana do północy.",
    "Looser changes": "Zmiany wolniejszego",
    "Looser changes wait %@": "Zmiany wyludniające czekają na %@",
    "Math override": "Określenie matematyczne",
    "Math problems": "problemy z matematyką",
    "Medium": "Średnia",
    "Minutes": "Protokół",
    "Mode": "Tryb",
    "Monthly schedules can't cross midnight — set the end time after the start time.": "Miesięczny harmonogram nie może przekraczać północy — wyznacza czas zakończenia po rozpoczęciu.",
    "More strict": "Bardziej rygorystyczne",
    "More-strict delay": "Opóźnienie bardziej ograniczone",
    "Most screen-time apps protect your rules with a password — which you know, so you cave. Demora protects them with time instead.": "Większość aplikacji czasu ekranu chroni Twoje zasady hasłem, który wiesz, więc unikniesz. Demora chroni je z czasem.",
    "Name": "Nazwa",
    "Names will appear here soon.": "Wkrótce pojawią się tu nazwiska.",
    "New free period": "Nowy okres wolny",
    "New limit": "Nowa granica",
    "New password": "Nowe hasło",
    "New schedule": "Nowy harmonogram",
    "New session": "Nowa sesja",
    "New session…": "Nowa sesja...",
    "No free periods": "Brak wolnych okresów",
    "No limits yet": "Dotychczas brak ograniczeń",
    "No overrides — delays are absolute": "Brak nadrzędnych przeterminowań – opóźnienia są bezwzględne",
    "No pending changes": "Brak zmian w toku",
    "No schedules": "Brak rozkładów",
    "No thanks": "Nie, dzięki.",
    "Nothing planned": "Nic nie zaplanowano",
    "Nth weekday": "N-ty dzień",
    "OK": "Dobrze.",
    "Off": "Wyłącz",
    "On": "Włączone",
    "One-off and unplanned, but still delay-gated. A block session waits %@; an unblock session waits %@. Ending early flips the rule (or use an override).": "Jednorazowa i nieplanowana, ale wciąż opóźniona. Blokada czeka na %@; sesja nierozłączna czeka na %@. Kończając wcześniej przerzuca regułę (lub używa nadrzędnego).",
    "Only the apps picked here are blocked during the window.": "Tylko aplikacje wybrane tutaj są zablokowane podczas okna.",
    "Overrides": "Wyjątki",
    "Overrides enabled": "Przekierowania włączone",
    "Overrides let you skip a pending change's countdown. They're off by default. Adding one later counts as a less-strict change; removing one counts as stricter — both go through delays.": "Przestrzeganie pozwala pominąć wyczekiwaną zmianę. Są domyślnie wyłączone. Dodanie jednego później liczy się jako mniej ograniczona zmiana; usunięcie jednego zlicznika jako surowsze — oba idą w opóźnienia.",
    "Overrides skip a pending change's countdown. Enabling or weakening one is a less-strict change; disabling or strengthening one is stricter. All edits here go through the matching delay.": "Przejrzysty pomija wyczekiwany odliczanie zmian. Włączanie lub osłabienie jest mniej ograniczoną zmianą, zniesienie lub wzmocnienie jest bardziej surowe. Wszystkie edycje tutaj przechodzi przez opóźnienie dopasowania.",
    "A change for this setting is already pending. Cancel it on the Home tab first if you want something different.": "Zmiana dla tego ustawienia jest już w toku. Anuluj to w zakładce Dom, jeśli chcesz czegoś innego.",
    "Already pending": "W toku",
    "A person you choose approves skipping a countdown — by email code or from their own Demora app. You can also add more later in Settings → Trusted contacts.": "Osoba, którą wybierasz, pomija odliczanie — kodem e-mail lub z własnej aplikacji „Demora”. Możesz dodać później w Ustawieniach → Zaufane kontakty.",
    "Add": "Dodaj",
    "Message (optional)": "Wiadomość (opcjonalnie)",
    "Sent along with the request so they know why you're asking.": "Wysłano razem z prośbą, żeby wiedzieli, dlaczego pytasz.",
    "e.g. why you need this": "np. dlaczego tego potrzebujesz",
    "%@ — Note: %@": "%@ — Uwaga: %@",
    "Your request was denied.": "Twoja prośba została odrzucona.",
    "Send a new request…": "Wyślij nowe żądanie...",
    "Cancels this request and lets you pick contacts again.": "Anuluje tę prośbę i pozwala na ponowne wybranie kontaktów.",
    "Coming soon": "Już idę.",
    "Appearance": "Wygląd",
    "Theme": "Motyw",
    "System": "System",
    "Light": "Światło",
    "Dark": "Ciemny",
    "/ de·mo·ra /  noun, Spanish": "/de·mo·ra / pseudonim, hiszpański",
    "a delay; the time that passes before something takes effect.": "opóźnienie; czas, który mija zanim coś zacznie działać.",
    "an iPhone app that protects your screen-time rules with definition 1 instead of a password.": "aplikacja iPhone chroniąca zasady czasu ekranu z definicją 1 zamiast hasłem.",
    "Coming soon — payments aren't available yet.": "Wkrótce przyjdą — płatności nie są jeszcze dostępne.",
    "Password": "Hasło",
    "Password override": "Ogranicza hasło",
    "Passwords don't match": "Nie pasują do nich.",
    "Pay %@": "Płatność %@",
    "Pay %@ to apply this change now": "Zapłacić %@ za zastosowanie tej zmiany już teraz",
    "Pending change": "Do czasu zmiany",
    "Pending changes": "Do czasu zmian",
    "Pending changes show on the Home tab with a live countdown. You can cancel them anytime before they apply.": "Do czasu zmiany pokaż na karcie Home z odliczaniem na żywo. Możesz je anulować zanim będą one stosowane.",
    "Plan %@: %@ (%@)": "Plan %@: %@ (%@)",
    "Plan a window": "Zaplanuj okno",
    "Plan a window…": "Zaplanuj okno...",
    "Plan ahead for specific dates — a trip, a weekend, an exam. Doesn't repeat. Planning a block is stricter; planning a free period is less strict.": "Planowanie daty, wycieczka, weekend, egzamin. Nie powtarza. Planowanie bloku jest bardziej surowe; planowanie wolnego okresu jest mniej surowe.",
    "Planned (one-off)": "Planowane (pojedyncze)",
    "Planned window": "Planowane okno",
    "Purchasing…": "- Przekupywanie...",
    "Queue change": "Zmiana kolejki",
    "Queue: turn off": "Linia kolejki: wyłącz",
    "Queue: turn on": "Wzmocnienie: włączyć",
    "Recurring schedules": "Powrót rozkładów",
    "Remove free period: %@": "Usuń wolny okres: %@",
    "Remove limit: %@": "Usuń limit: %@",
    "Remove planned window: %@": "Usuń planowane okno: %@",
    "Remove schedule: %@": "Usuń schemat: %@",
    "Remove this limit": "Usuń tę granicę",
    "Remove…": "Usuń...",
    "Repeating windows: every day, chosen weekdays, or monthly patterns. Adding waits %@; removing waits %@.": "Powtórzyć okna: codziennie, wybierane dni w tygodniu lub wzory miesięczne. Dodawanie oczekiwania %@; usuwanie czeków %@.",
    "Repeats": "Podwójny",
    "Schedule": "Harmonogram",
    "Schedules": "Harmonogramy",
    "Schedules: recurring or one-off windows that block chosen apps — or everything except a chosen few. Plus free periods where time doesn't count.": "Harmonogram: powtarzające się lub jednorazowe okna blokujące wybrane aplikacje — lub wszystko poza wybranymi kilkoma. Plus darmowe okresy, w których czas się nie liczy.",
    "Screen Time access": "Dostęp do Czasu przed ekranem",
    "Sessions": "Sesje",
    "Set 'less strict' delay to %@": "Ustaw \"mniej surowe\" opóźnienie na %@",
    "Set 'more strict' delay to %@": "Ustaw \"bardziej surowe\" opóźnienie na %@",
    "Settings": "Ustawienia",
    "Setup": "Ustawienia",
    "Simulate payment (beta)": "Symulacja płatności (beta)",
    "Skip the wait": "Pomiń czekanie",
    "Solve %d math problems (%@)": "Rozwiąż %d zadań matematycznych (%@)",
    "Solve math problems": "Rozwiąż problemy z matematyką",
    "Start": "Początek",
    "Start using Demora": "Zacznij używać Demora",
    "Starts": "Rozpoczęcie",
    "Stricter changes": "Bardziej surowe zmiany",
    "Stricter changes wait %@": "Bardziej restrykcyjne zmiany w badaniu %@",
    "Submit": "Wyślij",
    "Temporarily lifts limits, schedules, and block sessions for the chosen apps.": "Tymczasowo podnosi limity, harmonogramy i blokowania sesji dla wybranych aplikacji.",
    "Thanks for testing Demora!": "Dzięki za badania Demora!",
    "This app is blocked right now — by a limit, a schedule, or a session. Changing your rules takes a delay; open Demora to queue a change.": "Aplikacja ta jest już teraz zablokowana — przez limit, harmonogram lub sesję. Zmiana zasad wymaga opóźnienia; otwarcie Demora w kolejce zmiany.",
    "If it should already be unblocked, iOS is sometimes slow to apply a background change — open Demora for an immediate unblock.": "Jeśli już powinien być wyłączony, iOS jest czasem wolny do zastosowania zmiany tła — otworzyć Demora dla natychmiastowego odblokowania.",
    "Two delays rule everything": "Dwa opóźnienia rządzą wszystkim",
    "Type": "Typ",
    "Unblock": "Rozblokuj",
    "Unblock apps": "Rozblokuj aplikacje",
    "Unlock": "Odblokuj",
    "Wait this long before any change that loosens your rules takes effect. Usually set longer than the first.": "Czekaj na długo, zanim każda zmiana, która rozluźnia twoje zasady, zacznie działać.",
    "Wait this long before any change that tightens your rules takes effect.": "Poczekaj aż zmiana zaostrzy twoje zasady.",
    "Want your name in the app's beta-tester thanks page? Pick whatever you'd like to be called.": "Chcesz, aby twoje imię było w app's beta-tester dziękczynienia? Wybierz cokolwiek chcesz, żeby się nazywało.",
    "Weekday": "Tydzień",
    "Weekdays": "Tygodni",
    "What can it do?": "Co może zrobić?",
    "What's in the box": "Co jest w pudełku?",
    "When": "Kiedy",
    "When on, deleting ANY app from this iPhone is blocked — including Demora itself, so blocks can't be bypassed by uninstalling.": "Kiedy się rozpoczniesz, usuwanie każdej aplikacji z tego iPhone jest zablokowane – w tym „Demora” samego, więc bloki nie mogą być pominięte przez odinstalowanie.",
    "Which one": "Który?",
    "Window": "Okno",
    "Wrong — new problem": "Źle — nowy problem",
    "You're in! Your name will appear in the beta testers page once it's approved.": "Twoje nazwisko pojawi się na stronie beta testerów, gdy tylko się zatwierdzą.",
    "You're set": "Gotowe.",
    "Your name is in — it'll show up once approved.": "Twoje imię jest w - pojawi się raz po akceptacji.",
    "Your name or nickname": "Twoje imię lub pseudonim",
    "e.g. Airport, weekend trip": "np. lotnisko, weekendowa podróż",
    "e.g. Bedtime": "np. czas snu",
    "e.g. Deep work": "np. głęboka praca",
    "e.g. Instagram": "np. Instagram",
    "e.g. Lunch break": "np. przerwa na lunch",
    "free period": "okres wolny",
    "limit": "ograniczenie",
    "now": "Teraz",
    "planned window": "planowane okno",
    "schedule": "harmonogram",
    "session": "sesja",
    "A passcode is saved. Open the guide below to view it.": "Zapisuje się kod. Otwórz przewodnik poniżej, aby go zobaczyć.",
    "Access requested. It unlocks after your less-strict delay — track it on the Home tab, where you can also use an override to skip the wait.": "Wymagany dostęp. Odblokowuje się po mniej ograniczonym opóźnieniu — śledzi go na karcie Home, gdzie można również użyć nadrzędnego, aby pominąć czek.",
    "Can't reach this contact right now — they may have removed Demora or signed out. They won't be able to approve until they're back.": "Nie można się teraz dostać do tego kontaktu — mogli usunąć Demora lub się oddalić. Nie będą mogli zaakceptować, dopóki nie wrócą.",
    "Couldn't start the walkthrough": "Nie mogłem zacząć spaceru.",
    "Bug tracker": "Śledź błędów",
    "Demora can't stop you from turning off its Screen Time access in iOS Settings — but a friend can. If Screen Time itself is locked with someone else's passcode, iOS blocks any change to Demora's access, while Demora keeps doing all the blocking.": "Demora nie może powstrzymać od wyłączenia dostępu czasu ekranu w ustawieniach iOS, ale przyjaciel może. Jeżeli Screen Time jest zamknięty kodem przepustki kogoś innego, iOS blokuje każdą zmianę na „Demora” dostęp, podczas gdy Demora nadal blokuje.",
    "Demora couldn't safely back up your current setup, so the replay was cancelled to protect your limits. Nothing was changed. Please try again in a moment.": "Demora nie mógł bezpiecznie włączyć swojego aktualnego ustawień, więc powtórka została anulowana, aby chronić swoje granice. Nic się nie zmieniło. Proszę spróbować ponownie w chwili.",
    "Done. Now you can't disable Demora's access — or change the passcode — without your friend. To undo it later, your friend enters the passcode and turns it off.": "Gotowe. Teraz nie można wyłączyć dostępu Demora — lub zmienić kod dostępu — bez przyjaciela. Aby go cofnąć później, Twój przyjaciel wpisuje się w kod przepustki i wyłącza go.",
    "Email limit": "Limit poczty elektronicznej",
    "Emoji": "Emoji",
    "Friend: save the passcode here so it isn't lost. It's only shown from this page, which is behind your delay.": "Przyjaciel: Zapisz tutaj kod, aby nie został zagubiony. Jest wyświetlany tylko na tej stronie, która jest za Twoim opóźnieniem.",
    "Hand your phone to your friend. Have THEM enter a 4-digit passcode you don't see — don't watch.": "Oddaj telefon znajomemu. Niech wejdą 4-cyfrowe kody, których nie widzisz — nie oglądaj.",
    "Heads up: on your iOS version, a limit only counts screen time from the moment you add it — time you already spent earlier today isn't included. Update to iOS 17.4 or later for exact daily counting.": "Nagląca: na wersji iOS limit liczy tylko czas ekranu od momentu dodania go – czas, który już spędziłeś dzisiaj nie jest włączony. Aktualizacja do iOS 17.4 lub później dla dokładnej dziennej liczenia.",
    "Make Demora impossible to disable": "Spraw, aby Demora nie było możliwe wyłączenie",
    "Onboarding demo — you can skip below. It's always available again in Settings → Help.": "Debugowanie demo — można pominąć poniżej. Jest zawsze dostępny w Ustawieniach → Pomoc.",
    "One more safeguard": "Jeszcze jeden środek ochronny",
    "Open Settings → Screen Time on this iPhone. If it's off, turn it on.": "Otwórz ustawienia → Czas ekranu na tym iPhone. Jeśli jest wyłączony, włącz go.",
    "Open the guide": "Otwórz przewodnik",
    "Opening this is delayed on purpose — so you can't impulsively look up how to undo your own lock.": "Otwieranie tego jest opóźnione celowo, więc nie można impulsywnie sprawdzić jak cofnąć własny zamek.",
    "Passcode": "Kod paszportowy",
    "Pick someone you trust and can reach. If the passcode and its recovery Apple ID are both lost, removing it may require erasing the device.": "Wybierz kogoś, komu ufasz i dosięgniesz. Jeśli kod dostępu i jego odzyskanie identyfikator Apple są stracone, usunięcie go może wymagać usunięcia urządzenia.",
    "Prevent disabling": "Zapobieganie wyzwalaniu",
    "Protection": "Ochrona",
    "Replay walkthrough": "Powtórz przejście",
    "Request access": "Dostęp do wniosku",
    "Save": "Zapisz",
    "Saved passcode: %@": "Zaoszczędzony kod: %@",
    "Unlock viewing the stored passcode": "Odblokuj przechowywany kod dostępu",
    "how to lock it with a friend": "jak zamknąć je z przyjacielem",
    "Screen Time passcode": "Kod przepustnicy w czasie ekranu",
    "none saved": "brak zapisanych",
    "saved": "zapisany",
    "Enter passcode": "Podaj kod dostępu",
    "save it here so it isn't lost": "Zapisz tutaj, żeby nie było stracone",
    "replaces the saved one": "zastępuje zapisany",
    "behind your delay": "za opóźnieniem",
    "View passcode": "Widok kodu",
    "Change the passcode?": "Zmienić kod?",
    "Are you sure? There is no way to undo this — the saved passcode is replaced only when you save a new one.": "Czy jesteś pewien? Nie ma sposobu na cofnięcie tego - zapisany kod jest zastąpiony tylko wtedy, gdy zapisasz nowy.",
    "The friend who set the Screen Time passcode can store it here so it isn't lost. Going back without saving keeps the current one.": "Przyjaciel, który ustawił kod czasu ekranu może go tu przechowywać, więc nie jest stracony.",
    "Viewing the stored passcode is behind your less-strict delay: request it, wait out the delay, and you get one look. After that it locks again.": "Wyświetlenie przechowywanego kodu jest za mniej ograniczonym opóźnieniem: zapytaj go, czekaj opóźnienie, a dostaniesz jeden wygląd. Po tym, że ponownie się zablokuje.",
    "Access is spent — viewing it again needs a new request.": "Dostęp do niego jest wydawany — jego zwrócenie się wymaga nowej prośby.",
    "Screen Time usually only allows a 4-digit passcode — are you sure this is correct?": "Czas ekranowy zazwyczaj pozwala na 4-cyfrowy kod dostępu — czy jest to poprawne?",
    "Saved ✓": "Uratowane        ▶",
    "Show me how": "Pokaż mi jak",
    "Skip and set up manually": "Pomiń i ustaw ręcznie",
    "Skip walkthrough": "Pomiń spacer",
    "Skip — set up manually": "Pomiń – ustaw ręcznie",
    "Store the Screen Time passcode": "Przechowuj kod przepustnicy czasu ekranu",
    "Take photo": "Zdjęcia",
    "Takes about 2 minutes, and you need a second person physically with you.": "Zajmuje to około 2 minut, a potrzebuje pan drugiej osoby fizycznie.",
    "Tap “Lock Screen Time Settings” (or “Use Screen Time Passcode”).": "Kliknij przycisk „Ustawienia czasu ekranu” (lub „Użyj kodu przepustnicy ekranu”).",
    "Thank you. ❤️": "Dziękuję.",
    "That's okay. Without Screen Time access Demora can't block apps, but you can continue and turn it on later.": "Bez dostępu do czasu ekranu Demora nie może zablokować aplikacji, ale można kontynuować i włączyć je później.",
    "That's the whole loop. Your real limits, schedules, and settings are still here — nothing changed.": "Twoje rzeczywiste limity, harmonogramy i ustawienia wciąż tu są, nic się nie zmieniło.",
    "There's a way to make Demora impossible to turn off — with a friend's help. It takes about 2 minutes and needs a second person physically with you.": "Jest sposób, aby Demora nie było możliwe do wyłączenia — przy pomocy przyjaciela. To trwa około 2 minut i potrzebuje drugiej osoby fizycznie z tobą.",
    "They call themselves “%@”.": "Nazwano je „%@”.",
    "This guide is behind your less-strict delay: request it, wait out the delay, and you get one open. After you view it, it locks again.": "Ten przewodnik jest za mniej rygorystycznym opóźnieniem: poprosić, poczekać na opóźnienie, a dostaniesz jeden otwarty. Po obejrzeniu go, to znowu zamyka.",
    "Unavailable": "Niedostępny",
    "Unlock the “Prevent disabling” guide": "Odblokuj przewodnik „Preventmounting”",
    "Use photo": "Użyj zdjęcia",
    "When asked for Screen Time Passcode Recovery, your friend signs in with THEIR OWN Apple ID — not yours. That's what stops you from resetting the passcode on your own.": "Poproszony o odzyskanie kodu czasu ekranu, Twój przyjaciel zapisuje się za pomocą THEI Own Apple ID – nie twojego. To powstrzymuje cię od samodzielnego resetowania kodu przepustki.",
    "You can always find this later under Help — but there it's behind a delay.": "Zawsze możesz znaleźć to później pod pomocą — ale to za opóźnieniem.",
    "You can change these any time under General blocking. Each change then goes through your delays.": "Możesz je zmienić w dowolnym momencie podblokowania ogólnego.",
    "Your one-time access is ready.": "Twój jednorazowy dostęp jest gotowy.",
    "lock it with a friend": "Zamknij ją z przyjacielem.",
    "your setup stays safe": "Twoje ustawienia pozostają bezpieczne",
    "—": "—",
]
